// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMeta } from "./EventMeta";

/**
 * The wire shape of `GET /active-event` — the **Director's currently-active event**, or
 * `null` when none is set (issue #90).
 *
 * The active event is **Director (server-side) state**: there is exactly one Race Director
 * running one event, so the selected event lives on the Director, not in each browser. Every
 * client reads this on connect/reload to resume into the workspace (or fall to the picker when
 * `null`). The `event` field is the full [`EventMeta`] so a client renders the context header
 * without a second round-trip.
 */
export type ActiveEvent = { 
/**
 * The active event's metadata, or `null` when no event is active (→ the picker).
 */
event: EventMeta | null, };
