// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the timing source / adapter that produced an event.
 */
export type AdapterId = string;
