// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a [`Command::Advance`] **did** with the next heat (#401).
 *
 * Every value here is a **success** — `Advance` recorded its `Final -> Advanced` transition in
 * all of them; they differ in whether Live control moved on, and if not, why. Externally tagged,
 * so it maps to a TS string-union
 * (`"LoadedOnDeck" | "Generated" | "RoundComplete" | "AwaitingResult" | "Blocked" | "Untagged"`).
 *
 * The "nothing to advance to" values are stated **positively**, never inferred from an absent
 * [`AdvanceOutcome::loaded`]: inferring a no-op from an absence is precisely the bug (#395, #401)
 * this type exists to end.
 */
export type AdvanceStop = "LoadedOnDeck" | "Generated" | "RoundComplete" | "AwaitingResult" | "Blocked" | "Untagged";
