// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvanceStop } from "./AdvanceStop";
import type { ScheduledHeat } from "./ScheduledHeat";

/**
 * What a [`Command::Advance`] actually **did** (#401).
 *
 * `Advance` is two steps, not one: it records the heat's `Final -> Advanced` transition *and*
 * loads the next heat to run. Only the first always happens, and a bare `{"ok":true}` reported
 * all three second steps identically — loaded the on-deck heat, generated one, found nothing.
 * That is the same defect #395 fixed for [`FillRound`](Command::FillRound), and worse in
 * practice: "nothing to advance to" is a *routine* end-of-round state rather than a
 * misconfiguration, so the ambiguous ack was hit on every round rather than rarely.
 */
export type AdvanceOutcome = { 
/**
 * The heat Live control is now on, when the advance loaded one — `null` for every
 * "nothing to advance to" [`stopped`](Self::stopped).
 *
 * Always serialized, `null` included, and never the thing a caller reads to learn that
 * nothing happened: [`stopped`](Self::stopped) says that outright.
 */
loaded: ScheduledHeat | null, 
/**
 * What the advance did with the next heat — the machine-readable discriminator, always
 * present.
 */
stopped: AdvanceStop, 
/**
 * The same thing in one RD-facing sentence, naming the advanced heat, the loaded heat and
 * the round by their **friendly names** (never an id). Safe to show verbatim.
 */
detail: string, };
