// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a marshaling audit entry — *what sort of action* a logged fact was (#55).
 *
 * Derived purely from the event **type**, this is the "defensible results" surface: every
 * marshaling correction is a recorded, attributable, reversible fact (marshaling.html §3.3).
 * The automatic timer pass is included as [`AuditKind::Pass`] so the panel can distinguish a
 * *human ruling* from an *automatic detection* — but note `marshaling_log` only folds the
 * human rulings into entries (a heat has far too many passes to list); `Pass` exists so a
 * future "show automatic detections too" toggle is an additive consumer, not a model change.
 *
 * There is deliberately **no actor / who**: per the no-login decision every change is implicitly
 * the RD, so naming an actor would be a false precision (marshaling.html §3.3, the audit records
 * what-changed-when, and the single-RD trust model supplies the who).
 */
export type AuditKind = "Voided" | "Inserted" | "Adjusted" | "Split" | "PenaltyApplied" | "RulingReversed" | "HeatVoided" | "Pass";
