// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditKind } from "./AuditKind";
import type { LogRef } from "./LogRef";

/**
 * A single reverse-chronological marshaling audit entry (#55): *what changed, when, what kind*.
 *
 * A thin, render-ready fact derived from one logged marshaling event. `at` is the event's
 * `recorded_at` (the server wall-clock instant the log received it), so the panel can show
 * "when"; `summary` is a short human string ("Lap split", "DQ applied to node-2"); `kind`
 * drives the visual treatment. There is no actor field by design (see [`AuditKind`]).
 */
export type AuditEntry = { 
/**
 * What kind of marshaling action this was — derived from the event type.
 */
kind: AuditKind, 
/**
 * When the log received this fact (microseconds since the Unix epoch), if recorded.
 * `None` when the append carried no arrival timestamp (e.g. a replay with none supplied).
 */
at: number | null, 
/**
 * The global append offset of this fact — a stable identity for the entry (and what a
 * later "reverse this" would target). Lets the UI key the list deterministically.
 */
at_ref: LogRef, 
/**
 * A short human-readable description of the change.
 */
summary: string, };
