// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditKind } from "./AuditKind";
import type { CompetitorRef } from "./CompetitorRef";
import type { LogRef } from "./LogRef";

/**
 * A single reverse-chronological marshaling audit entry (#55): *what changed, when, what kind*.
 *
 * A thin, render-ready fact derived from one logged marshaling event. `at` is the event's
 * `recorded_at` (the server wall-clock instant the log received it), so the panel can show
 * "when"; `summary` is a short human string ("Lap split", "DQ applied"); `kind` drives the visual
 * treatment. There is no actor field by design (see [`AuditKind`]).
 *
 * `competitor` carries the **structured** competitor ref the action targeted (when it targets one),
 * kept *out* of `summary` on purpose: the ref is a source-local handle (a pilot id, a node seat),
 * not a friendly name, so the client resolves it to the pilot's **callsign** and composes the final
 * line (e.g. prepends "Ace · " to "DQ applied"). A server-baked `summary` cannot be re-resolved, so
 * the name lives in this field, not in the string (the Marshaling raw-id bug, #214 follow-up). It is
 * `None` for the lap-/heat-addressed actions that name no competitor (void, split, heat-void, …).
 */
export type AuditEntry = { 
/**
 * What kind of marshaling action this was — derived from the event type.
 */
kind: AuditKind, 
/**
 * When the log received this fact (microseconds since the Unix epoch), if recorded.
 * `None` when the append carried no arrival timestamp (e.g. a replay with none supplied).
 */
at: number | null, 
/**
 * The global append offset of this fact — a stable identity for the entry (and what a
 * later "reverse this" would target). Lets the UI key the list deterministically.
 */
at_ref: LogRef, 
/**
 * The competitor this action targeted, as a **structured ref** the client resolves to a
 * callsign and composes into the displayed line. `None` for actions that name no competitor.
 */
competitor: CompetitorRef | null, 
/**
 * A short human-readable description of the change — **without** the raw competitor ref (that
 * is carried structured in `competitor` so the client can show the resolved callsign instead).
 */
summary: string, };
