// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from "./TimerId";

/**
 * The answer to `POST /timers/{timer_id}/calibration` (#355): **what was dispatched**, after
 * clamping — never a readback.
 *
 * RotorHazard does not echo `set_enter_at_level` / `set_exit_at_level` (verified on v4.3.0 and
 * v4.4.0: neither handler emits, and `calibration.py` only triggers an internal `Evt`), so there
 * is nothing synchronous to answer with. Reporting the requested value under a readback's name
 * would claim success for a write that may never have reached the detector — the exact failure
 * this page exists to catch — so the field names deliberately match the **request**, not
 * [`NodeSignal`].
 *
 * **Confirmation is by poll.** The Director asks RotorHazard to re-broadcast
 * `enter_and_exit_at_levels` right after the write, which arrives on the same socket that feeds
 * `GET /timers/{id}/signal`; the console confirms by seeing [`NodeSignal::enter_at`] /
 * [`NodeSignal::exit_at`] come back holding the value it sent.
 */
export type CalibrationDispatch = { 
/**
 * The timer the write was dispatched to.
 */
timer: TimerId, 
/**
 * The node it addresses, `0`-based.
 */
node: number, 
/**
 * The clamped **enter** threshold that was queued, or absent if the request did not carry one.
 * May differ from what was asked for — that is the clamp, and it is worth showing.
 */
enter_at?: number, 
/**
 * The clamped **exit** threshold that was queued, or absent if the request did not carry one.
 */
exit_at?: number, };
