// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /timers/{timer_id}/calibration` (#355) — set one node's detection thresholds.
 *
 * **Only the threshold that changed is sent.** The Tune page writes on interaction end, per
 * threshold, so a slider release carries exactly one of the two; both absent is a refusal rather
 * than a no-op success, because "I asked for nothing and it worked" is the shape of every silent
 * calibration failure.
 */
export type CalibrationRequest = { 
/**
 * The node to calibrate, `0`-based — RotorHazard's `seat_index`, and the same index
 * [`NodeSignal::node`] carries.
 */
node: number, 
/**
 * The new **enter** threshold, or absent to leave it alone. Clamped to
 * [`RSSI_MIN`]..=[`RSSI_MAX`].
 */
enter_at?: number, 
/**
 * The new **exit** threshold, or absent to leave it alone. Clamped to
 * [`RSSI_MIN`]..=[`RSSI_MAX`].
 */
exit_at?: number, };
