// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureThreshold } from "./CaptureThreshold";

/**
 * The body of `POST /timers/{timer_id}/capture` (#355) — have the timer **measure** one node's
 * threshold instead of being told it.
 *
 * The answer to the gap #411 names: a fresh RD with no saved profile and a badly-tuned timer has
 * no starting point, and GridFPV deliberately ships no fabricated default because the right level
 * depends on craft, VTX power, antenna and gate geometry — none of which GridFPV knows. A capture
 * measures the RD's actual craft on their actual gate, which is the only honest way to bootstrap.
 */
export type CaptureRequest = { 
/**
 * The node to capture on, `0`-based — RotorHazard's `seat_index`, and the same index
 * [`NodeSignal::node`] and [`CalibrationRequest::node`] carry.
 */
node: number, 
/**
 * Which threshold to capture.
 */
threshold: CaptureThreshold, };
