// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from "./TimerId";

/**
 * The answer to `POST /timers/{timer_id}/capture` (#355): **what was dispatched**, never a
 * captured level — the level does not exist yet when this returns.
 *
 * A capture is dispatched, then measured for [`window_ms`](CaptureDispatch::window_ms), and only
 * then does RotorHazard have a value. So this is a `200` meaning *the capture was started*, and
 * the fields exist to let the console count the window down and say what it is waiting for.
 *
 * **Confirmation is by poll**, exactly as it is for [`CalibrationDispatch`]: the level arrives as
 * [`NodeSignal::enter_at`] / [`NodeSignal::exit_at`] on a later `GET /timers/{id}/signal`, fed
 * both by RotorHazard's end-of-capture `node_enter_at_level` broadcast and by the readback the
 * driver fires once the window has elapsed.
 */
export type CaptureDispatch = { 
/**
 * The timer the capture was started on.
 */
timer: TimerId, 
/**
 * The node it addresses, `0`-based.
 */
node: number, 
/**
 * How long RotorHazard samples for **each** threshold, in milliseconds —
 * [`CAPTURE_WINDOW_MS`]. The RD has to fly the pass inside the *first* one, which starts now.
 */
window_ms: number, 
/**
 * How long after the press the **exit** window opens — [`CAPTURE_EXIT_DELAY_MS`] (#465).
 *
 * The console needs it to say the true thing while the capture runs: for the first stretch the
 * instruction is *fly the pass*, and for the second it is *let it clear the gate*. One
 * countdown over the whole thing would send the RD back through the gate during the exit
 * window, which is the one way to spoil the measurement.
 */
exit_delay_ms: number, 
/**
 * How long after the **last** window GridFPV waits for the levels before reporting the capture
 * did not land — [`CAPTURE_SETTLE_MS`].
 */
settle_ms: number, 
/**
 * The **enter** level the timer was reporting when the capture started, if it was reporting
 * one. Shown as what the capture is replacing, and used to tell "a new level arrived" from
 * "nothing happened".
 */
previous_enter?: number, 
/**
 * The **exit** level the timer was reporting when the capture started, if it was reporting one.
 */
previous_exit?: number, };
