// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /timers/{timer_id}/capture` (#355, #465) — have the timer **measure** one
 * node's thresholds instead of being told them.
 *
 * The answer to the gap #411 names: a fresh RD with no saved profile and a badly-tuned timer has
 * no starting point, and GridFPV deliberately ships no fabricated default because the right level
 * depends on craft, VTX power, antenna and gate geometry — none of which GridFPV knows. A capture
 * measures the RD's actual craft on their actual gate, which is the only honest way to bootstrap.
 *
 * **One arm, one pass, both thresholds** (#465). The RD used to press Capture twice per node and
 * fly two passes; a single press now runs both of RotorHazard's captures over the one pass — see
 * [`CAPTURE_EXIT_DELAY_MS`] for why they are sequenced rather than fired together, and for the
 * reason GridFPV does not derive the pair from the signal curve itself.
 *
 * There is deliberately **no threshold field**. It was the RD's choice and is not one any more;
 * keeping it would let a caller ask for half a capture, which is the thing this issue removed.
 */
export type CaptureRequest = { 
/**
 * The node to capture on, `0`-based — RotorHazard's `seat_index`, and the same index
 * [`NodeSignal::node`] and [`CalibrationRequest::node`] carry.
 */
node: number, };
