// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a node's two detection thresholds a **capture** is for (#355).
 *
 * A capture is per threshold because RotorHazard's are: `cap_enter_at_btn` and `cap_exit_at_btn`
 * are separate handlers arming separate sampling windows, and the enter branch applies a peak
 * margin the exit branch does not.
 */
export type CaptureThreshold = "enter" | "exit";
