// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the standard FPV channel catalog: a band, its channel label, and the raw centre
 * frequency in **MHz** (race redesign Slice 4a).
 *
 * The `band`/`channel` pair is the human-readable handle a console offers; `mhz` is the
 * authoritative value every timer and the engine actually tune/allocate on. Exported via
 * `ts_rs::TS` so the frontend can render the catalog directly.
 */
export type ChannelCatalogEntry = { 
/**
 * The band name (e.g. `"Raceband"`, `"Fatshark"`, `"Boscam A"`, `"Boscam B"`, `"Boscam E"`).
 */
band: string, 
/**
 * The channel label within the band (e.g. `"R1"`, `"F4"`, `"A8"`).
 */
channel: string, 
/**
 * The channel's centre frequency in megahertz (the raw value the engine/timer use).
 */
mhz: number, };
