// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /timers/{timer_id}/channel` (#413) — set one node's channel while tuning it.
 *
 * Tuning a gate is meaningless until the node is listening on the channel it will race, so the
 * Tune page makes the frequency it already *shows* settable. The `band`/`channel` pair is the
 * **catalog entry the RD picked**; it is validated against the shared catalog server-side (D27
 * owns the vocabulary) and carried onto RotorHazard's `set_frequency`, whose handler stores both
 * on the active profile — without them RotorHazard's own UI shows a bare number with no `R7`-style
 * label, and the RD validates this work by refreshing that page.
 */
export type ChannelRequest = { 
/**
 * The node to tune, `0`-based — RotorHazard's `seat_index`, and the same index
 * [`NodeSignal::node`] and [`CalibrationRequest::node`] carry.
 */
node: number, 
/**
 * The channel's centre frequency in raw MHz. Must be within the timer's
 * [`channel_capability`](Timer::channel_capability) and inside
 * [`CHANNEL_MHZ_MIN`]..=[`CHANNEL_MHZ_MAX`].
 */
mhz: number, 
/**
 * The catalog band the RD picked (`"Raceband"`), if any. Honoured only when the
 * `(band, channel, mhz)` triple is a real catalog entry; otherwise the label is resolved from
 * the catalog instead.
 */
band?: string, 
/**
 * The catalog channel label the RD picked (`"R7"`), if any. See [`band`](ChannelRequest::band).
 */
channel?: string, };
