// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What channels a timer can be tuned to (race redesign Slice 4a) — its *channel capability*,
 * declared generically (NOT RotorHazard-specific).
 *
 * A timer is one of two kinds:
 *
 * - [`Fixed`](ChannelCapability::Fixed) — the timer supports only a **specific allowed set** of
 *   built-in catalog frequencies (raw MHz). A limited timer (e.g. a fixed-band module) exposes
 *   only what it physically supports; a console must pick a heat's channels from this set.
 * - [`Flexible`](ChannelCapability::Flexible) — the timer accepts **any** frequency: the whole
 *   standard catalog *plus* arbitrary custom raw MHz (e.g. RotorHazard, whose nodes tune freely).
 *
 * Externally tagged so it maps to a TS discriminated union. It is **additive** on the wire and on
 * disk: a timer persisted before the channel model existed deserializes with the
 * [`Default`] capability ([`Flexible`](ChannelCapability::Flexible)), so old `timers.json` files
 * round-trip and stay valid.
 */
export type ChannelCapability = { "Fixed": { 
/**
 * The allowed built-in channel centre frequencies, in raw MHz, in preference order.
 */
channels: Array<number>, } } | "Flexible";
