// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelLayout } from "./ChannelLayout";
import type { LayoutOverlap } from "./LayoutOverlap";

/**
 * An event's layouts **and what is worth telling the RD about them** (#117 S2) — the body of
 * `GET /events/{id}/layouts`, and of every layout write.
 *
 * One view type for the read and all three writes so the console never has to re-derive the
 * warnings from a write's response: a write returns the resulting whole picture, exactly like the
 * read. Errors do not appear here — they are refusals, returned as a typed 400 with a sentence the
 * RD can act on. This carries only the things that are *allowed* and still worth flagging.
 */
export type ChannelLayouts = { 
/**
 * The event's layouts, in definition order.
 */
layouts: Array<ChannelLayout>, 
/**
 * Cross-layout channel reuse ([`LayoutOverlap`]) — **advisory**. Empty when no two layouts share
 * a channel, and empty is *not* a goal: a bracket run off one layout trivially has none.
 */
overlaps?: Array<LayoutOverlap>, };
