// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from "./TimerId";

/**
 * The answer to `POST /timers/{timer_id}/channel` (#413): **what was dispatched** — never a
 * readback, exactly like [`CalibrationDispatch`].
 *
 * RotorHazard's `on_set_frequency` does not answer the caller; it re-broadcasts its frequency data
 * and, more usefully, every heartbeat carries each node's current frequency. So the console
 * confirms a channel change the same way it confirms a threshold: by seeing
 * [`NodeSignal::frequency_mhz`] come back holding what it sent on a later
 * `GET /timers/{id}/signal`.
 *
 * `previous_mhz` is what the node was **last told to tune to by GridFPV**, when GridFPV had told
 * it anything — the console pairs it with its own live reading to say plainly that the node's
 * enter/exit thresholds were tuned on a different channel.
 */
export type ChannelDispatch = { 
/**
 * The timer the write was dispatched to.
 */
timer: TimerId, 
/**
 * The node it addresses, `0`-based.
 */
node: number, 
/**
 * The centre frequency that was queued, in raw MHz.
 */
mhz: number, 
/**
 * The resolved catalog band, or absent for a custom raw MHz the catalog does not know.
 */
band?: string, 
/**
 * The resolved catalog channel label, or absent for a custom raw MHz.
 */
channel?: string, 
/**
 * The channel GridFPV had this node on before this write, if it had set one. Absent the first
 * time a node's channel is set from GridFPV.
 */
previous_mhz?: number, 
/**
 * Whether GridFPV holds **enter/exit thresholds** for this node ([`Timer::calibration`]) that
 * were set while it was on a *different* channel — i.e. whether the levels the Tune page is
 * showing were tuned for the frequency this write just moved away from.
 *
 * Reported, never acted on: the thresholds are deliberately left exactly where they are (D27 —
 * GridFPV changed one thing, so one thing changed). Recalling per-channel levels is #411.
 */
thresholds_tuned_on_another_channel: boolean, };
