// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Change } from "./Change";
import type { Cursor } from "./Cursor";
import type { ProjectionKind } from "./ProjectionKind";

/**
 * A change envelope (protocol.html §3): one ordered, sequenced update to a single
 * projection.
 *
 * Each envelope carries its monotonic `sequence` [`Cursor`], names the `projection` it
 * touches (as a [`ProjectionKind`] — for a [`Change::FreshValue`] the body also
 * carries the kind, but naming it here keeps deltas and fresh values uniform), and a
 * `change` that is a delta or a fresh value. The client applies envelopes in strictly
 * increasing `sequence` order; re-delivering one already applied is a no-op keyed by
 * sequence (§3 "idempotent application", "at-least-once, deduplicated").
 */
export type ChangeEnvelope = { 
/**
 * This envelope's position in the per-stream sequence.
 */
sequence: Cursor, 
/**
 * Which projection this change advances.
 */
projection: ProjectionKind, 
/**
 * The delta or fresh value to apply.
 */
change: Change, };
