// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectionBody } from "./ProjectionBody";

/**
 * How an envelope conveys a projection change (protocol.html §3, §9.2): a **delta**
 * for append-heavy projections (lap lists, live state) or a **fresh value** for cheap
 * or re-folded ones (a heat result, a ranking after a marshaling correction).
 *
 * Externally tagged, mapping to a TS discriminated union.
 *
 * > **Deferred (#43):** the exact per-projection delta *encodings* are a placeholder.
 * > [`Change::Delta`] carries a `serde_json::Value` rather than a typed delta for each
 * > [`ProjectionKind`]; the precise delta shapes (a single appended lap, a heat-state
 * > transition) are pinned when the change stream lands. The *structure* — the
 * > per-projection delta-vs-fresh-value distinction protocol.html §9.2 fixes — is
 * > what matters now and is captured here. A fresh value, by contrast, is already a
 * > fully-typed [`ProjectionBody`].
 */
export type Change = { "Delta": unknown } | { "FreshValue": ProjectionBody };
