// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerId } from "./LayerId";
import type { LayerNode } from "./LayerNode";

/**
 * One event **channel layer** (#117 S2): a complete tuning of the event's timer — one channel per
 * enabled node.
 *
 * ```text
 * Layer A:  Node 1→R1  Node 2→R2  Node 3→R3  Node 4→R4
 * Layer B:  Node 1→F1  Node 2→F2  Node 3→F4  Node 4→F8
 * ```
 *
 * # Why a layer, and why the system does not choose one for you
 *
 * The RD picks the strategy, per format, and both strategies fall out of this one mechanism with
 * no special case:
 *
 * - a **bracket** is *one layer for the whole tournament* — n channels for n pilots per heat, and
 *   they never move;
 * - a **GQ-style qualifier** defines *many* layers so each pilot can stay on their own channel.
 *
 * So nothing here encodes a policy that forces either. What the model does enforce is that a layer
 * is a **complete, conflict-free tuning**: every enabled node has exactly one channel, and no two
 * nodes share one (a node cannot share a frequency with its neighbour). Reusing a channel *between*
 * layers is a [`LayerOverlap`] **warning**, never a refusal — it only matters for the
 * keep-pilots-on-one-channel strategy, and an RD running a bracket off a single layer does not
 * care.
 *
 * Carried in [`EventMeta::channel_layers`]. **Not yet wired into heat filling or
 * `assign_frequencies`** — which heat flies which layer is S3.
 */
export type ChannelLayer = { 
/**
 * The stable, **auto-generated** handle (a slug of [`name`](Self::name) + a short random
 * suffix). Never user-entered; the name is display-only but is what a person reads.
 */
id: LayerId, 
/**
 * The RD-typed display name (`"Bracket A"`, `"Qual pack 2"`). Non-empty after trimming, and
 * unique within the event — two layers called "Bracket A" is a mis-click, not a choice.
 */
name: string, 
/**
 * The node → channel mapping, **ascending by node**, one entry per enabled node of the event's
 * timer. Complete and duplicate-free (see the type doc).
 */
nodes: Array<LayerNode>, };
