// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`RoundDef`] assigns **video channels** to its heats (race redesign Slice 7a).
 *
 * Two models, chosen by the round's competition shape:
 *
 * - [`Static`](Self::Static) — **time-trial / qualifying** (GQ-style): every member has a *fixed*
 *   channel assigned at membership ([`MemberSlot::channel`], drawn from the event's **primary
 *   timer**'s `available_channels`). Heats are **channel-balanced** — one pilot per channel per
 *   heat, ≤ `node_count` pilots per heat — so every member flies across the format's rounds.
 * - [`PerHeat`](Self::PerHeat) — **brackets**: the bracket decides matchups, so channels are
 *   assigned **per heat** from the timer's pool (the existing first-fit allocation), each heat ≤
 *   `node_count` pilots.
 *
 * Defaulted by format on round-create (`timed_qual` / `round_robin` → [`Static`](Self::Static);
 * the elimination / multi-main formats → [`PerHeat`](Self::PerHeat)); the default `Default` impl is
 * [`PerHeat`](Self::PerHeat) so a round persisted before this field existed reads back with the
 * prior per-heat behaviour. Derives serde + `ts_rs::TS`.
 */
export type ChannelMode = "Static" | "PerHeat";
