// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";

/**
 * One pilot's **contribution to a class's standings** (race redesign Slice 5/6a) — the
 * per-pilot / per-class row aggregated across that class's rounds (the season-join shape).
 *
 * This is the row the Results UI renders per competitor: their final standing position, the
 * total points they accrued across the class's rounds, and the headline lap metrics (best lap,
 * total counted laps). It is a pure aggregate of the class's scored rounds, so it replays
 * identically off the same log + meta.
 */
export type ClassStanding = { 
/**
 * The competitor this standing is for (the pilot's source-local handle).
 */
competitor: CompetitorRef, 
/**
 * 1-based overall standing position; tied competitors share a position with the same
 * dense, tie-aware "1, 2, 2, 4" convention as [`RankEntry`].
 */
position: number, 
/**
 * Total **points** across the class's rounds — the sum of each round's per-pilot points,
 * where a round awards `field_size - round_position + 1` points (a win in an N-pilot round
 * is worth N, last is worth 1). The headline metric the standings rank on.
 */
points: number, 
/**
 * The competitor's **best lap** across every heat of the class's rounds, in microseconds,
 * or `None` when they completed no lap. The qualifying-style tie-break / display metric.
 */
best_lap_micros: number | null, 
/**
 * The **total counted laps** the competitor completed across the class's rounds (each
 * round's laps under that round's win condition). A display / secondary metric.
 */
total_laps: number, 
/**
 * How many of the class's rounds this competitor appeared in (was ranked in) — context for
 * the points total (a pilot who skipped a round has fewer rounds to accrue from).
 */
rounds_entered: number, };
