// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a **class** within an event (protocol.html §4 "Class scope") — one
 * class's phases, schedule, and standings, which may run in parallel with others.
 */
export type ClassId = string;
