// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { ClassSource } from "./ClassSource";

/**
 * One class in the application-level directory (issue #84).
 *
 * The wire shape `GET /classes` returns and the on-disk shape `classes.json` persists: a stable
 * [`ClassId`] (auto-generated, never user-entered), a required `name`, a [`source`](Class::source)
 * provenance, and a little optional metadata. The optional fields are omitted from the wire when
 * unset (`skip_serializing_if`). Derives serde (its JSON *is* both the wire and the persisted form)
 * and `ts_rs::TS` so the frontend reads a generated `Class` type.
 */
export type Class = { 
/**
 * The stable handle a per-event selection references and the API addresses
 * (`PUT /classes/{id}`). The same [`ClassId`] the scope/log layer uses — directory and scope
 * never disagree on what a class id is.
 */
id: ClassId, 
/**
 * The class's **name** — the required display label (e.g. `"Open"`, `"Spec 5\""`). The
 * directory's one mandatory field; everything else is optional metadata.
 */
name: string, 
/**
 * Where this class came from (see [`ClassSource`]). Defaults to
 * [`Custom`](ClassSource::Custom).
 */
source: ClassSource, 
/**
 * An optional **reference** id/handle into the source system (e.g. a MultiGP class id), if
 * recorded. Free-form. Omitted from the wire when unset.
 */
reference?: string, 
/**
 * An optional free-text description / notes for the class. Omitted from the wire when unset.
 */
description?: string, };
