// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a **class** within an event (protocol.html §4 "Class scope") — one
 * class's phases, schedule, and standings, which may run in parallel with others.
 *
 * This is the **canonical** class handle the whole stack shares: the event model tags
 * a scheduled heat with the class it belongs to ([`Event::HeatScheduled`]) and the
 * wire/scope layer addresses a class by the same type
 * ([`ClassId`](../../server/scope/struct.ClassId.html), re-exported from here), so the
 * log and the protocol never disagree on what a class id is. A transparent string
 * newtype like the other event-model ids.
 */
export type ClassId = string;
