// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`Class`] came from (issue #84).
 *
 * A small closed enum the directory records so the RD can tell a canonical built-in class (e.g. a
 * MultiGP spec class) from one they typed in themselves. Externally tagged (the default serde enum
 * representation) so it maps to a TS string union (`"MultiGP" | "Five33" | … | "Custom" |
 * "Other"`), exactly like [`VtxType`](crate::pilots::VtxType). The org variants name the standard
 * FPV racing leagues / spec bodies the built-in classes carry as their provenance (shown as a
 * badge). Defaults to [`Custom`](ClassSource::Custom) — a class the RD created by hand; users only
 * ever create `Custom` classes. [`Other`](ClassSource::Other) is the catch-all for any provenance
 * not enumerated.
 */
export type ClassSource = "MultiGP" | "Five33" | "FreedomSpec" | "StreetLeague" | "UDL" | "Custom" | "Other";
