// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { ClassStanding } from "./ClassStanding";

/**
 * A class's **standings** (race redesign Slice 5/6a): the ordered per-pilot rows aggregated
 * across the class's rounds, plus the class id they are for.
 *
 * The season-join projection the Results screen reads: [`class_standings`] folds the log + meta
 * into one [`ClassStanding`] per competitor that raced the class, best standing first. Pure and
 * deterministic — the same log + meta always yields the same ordered standings.
 */
export type ClassStandings = { 
/**
 * The class these standings are for.
 */
class: ClassId, 
/**
 * The per-pilot standings, best first (ties adjacent, sharing a position).
 */
standings: Array<ClassStanding>, };
