// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`Class`] came from (issue #84).
 *
 * A small closed enum the directory records so the RD can tell an imported class (e.g. a MultiGP
 * chapter class) from one they typed in themselves. Externally tagged (the default serde enum
 * representation) so it maps to a TS string union (`"MultiGP" | "Custom" | "Other"`), exactly like
 * [`VtxType`](crate::pilots::VtxType). Defaults to [`Custom`](ClassSource::Custom) — a class the RD
 * created by hand; [`Other`](ClassSource::Other) is the catch-all for any provenance not
 * enumerated.
 */
export type ClassSource = "MultiGP" | "Custom" | "Other";
