// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { PilotId } from "./PilotId";

/**
 * One class's **membership** within an event (race redesign Slice 1a): the roster pilots that
 * race a single [`ClassId`].
 *
 * Carried in [`EventMeta::classes_membership`] as a list, one entry per class with any members.
 * Derives serde (its JSON *is* the wire form) and `ts_rs::TS` so the frontend reads a generated
 * `ClassMembership` type for the per-class roster picker (the UI lands in Slice 1b).
 */
export type ClassMembership = { 
/**
 * The class these pilots race — one of the event's selected [`classes`](EventMeta::classes).
 */
class: ClassId, 
/**
 * The roster pilots racing this class, in selection order. Each is a directory pilot that is
 * also on the event's [`roster`](EventMeta::roster).
 */
pilots: Array<PilotId>, };
