// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { MemberSlot } from "./MemberSlot";

/**
 * One class's **membership** within an event (race redesign Slice 1a): the roster pilots that
 * race a single [`ClassId`].
 *
 * Carried in [`EventMeta::classes_membership`] as a list, one entry per class with any members.
 * Derives serde (its JSON *is* the wire form) and `ts_rs::TS` so the frontend reads a generated
 * `ClassMembership` type for the per-class roster picker (the UI lands in Slice 1b).
 */
export type ClassMembership = { 
/**
 * The class these pilots race — one of the event's selected [`classes`](EventMeta::classes).
 */
class: ClassId, 
/**
 * The roster pilots racing this class, in selection order, **each with an optional assigned
 * channel** (race redesign Slice 7a). Each entry is a directory pilot that is also on the
 * event's [`roster`](EventMeta::roster); its [`channel`](MemberSlot::channel) is the raw-MHz
 * frequency the pilot flies in a *static*-channel-mode round (a fixed, per-membership channel,
 * GQ-style).
 *
 * **Legacy-compatible:** older events persisted this as a bare `Vec<PilotId>`; the
 * [`MemberSlot`] (de)serialises through a serde shim ([`member_slots`]) that accepts either
 * shape — a plain pilot-id string (legacy) reads back as a [`MemberSlot`] with no channel — so
 * pre-Slice-7a meta still loads and restart round-trips.
 */
pilots: Array<MemberSlot>, };
