// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolError } from "./ProtocolError";

/**
 * The acknowledgement of a [`Command`] (protocol.html §5): commands up,
 * acknowledgements down.
 *
 * `ok` is the success flag; on failure `error` carries the single shared
 * [`ProtocolError`](crate::error::ProtocolError) (§9.8) — an illegal transition for
 * the heat's state, an unauthorized caller, an unknown heat. On success `error` is
 * `None`. (The resulting projection state flows back separately as
 * [`ChangeEnvelope`](crate::stream::ChangeEnvelope)s on the read stream, not in the
 * ack.)
 */
export type CommandAck = { 
/**
 * Whether the command was accepted and applied.
 */
ok: boolean, 
/**
 * The failure detail when `ok` is `false`; `None` on success.
 */
error?: ProtocolError, };
