// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { ClassId } from "./ClassId";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { LogRef } from "./LogRef";
import type { Penalty } from "./Penalty";
import type { PilotId } from "./PilotId";
import type { RoundId } from "./RoundId";
import type { SourceTime } from "./SourceTime";

/**
 * A privileged RD control command (protocol.html §5). Externally tagged like the
 * event model, so it maps to a TS discriminated union.
 *
 * The variants fall into four groups:
 *
 * - **Heat-loop transitions** — [`Stage`](Command::Stage), [`Arm`](Command::Arm),
 *   [`Start`](Command::Start), [`Finish`](Command::Finish),
 *   [`Finalize`](Command::Finalize), [`Advance`](Command::Advance), and the off-ramps
 *   [`Revert`](Command::Revert), [`Abort`](Command::Abort),
 *   [`Restart`](Command::Restart), [`Discard`](Command::Discard). Each requests the
 *   matching [`HeatTransition`](gridfpv_events::HeatTransition); the engine validates
 *   it against the heat's current state (race-engine.html §2).
 * - **Scheduling** — [`ScheduleHeat`](Command::ScheduleHeat) creates a heat with its
 *   lineup ([`Event::HeatScheduled`](gridfpv_events::Event::HeatScheduled)).
 * - **Registration** — [`Register`](Command::Register) binds a source-local
 *   competitor to a pilot (the binding the adapter never does itself; Architecture §9).
 * - **Marshaling adjudications** — the five corrections
 *   ([`VoidDetection`](Command::VoidDetection), [`InsertLap`](Command::InsertLap),
 *   [`AdjustLap`](Command::AdjustLap), [`VoidHeat`](Command::VoidHeat),
 *   [`ApplyPenalty`](Command::ApplyPenalty)), each requesting the corresponding
 *   marshaling event the projection folds in (never a mutation; architecture.html §3).
 */
export type Command = { "Stage": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Arm": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Start": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Finish": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Finalize": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Advance": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Revert": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Abort": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Restart": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "Discard": { 
/**
 * The heat to transition.
 */
heat: HeatId, } } | { "ScheduleHeat": { 
/**
 * The id the new heat will carry.
 */
heat: HeatId, 
/**
 * The competitors in the heat, in lineup order.
 */
lineup: Array<CompetitorRef>, 
/**
 * The class this heat runs in, when the scheduler assigns one.
 */
class?: ClassId, 
/**
 * The round within the class's schedule, when the scheduler assigns one.
 */
round?: RoundId, 
/**
 * Per-pilot frequency assignment in raw MHz (e.g. `5800`); empty when none is
 * assigned (a sim race, or the free-text path).
 */
frequencies?: Array<[CompetitorRef, number]>, } } | { "FillRound": { 
/**
 * The round to fill — one of the event's [`rounds`](crate::events::EventMeta::rounds).
 */
round: RoundId, } } | { "Register": { 
/**
 * The timing source the competitor belongs to.
 */
adapter: AdapterId, 
/**
 * The source-local competitor handle being bound.
 */
competitor: CompetitorRef, 
/**
 * The event-scoped pilot the competitor is bound to.
 */
pilot: PilotId, } } | { "VoidDetection": { 
/**
 * The log offset of the pass (or ruling) to void.
 */
target: LogRef, } } | { "InsertLap": { 
/**
 * The timing source to attribute the inserted pass to.
 */
adapter: AdapterId, 
/**
 * The competitor the inserted lap belongs to.
 */
competitor: CompetitorRef, 
/**
 * When the inserted crossing happened, on the source clock.
 */
at: SourceTime, } } | { "AdjustLap": { 
/**
 * The log offset of the pass to re-time.
 */
target: LogRef, 
/**
 * The corrected crossing time, on the source clock.
 */
at: SourceTime, } } | { "VoidHeat": { 
/**
 * The heat to void.
 */
heat: HeatId, } } | { "ApplyPenalty": { 
/**
 * The heat the penalty applies in.
 */
heat: HeatId, 
/**
 * The competitor penalized.
 */
competitor: CompetitorRef, 
/**
 * The penalty applied.
 */
penalty: Penalty, } };
