// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvanceOutcome } from "./AdvanceOutcome";
import type { FillRoundOutcome } from "./FillRoundOutcome";

/**
 * What a command **did**, for the commands whose useful result is the effect rather than the
 * acceptance (#395).
 *
 * Externally tagged and keyed by command, so each command's outcome is its own shape and a new
 * one is an additive variant. Rides along in [`CommandAck::outcome`], which is optional — a
 * command with nothing interesting to report (a transition either happened or was rejected)
 * omits it entirely and its ack is byte-identical to before.
 */
export type CommandOutcome = { "FillRound": FillRoundOutcome } | { "Advance": AdvanceOutcome };
