// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandOutcome } from "./CommandOutcome";
import type { ProtocolError } from "./ProtocolError";

/**
 * The acknowledgement of a [`Command`] (protocol.html §5): commands up,
 * acknowledgements down.
 *
 * `ok` is the success flag; on failure `error` carries the single shared
 * [`ProtocolError`](crate::error::ProtocolError) (§9.8) — an illegal transition for
 * the heat's state, an unauthorized caller, an unknown heat. On success `error` is
 * `None`. (The resulting projection state flows back separately as
 * [`ChangeEnvelope`](crate::stream::ChangeEnvelope)s on the read stream, not in the
 * ack.)
 *
 * `ok` answers *"was the command accepted?"* — which for some commands is not the question the
 * caller is actually asking. `FillRound`'s "did nothing" is a routine, expected result, not an
 * error, so it acks ok; a caller then has no way to tell it from a fill that scheduled a heat
 * (#395). [`outcome`](Self::outcome) carries **what the command did** for those commands, and
 * is absent for the ones where acceptance *is* the whole answer — so it is purely additive:
 * every existing client keeps parsing every ack unchanged.
 */
export type CommandAck = { 
/**
 * Whether the command was accepted and applied.
 */
ok: boolean, 
/**
 * The failure detail when `ok` is `false`; `None` on success.
 */
error?: ProtocolError, 
/**
 * **What the command did**, for the commands whose effect is the useful answer — currently
 * [`FillRound`](Command::FillRound). `None` for every other command (and for a failure,
 * where `error` is the answer).
 */
outcome?: CommandOutcome, };
