// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source-local competitor handle: a node seat, a sim player name, a transponder
 * id. Bound to a GridFPV pilot later by a *registration* action — never by the
 * adapter (see Architecture §9). The adapter only reports the refs it sees.
 */
export type CompetitorRef = string;
