// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorKey } from "./CompetitorKey";
import type { Lap } from "./Lap";

/**
 * Every lap a single competitor completed, in order.
 */
export type CompetitorLaps = { 
/**
 * Which source-local competitor these laps belong to.
 */
competitor: CompetitorKey, 
/**
 * Completed laps, ordered by lap number (1-based, ascending).
 */
laps: Array<Lap>, };
