// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";

/**
 * Identifies a competitor *within a single timing source*.
 *
 * A source-local [`CompetitorRef`] is only meaningful relative to the adapter
 * that emitted it (node 2 on RotorHazard is unrelated to node 2 on a second
 * timer), so laps are grouped on the `(AdapterId, CompetitorRef)` pair. Binding
 * these per-source competitors to a single GridFPV pilot is a later registration
 * concern (Architecture §9) and deliberately out of scope here.
 */
export type CompetitorKey = { 
/**
 * The timing source the competitor belongs to.
 */
adapter: AdapterId, 
/**
 * The source-local competitor handle.
 */
competitor: CompetitorRef, };
