// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeatId } from "./HeatId";
import type { HeatResult } from "./HeatResult";

/**
 * A scored heat fed back into the generator: the heat's id and its [`HeatResult`].
 *
 * This is the generator's *only* input about what happened — it consumes finished,
 * scored heats (produced by [`crate::scoring::score`]) and never raw passes. The
 * `heat` id ties the result back to the [`HeatPlan`] that produced it, so a
 * generator that emitted several heats can tell which result is which.
 */
export type CompletedHeat = { 
/**
 * Which planned heat this result is for.
 */
heat: HeatId, 
/**
 * The scored result of that heat.
 */
result: HeatResult, };
