// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorKey } from "./CompetitorKey";
import type { SourceTime } from "./SourceTime";

/**
 * One competitor's reconstructed RSSI trace within a heat: the concatenated samples plus the
 * enter/exit thresholds the timer detected against (marshaling.html §3.2).
 *
 * The `samples` are the per-tick RSSI values in capture order; `from`/`period_micros` carry the
 * time base of the **first** chunk so a UI can place each sample on the source clock (chunks are
 * captured back-to-back at a fixed cadence, so the first chunk's base plus the running index
 * reconstructs every sample's time — see [`signal_trace`] for the contiguity it assumes).
 * `enter`/`exit` are the last thresholds seen for this competitor, `None` until one is captured.
 */
export type CompetitorTrace = { 
/**
 * Which source-local competitor this trace belongs to.
 */
competitor: CompetitorKey, 
/**
 * The source-clock timestamp of the first captured sample, if any.
 */
from?: SourceTime, 
/**
 * Microseconds between consecutive samples (the capture cadence of the first chunk).
 */
period_micros: number, 
/**
 * The concatenated per-tick RSSI samples (filtered ADC counts), oldest first.
 */
samples: Array<number>, 
/**
 * The enter detection threshold, where captured.
 */
enter?: number, 
/**
 * The exit detection threshold, where captured.
 */
exit?: number, };
