// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorKey } from "./CompetitorKey";
import type { Lap } from "./Lap";
import type { VoidedPass } from "./VoidedPass";

/**
 * Every lap a single competitor completed, in order.
 */
export type CompetitorLaps = { 
/**
 * Which source-local competitor these laps belong to.
 */
competitor: CompetitorKey, 
/**
 * Completed laps, ordered by lap number (1-based, ascending).
 */
laps: Array<Lap>, 
/**
 * Gate passes the RD **voided** (`DetectionVoided`, not undone), chronologically. The
 * record of removals travels WITH the lap list so every consumer shares it: the console
 * renders them struck-through in place, and threshold re-detection must NOT re-propose a
 * crossing the RD explicitly removed — the RSSI trace still shows the crossing, so without
 * this the tuner kept offering a voided lap back as "a lap to add". Additive: absent on
 * the wire when empty, so older payloads round-trip.
 */
voided?: Array<VoidedPass>, };
