// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The protocol **contract version** — axis 1 of the three version axes
 * (protocol.html §7): the wire shapes owned by this crate, kept distinct from the
 * log/schema version and the projection version.
 *
 * A single monotonic integer. A breaking change to any wire type bumps it; additive
 * changes (new projections, new fields an older client ignores) do not. The version
 * is negotiated at connect time ([`Hello`] / [`ServerHello`]) and is independent of
 * the transport (LAN or Cloud) — see [`CONTRACT_VERSION`] for the version this build
 * speaks.
 */
export type ContractVersion = number;
