// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCapability } from "./ChannelCapability";
import type { TimerKind } from "./TimerKind";

/**
 * The body of `POST /timers` — the config a caller supplies to create a timer (issue #73).
 *
 * A display `name` plus the [`TimerKind`]; the **id is auto-generated** server-side (a slug of
 * the name + a short random suffix), never user-entered, mirroring `POST /events`.
 */
export type CreateTimerRequest = { 
/**
 * The display name for the new timer.
 */
name: string, 
/**
 * The kind + config of the new timer.
 */
kind: TimerKind, 
/**
 * The new timer's **channel capability** (race redesign Slice 4a). Optional and additive —
 * omit it for the permissive [`Flexible`](ChannelCapability::Flexible) default.
 */
channel_capability?: ChannelCapability, 
/**
 * The new timer's **node/slot count** (race redesign Slice 4a) — the heat-size cap. Optional;
 * defaults to [`DEFAULT_NODE_COUNT`].
 */
node_count?: number, 
/**
 * The new timer's **available channels** in raw MHz (race redesign Slice 4a). Optional;
 * defaults to empty (none configured).
 */
available_channels?: Array<number>, };
