// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassSource } from "./ClassSource";

/**
 * The body of `POST /classes` — the fields a caller supplies to create a class (issue #84).
 *
 * The `name` is required; everything else is optional. The **id is auto-generated** server-side (a
 * slug of the name + a short random suffix), never user-entered, mirroring `POST /pilots`.
 */
export type CreateClassRequest = { 
/**
 * The required name for the new class.
 */
name: string, 
/**
 * The class's provenance, stored on [`Class::source`]. Defaults to
 * [`Custom`](ClassSource::Custom).
 */
source: ClassSource, 
/**
 * Optional reference id, stored on [`Class::reference`].
 */
reference?: string, 
/**
 * Optional description, stored on [`Class::description`].
 */
description?: string, };
