// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VtxType } from "./VtxType";

/**
 * The body of `POST /pilots` — the fields a caller supplies to create a pilot (issue #74).
 *
 * The `callsign` is required; everything else is optional. The **id is auto-generated**
 * server-side (a slug of the callsign + a short random suffix), never user-entered, mirroring
 * `POST /timers` / `POST /events`.
 */
export type CreatePilotRequest = { 
/**
 * The required callsign for the new pilot.
 */
callsign: string, 
/**
 * Optional real name, stored on [`Pilot::name`].
 */
name?: string, 
/**
 * Optional pronunciation hint, stored on [`Pilot::phonetic`].
 */
phonetic?: string, 
/**
 * Optional team / club, stored on [`Pilot::team`].
 */
team?: string, 
/**
 * Optional hex color `#RRGGBB`, stored on [`Pilot::color`] (validated).
 */
color?: string, 
/**
 * Optional ISO 3166-1 alpha-2 country code, stored on [`Pilot::country`] (validated).
 */
country?: string, 
/**
 * The pilot's video-transmitter system(s), stored (deduped, stable order) on
 * [`Pilot::vtx_types`]. Defaults empty (unspecified).
 */
vtx_types: Array<VtxType>, 
/**
 * Optional MultiGP id, stored on [`Pilot::multigp_id`].
 */
multigp_id?: string, 
/**
 * Optional Velocidrone id, stored on [`Pilot::velocidrone_id`].
 */
velocidrone_id?: string, };
