// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /events` — the only thing a caller supplies when creating an event.
 *
 * Just a display `name`; the **id is always auto-generated** (a slug of the name plus a
 * short random suffix), never user-entered, per the maintainer's rule. Keeping the id off
 * the wire means two events can share a name without colliding and a client cannot pick its
 * own id.
 */
export type CreateEventRequest = { 
/**
 * The display name for the new event.
 */
name: string, 
/**
 * Optional **display date** stored on the new event's [`EventMeta::date`] (see there).
 * Omitted from the wire when unset — a name-only create stays a one-field body.
 */
date?: string, 
/**
 * Optional venue / location, stored on [`EventMeta::location`].
 */
location?: string, 
/**
 * Optional free-text description, stored on [`EventMeta::description`].
 */
description?: string, 
/**
 * Optional organizer name, stored on [`EventMeta::organizer`].
 */
organizer?: string, };
