// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `POST /events` — the only thing a caller supplies when creating an event.
 *
 * Just a display `name`; the **id is always auto-generated** (a slug of the name plus a
 * short random suffix), never user-entered, per the maintainer's rule. Keeping the id off
 * the wire means two events can share a name without colliding and a client can't squat a
 * reserved id (e.g. `practice`).
 */
export type CreateEventRequest = { 
/**
 * The display name for the new event.
 */
name: string, };
