// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerKind } from "./TimerKind";

/**
 * The body of `POST /timers` — the config a caller supplies to create a timer (issue #73).
 *
 * A display `name` plus the [`TimerKind`]; the **id is auto-generated** server-side (a slug of
 * the name + a short random suffix), never user-entered, mirroring `POST /events`.
 */
export type CreateTimerRequest = { 
/**
 * The display name for the new timer.
 */
name: string, 
/**
 * The kind + config of the new timer.
 */
kind: TimerKind, };
