// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one gate crossing — the **disposition** the live crossing feed carries (#397).
 *
 * A timer emits crossings; GridFPV owns lap semantics, so a crossing is not the same thing as a
 * lap and the interesting ones are mostly *not* laps. There is no "holeshot" concept in the log —
 * the first crossing is an ordinary [`GateIndex::LAP`](gridfpv_events::GateIndex::LAP) pass, and
 * lap derivation is nothing but consecutive pairs of the corrected chain (`passes.windows(2)`).
 * So a disposition is a **position in the corrected pass chain**, or the removal record the fold
 * already keeps — never a new logged fact.
 *
 * The two removal-side variants map 1:1 onto the only two [`VoidReason`]s that exist.
 */
export type CrossingDisposition = "Holeshot" | "Counted" | "RejectedTooShort" | "VoidedByMarshal" | "RejectedAfterRaceEnd";
