// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The public **projection sequence number** (protocol.html §3, §9.5): a single
 * monotonic integer per stream, increasing by one per envelope.
 *
 * It is *not* the raw log offset — one log append can fan out into several projection
 * changes or none a client subscribes to. The protocol commits to this projection
 * sequence as its public ordering; the log offset stays a private Director/Cloud
 * detail. The snapshot hands the client a starting cursor (§2) and every envelope
 * advances it; on reconnect the client presents its last-applied cursor to resume
 * (§3).
 *
 * Transparent `u64` newtype; `#[ts(as = "f64")]` so it renders as a plain TS
 * `number`. Our cursors/sequences are bounded well below 2^53, so `number` is exact
 * and avoids the wire/type mismatch a `u64` → wide-integer TS mapping would introduce.
 */
export type Cursor = number;
