// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A machine-readable error category — the cases protocol.html §9.8 enumerates
 * ("auth failure, unknown scope, stale-cursor, version-mismatch"), plus a generic
 * fallback. Externally tagged like the event model so it maps to a TS string union.
 *
 * Adding a new variant is an additive change (§7): an older client that does not
 * understand a new code treats it as it would [`ErrorCode::Internal`] — an error it
 * surfaces but cannot specifically branch on.
 */
export type ErrorCode = "Unauthorized" | "UnknownScope" | "StaleCursor" | "VersionMismatch" | "BadRequest" | "Internal";
