// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { ClassId } from "./ClassId";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatTransition } from "./HeatTransition";
import type { LogRef } from "./LogRef";
import type { Pass } from "./Pass";
import type { Penalty } from "./Penalty";
import type { PilotId } from "./PilotId";
import type { RoundId } from "./RoundId";
import type { SessionId } from "./SessionId";
import type { SignalChunk } from "./SignalChunk";
import type { SignalThresholds } from "./SignalThresholds";
import type { SourceTime } from "./SourceTime";

/**
 * A canonical event in the append-only log.
 *
 * Adapters append **raw observations** (lifecycle, [`CompetitorSeen`](Event::CompetitorSeen),
 * [`Pass`]); the **race engine** appends heat-loop state transitions and the **RD** appends
 * marshaling adjudications (#28). Everything folds into the same projections — laps, results,
 * standings — and raw observations are never mutated; a correction is a new appended event.
 *
 * Externally tagged (the default serde representation): each variant serialises as
 * `{ "VariantName": { ..fields } }`, which maps cleanly to a discriminated union in
 * the generated TypeScript (#4).
 */
export type Event = { "AdapterConnected": { adapter: AdapterId, } } | { "AdapterDisconnected": { adapter: AdapterId, } } | { "SessionStarted": { adapter: AdapterId, session: SessionId, } } | { "SessionEnded": { adapter: AdapterId, session: SessionId, } } | { "CompetitorSeen": { adapter: AdapterId, competitor: CompetitorRef, } } | { "CompetitorRegistered": { adapter: AdapterId, competitor: CompetitorRef, pilot: PilotId, } } | { "Pass": Pass } | { "SignalChunk": SignalChunk } | { "SignalThresholds": SignalThresholds } | { "HeatScheduled": { heat: HeatId, lineup: Array<CompetitorRef>, 
/**
 * The class this heat runs in, where the scheduler tagged it.
 */
class?: ClassId, 
/**
 * The round within the class's schedule, where the scheduler tagged it.
 */
round?: RoundId, 
/**
 * Per-pilot frequency assignment in raw MHz (e.g. `5800`). Empty when none is
 * assigned (a simulator, or the free-text path that does not assign channels).
 */
frequencies?: Array<[CompetitorRef, number]>, } } | { "HeatStateChanged": { heat: HeatId, transition: HeatTransition, } } | { "CurrentHeatSelected": { heat: HeatId, } } | { "HeatStarting": { 
/**
 * The heat whose start procedure fired (it is in `Armed`).
 */
heat: HeatId, 
/**
 * The chosen randomized start delay, in **milliseconds**, from this event to the
 * `Armed → Running` transition. Written once by the runtime; deterministic on replay.
 */
delay_ms: number, } } | { "HeatFinalizing": { 
/**
 * The heat whose protest window is open (it is in `Unofficial`).
 */
heat: HeatId, 
/**
 * The **auto-official deadline**: the server wall-clock instant (microseconds since the
 * Unix epoch) at which the runtime appends the auto `Finalize`. The countdown the console
 * shows is `at − now`.
 */
at: number, } } | { "DetectionVoided": { target: LogRef, } } | { "LapInserted": { adapter: AdapterId, competitor: CompetitorRef, at: SourceTime, } } | { "LapAdjusted": { target: LogRef, at: SourceTime, } } | { "LapSplit": { 
/**
 * The log offset of the pass that *ends* the over-long lap being split.
 */
target: LogRef, 
/**
 * When the inserted mid-lap crossing happened, on the source clock — between the
 * `target` lap's start and `target` itself.
 */
at: SourceTime, } } | { "HeatVoided": { heat: HeatId, } } | { "PenaltyApplied": { heat: HeatId, competitor: CompetitorRef, penalty: Penalty, } } | { "RulingReversed": { 
/**
 * The log offset of the ruling (a [`PenaltyApplied`](Event::PenaltyApplied)) to reverse.
 */
target: LogRef, } };
