// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatTransition } from "./HeatTransition";
import type { LogRef } from "./LogRef";
import type { Pass } from "./Pass";
import type { Penalty } from "./Penalty";
import type { SessionId } from "./SessionId";
import type { SourceTime } from "./SourceTime";

/**
 * A canonical event in the append-only log.
 *
 * Adapters append **raw observations** (lifecycle, [`CompetitorSeen`](Event::CompetitorSeen),
 * [`Pass`]); the **race engine** appends heat-loop state transitions and the **RD** appends
 * marshaling adjudications (#28). Everything folds into the same projections — laps, results,
 * standings — and raw observations are never mutated; a correction is a new appended event.
 *
 * Externally tagged (the default serde representation): each variant serialises as
 * `{ "VariantName": { ..fields } }`, which maps cleanly to a discriminated union in
 * the generated TypeScript (#4).
 */
export type Event = { "AdapterConnected": { adapter: AdapterId, } } | { "AdapterDisconnected": { adapter: AdapterId, } } | { "SessionStarted": { adapter: AdapterId, session: SessionId, } } | { "SessionEnded": { adapter: AdapterId, session: SessionId, } } | { "CompetitorSeen": { adapter: AdapterId, competitor: CompetitorRef, } } | { "Pass": Pass } | { "HeatStateChanged": { heat: HeatId, transition: HeatTransition, } } | { "DetectionVoided": { target: LogRef, } } | { "LapInserted": { adapter: AdapterId, competitor: CompetitorRef, at: SourceTime, } } | { "LapAdjusted": { target: LogRef, at: SourceTime, } } | { "HeatVoided": { heat: HeatId, } } | { "PenaltyApplied": { heat: HeatId, competitor: CompetitorRef, penalty: Penalty, } };
