// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditKind } from "./AuditKind";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { LogRef } from "./LogRef";

/**
 * One row of the **event-wide** audit trail (`GET /events/{event_id}/audit`): a per-heat
 * marshaling [`AuditEntry`] plus the heat it belongs to.
 *
 * The per-heat [`AuditEntry`] deliberately carries no heat id — it is served from a heat-scoped
 * route where the heat is implicit. The event-wide read merges every heat's trail into one list,
 * so each entry must say *which* heat it rules on; the console's Audit page renders (and filters
 * by) that tag. The entry's own fields are flattened onto the row, so on the wire this is "an
 * `AuditEntry` plus `heat`" — additive, no re-modelling.
 */
export type EventAuditEntry = { 
/**
 * The heat this ruling belongs to — attributed by the same heat-window rules Marshaling's
 * per-heat audit uses ([`heat_window_offsets`]), so the two views can never disagree.
 */
heat: HeatId, 
/**
 * What kind of marshaling action this was — derived from the event type.
 */
kind: AuditKind, 
/**
 * When the log received this fact (microseconds since the Unix epoch), if recorded.
 * `None` when the append carried no arrival timestamp (e.g. a replay with none supplied).
 */
at: number | null, 
/**
 * The global append offset of this fact — a stable identity for the entry (and what a
 * later "reverse this" would target). Lets the UI key the list deterministically.
 */
at_ref: LogRef, 
/**
 * The competitor this action targeted, as a **structured ref** the client resolves to a
 * callsign and composes into the displayed line. `None` for actions that name no competitor.
 */
competitor: CompetitorRef | null, 
/**
 * A short human-readable description of the change — **without** the raw competitor ref (that
 * is carried structured in `competitor` so the client can show the resolved callsign instead).
 */
summary: string, };
