// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { CompletedHeat } from "./CompletedHeat";
import type { RankEntry } from "./RankEntry";

/**
 * The result of running a whole event: the qualifying ranking that seeded the bracket,
 * the bracket's final standings, and the single winner at the top of them.
 */
export type EventOutcome = { 
/**
 * The qualifying phase's final ranking (best seed first) — what seeds the bracket.
 */
qualifying: Array<RankEntry>, 
/**
 * The completed qualifying heats, in run order.
 */
qualifying_heats: Array<CompletedHeat>, 
/**
 * The seeded field that entered the bracket: the top `bracket_size` of `qualifying`.
 */
bracket_seeds: Array<CompetitorRef>, 
/**
 * The bracket's final ranking (winner first) — the event standings.
 */
bracket: Array<RankEntry>, 
/**
 * The completed bracket heats, in run order.
 */
bracket_heats: Array<CompletedHeat>, };
