// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies an **event** — the whole competition (protocol.html §4 "Event scope").
 *
 * A transparent string newtype like the event-model ids. The cross-event registry
 * and account model are a Cloud concern (protocol.html callout); this is just the
 * stable handle a scope addresses, sufficient for the wire contract.
 */
export type EventId = string;
