// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";

/**
 * The metadata describing one event in the registry (issue #72).
 *
 * The wire shape `GET /events` returns: a stable [`EventId`], a human display `name`, the
 * creation time, and whether the event is **persistent** (file-backed) or ephemeral (the
 * in-memory Practice event). Derives serde (its JSON *is* the wire form) and `ts_rs::TS`
 * so the frontend reads a generated `EventMeta` type.
 */
export type EventMeta = { 
/**
 * The stable handle every per-event route is rooted under (`/events/{id}/…`).
 */
id: EventId, 
/**
 * The human-readable display name (names are display-only; the id is authoritative).
 */
name: string, 
/**
 * Creation time in **milliseconds since the Unix epoch** (a plain JSON number — bounded
 * far below 2^53, rendered as a TS `number` not a `bigint`, matching every other integer
 * on the wire). Practice is seeded at registry construction.
 */
created_at: number, 
/**
 * Whether the event's log is durable (a SQLite file) or ephemeral (the in-memory
 * Practice log, `false`).
 */
persistent: boolean, };
