// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";
import type { Pass } from "./Pass";
import type { SessionId } from "./SessionId";

/**
 * A canonical event appended to the log by an adapter.
 *
 * Externally tagged (the default serde representation): each variant serialises as
 * `{ "VariantName": { ..fields } }`, which maps cleanly to a discriminated union in
 * the generated TypeScript (#4).
 */
export type Event = { "AdapterConnected": { adapter: AdapterId, } } | { "AdapterDisconnected": { adapter: AdapterId, } } | { "SessionStarted": { adapter: AdapterId, session: SessionId, } } | { "SessionEnded": { adapter: AdapterId, session: SessionId, } } | { "CompetitorSeen": { adapter: AdapterId, competitor: CompetitorRef, } } | { "Pass": Pass };
