// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelLayer } from "./ChannelLayer";
import type { ClassId } from "./ClassId";
import type { ClassMembership } from "./ClassMembership";
import type { EventId } from "./EventId";
import type { PilotId } from "./PilotId";
import type { RoundDef } from "./RoundDef";
import type { TimerId } from "./TimerId";

/**
 * The metadata describing one event in the registry (issue #72).
 *
 * The wire shape `GET /events` returns: a stable [`EventId`], a human display `name`, the
 * creation time, and whether the event is **persistent** (file-backed) or ephemeral (an
 * in-memory log, when the Director has no data dir configured). Derives serde (its JSON *is*
 * the wire form) and `ts_rs::TS`
 * so the frontend reads a generated `EventMeta` type.
 */
export type EventMeta = { 
/**
 * The stable handle every per-event route is rooted under (`/events/{id}/…`).
 */
id: EventId, 
/**
 * The human-readable display name (names are display-only; the id is authoritative).
 */
name: string, 
/**
 * Creation time in **milliseconds since the Unix epoch** (a plain JSON number — bounded
 * far below 2^53, rendered as a TS `number` not a `bigint`, matching every other integer
 * on the wire).
 */
created_at: number, 
/**
 * Whether the event's log is durable (a SQLite file) or ephemeral (an in-memory log —
 * `false`, which happens only when no data dir is configured).
 */
persistent: boolean, 
/**
 * Optional **display date** of the event, as a free-form string (e.g. `"2026-06-20"` or
 * `"Sat 20 Jun"`). A string, not an epoch — it is a *human label the RD types*, shown
 * verbatim on the picker and (later) the context header; the authoritative machine
 * timestamp is [`created_at`](Self::created_at). Omitted from the wire when unset.
 */
date?: string, 
/**
 * Optional venue / location label (e.g. `"Main field"`). Omitted from the wire when unset.
 */
location?: string, 
/**
 * Optional free-text description / notes for the event. Omitted from the wire when unset.
 */
description?: string, 
/**
 * Optional organizer name (the running club / person). Omitted from the wire when unset.
 */
organizer?: string, 
/**
 * The application-level timers this event **selects** (issue #73) — the per-event reference
 * into the app-level [`TimerRegistry`](crate::timers::TimerRegistry). Additive
 * (`#[serde(default)]`) so an event persisted before #73 reads back with an empty list; new
 * events default to `["mock"]` (the built-in Mock) so they work out of the
 * box. The per-event source bridge runs the selected Sim timers; a selected RotorHazard timer is
 * dialled by the RH connection reconciler instead (#65/#73), not by this bridge.
 */
timers: Array<TimerId>, 
/**
 * The **primary** timer among the selection (issue #112) — redundant timers at one gate, one
 * designated **primary** and the rest **alternates**. The per-event source bridge feeds **only
 * the active source's** passes into the log (the primary while it's healthy; on a primary drop
 * it fails over to the first healthy alternate; on primary recovery it switches back), so two
 * timers at the same gate give redundancy without double-counting the same crossing.
 *
 * Additive (`#[serde(default)]`) so an event persisted before #112 reads back with `None`.
 * When unset, the **first** selected timer is the effective primary (see
 * [`EventMeta::effective_primary`]). Must name a timer that is in [`timers`](Self::timers); a
 * primary not in the selection is ignored (the first selected timer is used instead).
 */
primary_timer?: TimerId, 
/**
 * The event's **roster** (issue #74) — the application-level [`Pilot`](crate::pilots::Pilot)s
 * that race this event, by their [`PilotId`]. The per-event reference into the app-level
 * [`PilotDirectory`](crate::pilots::PilotDirectory): a Director maintains their pilots once,
 * and each event simply picks which of them race it (mirroring [`timers`](Self::timers)).
 *
 * Additive (`#[serde(default)]`) so an event persisted before #74 reads back with an empty
 * roster; a new event defaults to an **empty** roster. Channels (which frequency a
 * roster pilot flies in a heat) are a separate concern (#117) and are not modelled here.
 */
roster: Array<PilotId>, 
/**
 * The application-level **classes** this event runs (issue #84) — the per-event reference into
 * the app-level [`ClassDirectory`](crate::classes::ClassDirectory), by their [`ClassId`]. The
 * per-event selection into the app-level class directory: a Director maintains their racing
 * categories once, and each event simply picks which of them run at it (mirroring
 * [`roster`](Self::roster) and [`timers`](Self::timers)).
 *
 * Additive (`#[serde(default)]`) so an event persisted before #84 reads back with an empty
 * selection; a new event defaults to an **empty** selection. This is the registry
 * slice only — the rounds / phase engine a class later drives is a separate concern.
 */
classes: Array<ClassId>, 
/**
 * **Per-class membership** (race redesign Slice 1a) — which roster pilots race each
 * [`class`](Self::classes). Each [`ClassMembership`] pairs one selected class with the
 * [`PilotId`]s racing it; a roster pilot may be a member of several classes (or none).
 *
 * Distinct from the [`roster`](Self::roster) (who is *present at the event*) and from the
 * [`classes`](Self::classes) selection (which categories *run at all*): membership is the
 * finer join of the two — given the present pilots and the running classes, *who races
 * which class*. Set per class through
 * [`set_class_membership`](EventRegistry::set_class_membership).
 *
 * Additive (`#[serde(default)]`, omitted from the wire when empty) so an event persisted
 * before Slice 1a reads back with no membership; a new event defaults to an
 * **empty** list. The whole field round-trips through the event's persisted meta (issue
 * #115), so it is restart-safe for free.
 */
classes_membership?: Array<ClassMembership>, 
/**
 * The event's **rounds** (race redesign Slice 2a) — the event-level, class-tagged, *dynamic*
 * format-instances this event runs. A [`RoundDef`] scopes a format (a
 * [`FormatRegistry`](gridfpv_engine::format::FormatRegistry) name) and its config to one or
 * more eligible [`classes`](Self::classes), with a [`SeedingRule`] for how the field is drawn.
 * Practice / qualifying rounds are added **as-you-go** through
 * [`add_round`](EventRegistry::add_round); brackets (later slices) seed from a prior round's
 * ranking via [`SeedingRule::FromRanking`].
 *
 * Additive (`#[serde(default)]`, omitted from the wire when empty) so an event persisted before
 * Slice 2a reads back with no rounds; a new event defaults to an **empty** list. The
 * whole field round-trips through the event's persisted meta (issue #115), so it is restart-safe
 * for free.
 */
rounds?: Array<RoundDef>, 
/**
 * The event's **channel layers** (#117 S2) — the event-scoped answer to *what goes on which
 * node?*
 *
 * Each [`ChannelLayer`] is one complete tuning of the event's timer (one channel per enabled
 * node), drawn from the timer's **allowed** set ([`Timer::available_channels`], S1). A bracket
 * runs off one layer all tournament; a GQ-style qualifier defines many so each pilot keeps
 * their own channel — the RD picks the strategy, the model does not.
 *
 * **This is the field that stops "editing channels in the event" from mutating the global timer
 * record.** It sits beside [`timers`](Self::timers) / [`roster`](Self::roster) /
 * [`classes`](Self::classes) because it is the same kind of thing: an event-scoped decision,
 * next to the log rather than in it. Global is the seed, the event owns what it runs — the same
 * layering as #411's base profile → event tune.
 *
 * Additive (`#[serde(default)]`, omitted from the wire when empty) so an event persisted before
 * #117 S2 reads back with no layers; a new event defaults to an **empty** list (the RD defines
 * the first one). The whole field round-trips through the event's persisted meta (issue #115),
 * so it is restart-safe for free.
 *
 * **Nothing reads it yet.** Which heat flies which layer — and the retune on arming — is S3.
 */
channel_layers?: Array<ChannelLayer>, };
