// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { TimerId } from "./TimerId";

/**
 * The metadata describing one event in the registry (issue #72).
 *
 * The wire shape `GET /events` returns: a stable [`EventId`], a human display `name`, the
 * creation time, and whether the event is **persistent** (file-backed) or ephemeral (the
 * in-memory Practice event). Derives serde (its JSON *is* the wire form) and `ts_rs::TS`
 * so the frontend reads a generated `EventMeta` type.
 */
export type EventMeta = { 
/**
 * The stable handle every per-event route is rooted under (`/events/{id}/…`).
 */
id: EventId, 
/**
 * The human-readable display name (names are display-only; the id is authoritative).
 */
name: string, 
/**
 * Creation time in **milliseconds since the Unix epoch** (a plain JSON number — bounded
 * far below 2^53, rendered as a TS `number` not a `bigint`, matching every other integer
 * on the wire). Practice is seeded at registry construction.
 */
created_at: number, 
/**
 * Whether the event's log is durable (a SQLite file) or ephemeral (the in-memory
 * Practice log, `false`).
 */
persistent: boolean, 
/**
 * Optional **display date** of the event, as a free-form string (e.g. `"2026-06-20"` or
 * `"Sat 20 Jun"`). A string, not an epoch — it is a *human label the RD types*, shown
 * verbatim on the picker and (later) the context header; the authoritative machine
 * timestamp is [`created_at`](Self::created_at). Omitted from the wire when unset.
 */
date?: string, 
/**
 * Optional venue / location label (e.g. `"Main field"`). Omitted from the wire when unset.
 */
location?: string, 
/**
 * Optional free-text description / notes for the event. Omitted from the wire when unset.
 */
description?: string, 
/**
 * Optional organizer name (the running club / person). Omitted from the wire when unset.
 */
organizer?: string, 
/**
 * The application-level timers this event **selects** (issue #73) — the per-event reference
 * into the app-level [`TimerRegistry`](crate::timers::TimerRegistry). Additive
 * (`#[serde(default)]`) so an event persisted before #73 reads back with an empty list; new
 * events and Practice default to `["mock"]` (the built-in Mock) so they work out of the
 * box. The per-event source bridge runs the selected Sim timers; a selected RotorHazard is a
 * reserved no-op stub (2b / #65).
 */
timers: Array<TimerId>, };
