// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a round a [`Command::FillRound`] fills (#216). Externally tagged like the rest
 * of the control vocabulary, so it maps to a TS string-union (`"Next" | "All"`).
 */
export type FillMode = "Next" | "All";
