// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a [`Command::FillRound`] stopped drawing heats (#395).
 *
 * Every value here is a **success**; they differ in what the RD has to do next, which is
 * exactly what `ok: true` alone could not say. Externally tagged, so it maps to a TS
 * string-union (`"SingleStep" | "Complete" | "AwaitingResult" | "Blocked"`).
 */
export type FillStop = "SingleStep" | "Complete" | "AwaitingResult" | "Blocked";
