// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FillStop } from "./FillStop";
import type { ScheduledHeat } from "./ScheduledHeat";

/**
 * What a [`Command::FillRound`] actually **did** (#395).
 *
 * The scheduling commands' useful answer is their *effect*, not their acceptance: a fill that
 * appended nothing — round finished, outstanding heat unscored, field too small for the format
 * — was reported byte-identically to one that scheduled a heat. That is not merely unhelpful,
 * it actively misleads: `ok: true` reads as "the thing you asked for happened", so a caller
 * debugging an empty log searches downstream through the projection and the read routes, all of
 * which are working correctly. Both halves are here, so nobody has to diff the event log to
 * find out which happened.
 */
export type FillRoundOutcome = { 
/**
 * The heats this fill scheduled, in append order — one for
 * [`FillMode::Next`](FillMode::Next), zero or more for [`All`](FillMode::All). **Empty
 * means the fill appended nothing**, and [`stopped`](Self::stopped) says why.
 *
 * Always serialized, empty included: "this fill scheduled nothing" is the very signal this
 * type exists to carry, and omitting the field would leave a caller inferring it from an
 * absence again — the exact shape of the bug (#395).
 */
scheduled: Array<ScheduledHeat>, 
/**
 * Why the fill stopped drawing — the machine-readable discriminator.
 */
stopped: FillStop, 
/**
 * The same thing in one RD-facing sentence, naming the round by its **label** and any heat
 * by its friendly name (never an id). Safe to show verbatim.
 */
detail: string, };
