// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatParam } from "./FormatParam";

/**
 * A format's **declared param schema** (race redesign Slice 7a): the format name plus the params
 * its generator reads. The shape `GET /formats` returns so the Rounds UI renders a params editor.
 */
export type FormatSchema = { 
/**
 * The format name (a [`FormatRegistry::standard`] name).
 */
name: string, 
/**
 * The params this format's generator reads, in display order.
 */
params: Array<FormatParam>, };
