// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamKind } from "./ParamKind";

/**
 * One **parameter schema** entry for a format (race redesign Slice 7a) — the declared shape of a
 * config knob the format's generator reads.
 *
 * The Rounds UI's params editor reads these to render the right control per knob (a number field,
 * an enum dropdown, a toggle) with its default; the server declares one per param each generator
 * actually consumes. Derives serde (its JSON *is* the `GET /formats` wire shape) + `ts_rs::TS`.
 */
export type FormatParam = { 
/**
 * The param key as it appears in a round's `params` map (e.g. `"rounds"`).
 */
key: string, 
/**
 * A human-readable label for the param (e.g. `"Rounds"`).
 */
label: string, 
/**
 * How the param is rendered / validated.
 */
kind: ParamKind, 
/**
 * For an [`Enum`](ParamKind::Enum) param, the allowed values (the raw strings stored in
 * `params`); empty for `number` / `bool`.
 */
options?: Array<string>, 
/**
 * The default value (the raw string the format falls back to when the param is unset), or
 * `None` when the format has no default.
 */
default?: string, };
