// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which gate a [`Pass`] crossed. The lap gate is index `0`; higher indices are
 * splits for sources that report multiple gates (Velocidrone). Lap derivation
 * counts lap-gate passes; splits are intermediate detail.
 */
export type GateIndex = number;
