// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The grace window for late crossings after a heat is finished (race-engine.html
 * §2): "late crossings still count until the heat is finalized; the window is
 * configurable, default until finalized".
 *
 * Derives serde + `ts_rs::TS` so it can be carried as a per-round config
 * ([`RoundDef::grace_window`](../../server/events/struct.RoundDef.html)) and read by the
 * frontend. The runtime completion clock (heat-lifecycle Slice 2) reads this to decide how long
 * to hold the heat in `Running` for trailing pilots after the win condition is met, before
 * appending the auto `Running → Unofficial`.
 */
export type GraceWindow = "UntilScored" | { "Duration": { 
/**
 * Length of the grace window, in microseconds on the source clock.
 */
micros: number, } };
