// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The grace window after the **race window expires**: how long the heat stays `Running` so each
 * pilot can *finish the lap they were already flying* (#505).
 *
 * The runtime completion clock reads this at the heat's fixed end (the round's
 * `time_limit_secs`, or a Timed window): with a non-zero window it appends the `RaceExpired`
 * marker and holds the heat `Running` until the window elapses — or **earlier**, once every
 * still-flying pilot has taken their one post-expiry crossing
 * ([`grace_satisfied`](crate::scoring::grace_satisfied)). The marker's log position is the
 * scoring boundary: a competitor's first lap-gate pass appended after it still counts; every
 * later one is auto-voided by the corrected fold (`AfterRaceEnd`), marshal-restorable.
 *
 * Derives serde + `ts_rs::TS` so it can be carried as a per-round config
 * ([`RoundDef::grace_window`](../../server/events/struct.RoundDef.html)) and read by the
 * frontend.
 */
export type GraceWindow = "UntilScored" | { "Duration": { 
/**
 * Length of the grace window, in microseconds on the source clock.
 */
micros: number, } };
