// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transition of the heat-loop state machine (race-engine.html §2). The recorded
 * transition is named for the state it enters on the forward path (Staged → Armed →
 * Running → Finished → Scored), with the off-ramps (abort/restart/discard) named for
 * the action so they stay distinct even when they land on the same state. The engine
 * validates legality against the current state. Heat *creation* is a separate event
 * ([`Event::HeatScheduled`]) — it carries the lineup, which a transition does not.
 */
export type HeatTransition = "Staged" | "Armed" | "Running" | "Finished" | "Scored" | "Advanced" | "Aborted" | "Restarted" | "Discarded";
