// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transition of the heat-loop state machine (race-engine.html §2). One event per
 * verb; the engine validates legality against the current state — the recorded
 * transition, not a target state, so abort/restart/discard stay distinct even when
 * they land on the same state.
 */
export type HeatTransition = "Staged" | "Armed" | "Started" | "Landed" | "Scored" | "Advanced" | "Aborted" | "Restarted" | "Discarded";
