// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatPhase } from "./HeatPhase";
import type { RoundId } from "./RoundId";

/**
 * A scheduled heat as the **Heats UI** lists it (race redesign Slice 3b) — the per-heat view
 * model the Rounds & Heats stage renders under each round.
 *
 * Unlike [`LiveRaceState`] (which is *only* about the current heat), this is one entry per heat
 * the log ever scheduled, carrying the round/class tag the scheduler assigned so the UI can group
 * heats by round and resolve their lineup to pilots. Folded from the log by
 * [`heat_summaries`] — pure and recomputable like every other projection.
 */
export type HeatSummary = { 
/**
 * The heat's id (its scheduled handle, the same one the live/control path drives).
 */
heat: HeatId, 
/**
 * The heat's lineup — the competitors from its most recent `HeatScheduled`, in lineup order.
 */
lineup: Array<CompetitorRef>, 
/**
 * The class this heat was tagged with, when the scheduler assigned one (`None` for the
 * free-text / untagged path).
 */
class?: ClassId, 
/**
 * The round this heat was tagged with, when the scheduler assigned one. The Heats UI groups
 * the list by this.
 */
round?: RoundId, 
/**
 * The heat's folded loop phase (its derived status: scheduled / running / scored / …).
 */
phase: HeatPhase, 
/**
 * Whether this heat is the one currently on the timer (the live `current_heat`).
 */
is_current: boolean, };
