// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Placement } from "./Placement";

/**
 * The scored heat: every competitor's [`Placement`], best position first.
 *
 * Ties share a `position` (see [`Placement::position`]). The order within a tie
 * group is still deterministic — competitors are ordered by [`CompetitorKey`] as
 * the final, total tie-break — but their `position` numbers are equal.
 */
export type HeatResult = { 
/**
 * Placements in finishing order (ties adjacent, sharing a position).
 */
places: Array<Placement>, };
