// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Placement } from "./Placement";

/**
 * The scored heat: every competitor's [`Placement`], best position first.
 *
 * Ties share a `position` (see [`Placement::position`]). The order within a tie
 * group is still deterministic — competitors are ordered by [`CompetitorKey`] as
 * the final, total tie-break — but their `position` numbers are equal.
 */
export type HeatResult = { 
/**
 * Placements in finishing order (ties adjacent, sharing a position).
 */
places: Array<Placement>, 
/**
 * Whether the whole heat was **voided** by an adjudication
 * ([`gridfpv_events::Event::HeatVoided`]). A voided result is nullified: its
 * `places` are still scored (so the on-track standing is visible) but the heat does
 * not count. Defaults to `false` and is omitted from the wire when false.
 */
voided?: boolean, };
