// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatPhase } from "./HeatPhase";
import type { LayoutId } from "./LayoutId";
import type { RoundId } from "./RoundId";

/**
 * A scheduled heat as the **Heats UI** lists it (race redesign Slice 3b) — the per-heat view
 * model the Rounds & Heats stage renders under each round.
 *
 * Unlike [`LiveRaceState`] (which is *only* about the current heat), this is one entry per heat
 * the log ever scheduled, carrying the round/class tag the scheduler assigned so the UI can group
 * heats by round and resolve their lineup to pilots. Folded from the log by
 * [`heat_summaries`] — pure and recomputable like every other projection.
 */
export type HeatSummary = { 
/**
 * The heat's id (its scheduled handle, the same one the live/control path drives).
 */
heat: HeatId, 
/**
 * The heat's lineup — the competitors from its most recent `HeatScheduled`, in lineup order.
 */
lineup: Array<CompetitorRef>, 
/**
 * The class this heat was tagged with, when the scheduler assigned one (`None` for the
 * free-text / untagged path).
 */
class?: ClassId, 
/**
 * The round this heat was tagged with, when the scheduler assigned one. The Heats UI groups
 * the list by this.
 */
round?: RoundId, 
/**
 * The per-pilot **frequency assignment** of this heat, in raw MHz, paired with the competitor
 * it is assigned to — taken from the most recent `HeatScheduled` (race redesign Slice 4b). The
 * Heats/Live UI resolves each raw MHz back to a band+channel label via the channel catalog.
 * Empty when none was assigned (a sim heat, or the free-text path), in which case the UI shows
 * "—". Additive — defaults empty so older logs round-trip.
 */
frequencies?: Array<[CompetitorRef, number]>, 
/**
 * The **optional human label** the RD typed when building this heat by hand, from the most
 * recent `HeatScheduled`. When present the Heats/Live UI shows it as the heat's display name
 * (overriding the derived "‹Round› Heat N" / tier convention); `None` for a generator-filled
 * heat, which keeps the auto-name. Additive — defaults absent so older logs round-trip.
 */
label?: string, 
/**
 * The **channel layout** this heat flies (#117 S3) — the last
 * [`HeatLayoutSet`](gridfpv_events::Event::HeatLayoutSet) for it.
 *
 * A wire handle: the console resolves it to the layout's **name** against the event's
 * `channel_layouts` (CLAUDE.md), and uses its `node → channel` mapping as the per-node channel
 * source a seat resolves through — the value that replaces `available_channels[node]`, which
 * an allowed set never had any business answering.
 *
 * This is the **RD's own bind**, not the layout the heat resolves to: `None` whenever no
 * `HeatLayoutSet` names one — the RD never picked for this heat (#441: the fill records no
 * bind, so this is the common case for a generated heat, which follows its round's default),
 * they cleared their pick, or the round names no layouts at all. The heat's actual per-seat
 * channels are always on [`frequencies`](Self::frequencies), which is the first source a
 * console seat resolves through; this only backfills a seat that has none. Additive —
 * defaults absent so older logs round-trip.
 */
layout?: LayoutId, 
/**
 * The heat's folded loop phase (its derived status: scheduled / running / final / …).
 */
phase: HeatPhase, 
/**
 * Whether this heat is the one currently on the timer (the live `current_heat`).
 */
is_current: boolean, };
