// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractVersion } from "./ContractVersion";

/**
 * The client's **connect message** (protocol.html §7): announced before anything
 * else, it carries the [`ContractVersion`] the client was built against so the
 * server can decide whether it can serve it.
 *
 * "The contract version is negotiated, not assumed" (§7): the client states its
 * version, the server replies with the band it serves ([`ServerHello`]). The version
 * is the only thing negotiated here; auth (a bearer token, §9.4) is a separate #44
 * concern layered in front, not part of this message yet.
 */
export type Hello = { 
/**
 * The contract version the client was built against.
 */
contract_version: ContractVersion, };
