// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The single two-tone product that hurts a channel set most — the **worst offender** (#117 S4).
 *
 * [`imd_rating`] answers *how clean is this set*; it cannot answer *what is wrong with it*. This
 * does, and it is the other half of what an RD needs while they are still choosing channels: a
 * number tells them to change something, this tells them **what**.
 *
 * Every field is a raw wire value. `doubled`, `subtracted` and `lands_on` are channels **in the
 * set**, so all three have friendly names and none may reach a person as bare MHz — they resolve
 * through the console's shared channel resolver (`channels.ts`'s `channelLabel`). `product` is
 * arithmetic, not an entity: it is `2 · doubled − subtracted`, and it is the one number here that
 * names nothing.
 *
 * Read as a sentence: *two times `doubled`, minus `subtracted`, equals `product` — which is
 * `gap_mhz` MHz from `lands_on`, a channel somebody in this heat is flying.*
 */
export type ImdProduct = { 
/**
 * The channel that mixes with itself — `f_i` in `2·f_i − f_j`. A channel in the rated set.
 */
doubled: number, 
/**
 * The channel subtracted from it — `f_j` in `2·f_i − f_j`. A channel in the rated set.
 */
subtracted: number, 
/**
 * The product frequency in MHz, `2·doubled − subtracted`. Always inside the receivable band
 * (`5100..=6099`), which is why it fits a `u16` where the raw arithmetic would not.
 */
product: number, 
/**
 * The channel in the set the product comes **closest** to — the pilot whose video it breaks.
 */
lands_on: number, 
/**
 * How far the product misses [`lands_on`](Self::lands_on) by, in MHz. Always under
 * [`RATING_DIFF_LIMIT_MHZ`] (a product further out than that is not an offender at all), and
 * `0` means the product lands *exactly* on a used channel.
 */
gap_mhz: number, };
