// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImdProduct } from "./ImdProduct";

/**
 * A channel set's IMD **reading**: the rating, and the worst offender behind it (#117 S4).
 *
 * The pair is deliberate. The rating alone is the number an RD already reads off RotorHazard, so
 * it is the one that must be shown — but on its own it is a verdict with no next step. The
 * offender is the next step, and it is the specific thing the RD can act on while they are still
 * picking channels.
 *
 * **Advisory, always.** Nothing consults a reading to accept or refuse anything: a layout with a
 * poor rating still saves, because the RD may have no better option (a Raceband-only timer
 * genuinely cannot beat 0 at five pilots) and information that blocks is a refusal wearing a
 * hint's clothes.
 *
 * No threshold, no verdict word, and deliberately no clean/marginal/poor band — see this module's
 * header for why a flat band is unreachable at five or more pilots.
 */
export type ImdReading = { 
/**
 * IMDTabler's rating for the set — **higher is cleaner**, [`RATING_MAX`] is the ceiling, and a
 * bad set goes negative. Exactly [`imd_rating`]'s answer; see it for what the number means.
 */
rating: number, 
/**
 * The worst two-tone product, or `None` when **no** product comes within
 * [`RATING_DIFF_LIMIT_MHZ`] of a used channel — in which case there is nothing to name, and
 * the honest thing to say is that the set is clean rather than to report a nearest miss that
 * is not a problem.
 */
worst?: ImdProduct, };
