// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of a successful `POST /auth/join-token` (protocol.html §5, §9.4) — issue #63.
 *
 * A freshly-minted **read-only** join token, returned to an authenticated RD so it can
 * hand it (e.g. as a venue QR / share URL) to a spectator. The token authenticates LAN
 * **reads** but is rejected on control ([`Role::can_control`]). The single-field wire
 * shape leaves room to grow additively (an expiry, a scope) without breaking an older
 * client that reads only `token`.
 */
export type JoinTokenResponse = { 
/**
 * The opaque, URL/QR-safe read-only join token (see [`random_token`]).
 */
token: string, };
