// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRef } from "./LogRef";

/**
 * A single completed lap: the interval between two consecutive lap-gate passes.
 *
 * The lap also carries the **global append offsets** ([`LogRef`]) of the two passes that
 * bound it — `start_ref` (the opening pass) and `end_ref` (the closing pass). These are the
 * *stable* log offsets a marshaling command targets (`VoidDetection`/`AdjustLap`/`SplitLap`
 * all key on a single pass's offset), so a UI that selects a lap can address the correct pass
 * without the operator hand-typing an offset (#55). They are real global offsets even when the
 * lap list is folded from a heat window — the fold is fed `(global_offset, &Event)` pairs, so
 * `end_ref`/`start_ref` are valid command targets across a multi-heat log (the heat-window
 * re-enumeration bug this fixes).
 */
export type Lap = { 
/**
 * 1-based lap number within the competitor's run.
 */
number: number, 
/**
 * Lap duration in microseconds on the source clock
 * (`pass[n + 1].at - pass[n].at`). Always `>= 0` for in-order passes.
 * Renders as a plain TS `number` (bounded far below 2^53).
 */
duration_micros: number, 
/**
 * Global append offset of the pass that **opens** this lap (the lap's start gate).
 */
start_ref: LogRef, 
/**
 * Global append offset of the pass that **closes** this lap (the lap's end gate). This is
 * the natural correction target: voiding/adjusting it edits this lap's boundary, and a
 * `SplitLap` splits the over-long lap *ending* here.
 */
end_ref: LogRef, };
