// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single completed lap: the interval between two consecutive lap-gate passes.
 */
export type Lap = { 
/**
 * 1-based lap number within the competitor's run.
 */
number: number, 
/**
 * Lap duration in microseconds on the source clock
 * (`pass[n + 1].at - pass[n].at`). Always `>= 0` for in-order passes.
 * Renders as a plain TS `number` (bounded far below 2^53).
 */
duration_micros: number, };
