// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorLaps } from "./CompetitorLaps";

/**
 * The lap-list read model: per-competitor lap lists derived from the log.
 *
 * Competitors are ordered deterministically by [`CompetitorKey`] so the
 * projection is stable across runs regardless of event arrival order.
 */
export type LapList = { 
/**
 * Per-competitor laps, ordered by competitor key.
 */
competitors: Array<CompetitorLaps>, };
