// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerId } from "./LayerId";

/**
 * Two layers that share at least one channel (#117 S2) — a **warning**, never a refusal.
 *
 * The RD settled this explicitly: *"if I have R1-4 in one layer, I cannot use R1-4 in the next"*
 * only matters for the **keep-pilots-on-one-channel** strategy. If layers are just timer tunings,
 * reusing a channel across them is harmless — so it is flagged so an RD pursuing that strategy
 * sees it, and it never blocks an RD who does not care. Nothing in the write path consults this;
 * it is computed on top of a layer set that has *already been accepted*.
 *
 * Carries the two [`LayerId`]s as **wire handles** and the shared channels as raw MHz. Both resolve
 * to names in the console (layer id → `ChannelLayer.name`, MHz → `channelLabel`), which is the
 * repo's rule: ids travel, names display.
 */
export type LayerOverlap = { 
/**
 * The **earlier** of the two layers, in the event's layer order.
 */
layer: LayerId, 
/**
 * The **later** of the two layers, in the event's layer order.
 */
other: LayerId, 
/**
 * The channels both layers use, ascending. Never empty (an empty intersection is not reported).
 */
channels: Array<number>, };
