// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one **channel layer** within an event (#117 S2).
 *
 * A transparent string newtype like every other id on the wire, and **auto-generated** (a slug of
 * the layer's name plus a short random suffix — the same id-gen as events / pilots / rounds).
 * Never user-entered, and a **wire handle only**: what an RD reads is [`ChannelLayer::name`]
 * (CLAUDE.md's display rule).
 */
export type LayerId = string;
