// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImdReading } from "./ImdReading";
import type { LayoutId } from "./LayoutId";

/**
 * One layout's **IMD reading** (#117 S4) — how cleanly its channels fly together, and what the
 * worst offending mixing product is.
 *
 * Keyed by [`LayoutId`] rather than positional, for the same reason [`LayoutOverlap`] carries ids:
 * a parallel array silently mis-labels every layout the day someone filters the list.
 *
 * **Advisory, exactly like [`LayoutOverlap`].** Nothing in the write path consults it — a layout
 * with a poor rating saves like any other, because the RD may have no better option and a
 * Raceband-only timer genuinely cannot do better than 0 at five pilots.
 */
export type LayoutRating = { 
/**
 * The layout this reading is for.
 */
layout: LayoutId, 
/**
 * The reading itself — IMDTabler's rating plus the worst two-tone product, or no offender at
 * all when the set is clean.
 */
imd: ImdReading, };
