// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies one **channel layout** within an event (#117 S2/S3) — a named `node → channel`
 * tuning of the event's timer.
 *
 * Defined here rather than in `gridfpv_server` because a **heat carries the layout it flies**
 * ([`Event::HeatScheduled::layout`]), exactly as it carries its class and round: which channels a
 * heat raced on is a fact about the heat, and facts about a heat live in the log. The richer
 * `ChannelLayout` (the mapping itself) stays event *config* in `gridfpv_server::events`, which
 * re-exports this type so the log and the protocol never disagree on what a layout id is.
 *
 * A transparent string newtype like [`ClassId`] / [`RoundId`], **auto-generated** (a slug of the
 * layout's name plus a short random suffix), and a **wire handle only**: what an RD reads is the
 * layout's name.
 */
export type LayoutId = string;
