// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node's tuning within a [`ChannelLayout`] (#117 S2): the node index and the raw-MHz channel it
 * is tuned to.
 *
 * **0-based on the wire, 1-based on screen** — index `2` is the node the RD calls "Node 3"
 * ([`Timer::node_label`]), and `channel` is a raw frequency that renders through
 * [`crate::timers::channel_label`] as `"Raceband R7"`. Neither raw value may reach a person; both
 * are wire handles.
 */
export type LayoutNode = { 
/**
 * The node's index on the timer, **0-based** — the same index [`TimerNode`] carries, and the
 * one `NodeSignal::node` and the `node-{i}` seat ref mean.
 */
node: number, 
/**
 * The raw centre frequency in **MHz** this node is tuned to in this layout. Must be one of the
 * timer's [`available_channels`](Timer::available_channels) — the *allowed* set S1 clarified.
 */
channel: number, };
