// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The provisional → official lifecycle of a heat's result (marshaling Slice 5), projected for the
 * UI from the heat FSM + the logged auto-official deadline.
 *
 * This is **not** a new FSM state: it reuses the heat's existing `Unofficial` (provisional,
 * correctable) → `Final` (official) transition. [`Provisional`](Self::Provisional) maps onto
 * `Unofficial`; [`Official`](Self::Official) onto `Final`. The optional `auto_official_at` is the
 * server-clock instant the runtime will auto-finalize, present only when the round armed a
 * [`ProtestWindow::After`](gridfpv_engine::heat::ProtestWindow::After).
 */
export type LifecycleState = { "Provisional": { auto_official_at?: number, } } | "Official";
