// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { CrossingDisposition } from "./CrossingDisposition";
import type { LogRef } from "./LogRef";
import type { PilotId } from "./PilotId";
import type { SourceTime } from "./SourceTime";

/**
 * One gate crossing of the current heat, with what became of it (#397).
 *
 * The **crossing** is the observation; the lap is a derivation over pairs of them. This carries
 * the observation, so a consumer can react to crossings that never became laps — the holeshot,
 * and a pass rejected under the min-lap floor.
 *
 * Competitor and pilot are raw wire handles, exactly as [`PilotProgress`] carries them; the
 * console resolves them to a callsign through its shared resolver before anything is displayed.
 */
export type LiveCrossing = { 
/**
 * **The crossing's stable identity**: its global append offset in the event log. Identical on
 * every re-fold of the same log and across every scope, so a consumer deduplicates on this
 * and never on frame arrival. The feed is sorted ascending by it.
 */
pass_ref: LogRef, 
/**
 * The source-local competitor that crossed. Not necessarily a member of the current lineup —
 * a crossing on an unseated node is reported too, because a phantom detection is exactly what
 * an RD needs to notice.
 */
competitor: CompetitorRef, 
/**
 * The GridFPV pilot this competitor is bound to, if a registration has bound it (#60). `None`
 * for an unregistered competitor, which still appears by its bare [`CompetitorRef`].
 */
pilot?: PilotId, 
/**
 * When the crossing happened, on the **source's** clock (µs) — the same axis as
 * [`Lap::at`](gridfpv_projection::Lap::at) and the signal trace's sample times, NOT the server
 * wall clock the race anchors (`race_started_at`) use. Renders as a plain TS `number`.
 */
at: SourceTime, 
/**
 * What became of this crossing — holeshot / counted / rejected-too-short / voided by a
 * marshal. Derived from the crossing's position in the corrected pass chain and the fold's
 * removal record; nothing in the log states it.
 *
 * A crossing's disposition MAY change while its `pass_ref` stays the same (a marshal voids a
 * counted lap; voiding a holeshot promotes the next crossing). That is correct and is why
 * deduplication keys on `pass_ref` alone: a re-labelled crossing is not a new one.
 */
disposition: CrossingDisposition, 
/**
 * The 1-based lap this crossing **closed**, when it closed one. `None` for a holeshot (it
 * opens the first lap and closes none) and for a rejected or voided crossing. Lets a consumer
 * tell a crossing that already drove a lap callout from one that did not, without
 * re-deriving laps.
 */
lap_number?: number, };
