// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatPhase } from "./HeatPhase";
import type { LifecycleState } from "./LifecycleState";
import type { LiveCrossing } from "./LiveCrossing";
import type { PilotProgress } from "./PilotProgress";

/**
 * The current **live race-state** projection (protocol.html §1) — the latency-sensitive
 * core every overlay and spectator watches.
 *
 * Fleshed out in #41 from the #40 placeholder: it carries the current heat and its
 * [`HeatPhase`], the active pilots in that heat, each pilot's live
 * [`PilotProgress`], the running order, and the on-deck heat. Fields are additive over
 * the placeholder (§7), so the snapshot body and change envelope did not reshape.
 */
export type LiveRaceState = { 
/**
 * The heat currently on the timer, if any (`None` before any heat is scheduled).
 */
current_heat?: HeatId, 
/**
 * The current heat's loop phase (protocol.html §1, race-engine.html §2). When
 * `current_heat` is `None` this is [`HeatPhase::Scheduled`] (the idle default).
 */
phase: HeatPhase, 
/**
 * The active pilots in the current heat — its lineup, in lineup (seeding) order.
 * Empty when there is no current heat.
 */
active_pilots?: Array<CompetitorRef>, 
/**
 * Per-pilot live lap progress for the current heat, one entry per active pilot,
 * ordered like [`active_pilots`](Self::active_pilots).
 */
progress?: Array<PilotProgress>, 
/**
 * The provisional running order of the current heat: the active pilots ranked by
 * live standing (most laps, then who banked their last lap earliest). Best first.
 */
running_order?: Array<CompetitorRef>, 
/**
 * The next heat to run after the current one (the earliest still-`Scheduled` heat
 * that is not on the timer), if one is known.
 */
on_deck?: HeatId, 
/**
 * The **server-authoritative race-start instant** of the current heat: the
 * `recorded_at` (microseconds, server wall clock) of the `Armed → Running`
 * transition that put it on the timer (the real race-go). `None` before the heat
 * has started (or for an older log whose transition carried no timestamp).
 *
 * This is the anchor every client clock counts from — header and HUD alike — so the
 * elapsed reads identically and accurately *regardless of when the client mounted*
 * (the #62 follow-up: kill the per-client wall-clock drift). Renders as a plain TS
 * `number` (microseconds, bounded far below 2^53).
 */
race_started_at?: number, 
/**
 * The **server-authoritative race-end instant** of the current heat: the
 * `recorded_at` (microseconds, server wall clock) of the `Running → Unofficial`
 * transition that closed it. `None` while the heat is still running (or has not
 * started). When set, `race_ended_at - race_started_at` is the **exact** race
 * duration a frozen clock reads (so a 60s limit reads `1:00.000`, not `1:00.100`).
 * Renders as a plain TS `number` (microseconds).
 */
race_ended_at?: number, 
/**
 * The **server-authoritative staging-start instant** of the current heat while it is
 * `Staged`: the `recorded_at` (microseconds, server wall clock) of its latest
 * `Scheduled → Staged` transition. The staging countdown anchors here — a per-client
 * wall-clock anchor made every console (and every reload) count its own window, so the
 * RD's console could read overtime while a fresh one read the full window. `None` in
 * every non-Staged phase. Renders as a plain TS `number` (microseconds).
 */
staged_at?: number, 
/**
 * The **server-authoritative start-tone instant** of the current heat while it is `Armed`:
 * the absolute wall-clock instant (microseconds since the Unix epoch) the start tone fires
 * and the heat auto-advances `Armed → Running`. Derived from the `recorded_at` of the heat's
 * [`HeatStarting`](gridfpv_events::Event::HeatStarting) event plus its logged `delay_ms` (the
 * chosen randomized hold). `None` once the heat is `Running`/past (or before it has armed).
 *
 * **RD-console-only:** the start delay is *intentionally random to pilots*, so this is the
 * anchor the RD's control view counts down to ("tone in 0:03") — the read-only / pilot view
 * never renders it. It is `None` once `race_started_at` is set, so a late join after race-go
 * sees no stale countdown. Renders as a plain TS `number` (microseconds).
 */
tone_at?: number, 
/**
 * The current heat's **grace deadline** while its race window has expired but the heat is
 * still `Running` (#505): the logged `deadline` of its latest
 * [`RaceExpired`](gridfpv_events::Event::RaceExpired) marker — the server wall-clock instant
 * (microseconds since the Unix epoch) at which the runtime closes the heat if pilots are
 * still out. The console's "grace" countdown anchors here, exactly as the auto-official
 * countdown anchors on the `HeatFinalizing` deadline. `None` before the race window expires,
 * in every non-`Running` phase, and for an unbounded (`UntilScored`) grace — whose marker
 * carries no deadline. Renders as a plain TS `number` (microseconds).
 */
grace_deadline?: number, 
/**
 * The **provisional → official lifecycle** of the current heat (marshaling Slice 5,
 * marshaling.html §3.3), surfaced for the Marshaling/Live UI. `None` until the heat reaches the
 * `Unofficial` phase (before that there is no result to be provisional about). Once provisional
 * it carries the auto-official deadline (when a protest window is armed) so the console can show
 * a "Provisional — auto-official in M:SS" countdown; `Official` once finalized. Derived from the
 * heat's phase + the logged [`HeatFinalizing`](gridfpv_events::Event::HeatFinalizing) deadline,
 * so it folds deterministically like the rest of this projection.
 */
lifecycle?: LifecycleState, 
/**
 * The current heat's recent **gate crossings, each with its disposition** (#397) — the live
 * feed a console announces from, in ascending `pass_ref` (append-offset) order.
 *
 * `progress` reports *laps*, and laps are derived (`passes.windows(2)`), so a lap-derived
 * consumer is structurally blind to most crossings: the **holeshot** closes no lap, and a
 * crossing **rejected under the round's min-lap floor** is auto-voided in the projection and
 * reaches no live consumer at all. This field carries the crossings themselves, so "the gate
 * saw nothing" and "the gate saw something that did not count" stop being the same silence.
 *
 * **Idempotency (the hard requirement).** Every entry carries a stable
 * [`pass_ref`](LiveCrossing::pass_ref) — the crossing's global append offset — and the feed is
 * ordered by it. A consumer holds a single high-water mark and acts on `pass_ref >` it, so
 * a re-pushed or re-snapshotted `LiveRaceState` (or a resubscribe, or a scope change) can
 * never look like new crossings. Receipt of a frame means nothing; identity is everything.
 *
 * **Bounded** to the most recent [`MAX_LIVE_CROSSINGS`] entries — see that constant for why
 * dropping the *oldest* is the one truncation that leaves the high-water mark sound.
 *
 * Additive: absent on the wire when empty, so older payloads round-trip.
 */
crossings?: Array<LiveCrossing>, };
