// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeatId } from "./HeatId";
import type { HeatPhase } from "./HeatPhase";

/**
 * The current **live race-state** projection (protocol.html §1) — the latency-sensitive
 * core every overlay and spectator watches: the current heat and its loop state, the
 * active pilots' live lap/split progress, the running order, and the on-deck heat.
 *
 * **#41 placeholder.** This is intentionally minimal-but-real: it carries the current
 * heat id and a coarse [`HeatPhase`] so the contract, the snapshot body, and the
 * change envelope are all wired end to end *now*. #41 fleshes it out with per-pilot
 * live progress, the running order, and the on-deck heat. Keeping the type real (not a
 * unit stub) means #41 extends fields additively (§7) without reshaping the envelope.
 */
export type LiveRaceState = { 
/**
 * The heat currently on the timer, if any (`None` between heats).
 */
current_heat?: HeatId, 
/**
 * The current heat's loop phase (protocol.html §1, race-engine.html §2).
 */
phase: HeatPhase, };
