// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";
import type { HeatPhase } from "./HeatPhase";
import type { LifecycleState } from "./LifecycleState";
import type { PilotProgress } from "./PilotProgress";

/**
 * The current **live race-state** projection (protocol.html §1) — the latency-sensitive
 * core every overlay and spectator watches.
 *
 * Fleshed out in #41 from the #40 placeholder: it carries the current heat and its
 * [`HeatPhase`], the active pilots in that heat, each pilot's live
 * [`PilotProgress`], the running order, and the on-deck heat. Fields are additive over
 * the placeholder (§7), so the snapshot body and change envelope did not reshape.
 */
export type LiveRaceState = { 
/**
 * The heat currently on the timer, if any (`None` before any heat is scheduled).
 */
current_heat?: HeatId, 
/**
 * The current heat's loop phase (protocol.html §1, race-engine.html §2). When
 * `current_heat` is `None` this is [`HeatPhase::Scheduled`] (the idle default).
 */
phase: HeatPhase, 
/**
 * The active pilots in the current heat — its lineup, in lineup (seeding) order.
 * Empty when there is no current heat.
 */
active_pilots?: Array<CompetitorRef>, 
/**
 * Per-pilot live lap progress for the current heat, one entry per active pilot,
 * ordered like [`active_pilots`](Self::active_pilots).
 */
progress?: Array<PilotProgress>, 
/**
 * The provisional running order of the current heat: the active pilots ranked by
 * live standing (most laps, then who banked their last lap earliest). Best first.
 */
running_order?: Array<CompetitorRef>, 
/**
 * The next heat to run after the current one (the earliest still-`Scheduled` heat
 * that is not on the timer), if one is known.
 */
on_deck?: HeatId, 
/**
 * The **server-authoritative race-start instant** of the current heat: the
 * `recorded_at` (microseconds, server wall clock) of the `Armed → Running`
 * transition that put it on the timer (the real race-go). `None` before the heat
 * has started (or for an older log whose transition carried no timestamp).
 *
 * This is the anchor every client clock counts from — header and HUD alike — so the
 * elapsed reads identically and accurately *regardless of when the client mounted*
 * (the #62 follow-up: kill the per-client wall-clock drift). Renders as a plain TS
 * `number` (microseconds, bounded far below 2^53).
 */
race_started_at?: number, 
/**
 * The **server-authoritative race-end instant** of the current heat: the
 * `recorded_at` (microseconds, server wall clock) of the `Running → Unofficial`
 * transition that closed it. `None` while the heat is still running (or has not
 * started). When set, `race_ended_at - race_started_at` is the **exact** race
 * duration a frozen clock reads (so a 60s limit reads `1:00.000`, not `1:00.100`).
 * Renders as a plain TS `number` (microseconds).
 */
race_ended_at?: number, 
/**
 * The **provisional → official lifecycle** of the current heat (marshaling Slice 5,
 * marshaling.html §3.3), surfaced for the Marshaling/Live UI. `None` until the heat reaches the
 * `Unofficial` phase (before that there is no result to be provisional about). Once provisional
 * it carries the auto-official deadline (when a protest window is armed) so the console can show
 * a "Provisional — auto-official in M:SS" countdown; `Official` once finalized. Derived from the
 * heat's phase + the logged [`HeatFinalizing`](gridfpv_events::Event::HeatFinalizing) deadline,
 * so it folds deterministically like the rest of this projection.
 */
lifecycle?: LifecycleState, };
