// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an already-logged event by its append **offset** — the stable id
 * marshaling adjudications target (e.g. "void *this* pass"). The offset is assigned
 * by the storage layer when the target event was appended.
 */
export type LogRef = number;
