// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotId } from "./PilotId";

/**
 * One pilot's **slot** within a class's membership (race redesign Slice 7a): the directory pilot
 * plus the optional raw-MHz channel they fly in a *static*-channel-mode round.
 *
 * The channel is the GQ-style **fixed, per-membership** assignment: in a [`ChannelMode::Static`]
 * round (time-trial / qualifying), every member flies their own channel and qual heats are
 * channel-balanced (one pilot per channel per heat). It is `None` until set, and is unused by a
 * [`ChannelMode::PerHeat`] round (the bracket path assigns channels per heat). Validated on set
 * against the event's **primary timer**'s `available_channels` — and that pool **can exceed** the
 * timer's `node_count`, so any channel in the pool is valid (node_count caps only pilots-per-heat).
 *
 * Derives serde + `ts_rs::TS` so the frontend reads a generated `MemberSlot` for the Classes &
 * Roster channel picker (the UI is the Slice-7b follow-up).
 */
export type MemberSlot = { 
/**
 * The directory pilot racing this class.
 */
pilot: PilotId, 
/**
 * The pilot's **fixed assigned channel** (raw MHz) for *static*-channel-mode rounds, or `None`
 * when unassigned. Must be one of the event's **primary timer**'s `available_channels`
 * (validated on set) — the pool may be larger than `node_count`.
 */
channel?: number, };
