// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceTime } from "./SourceTime";

/**
 * The condition-specific value a [`Placement`] was ranked on, kept for display and
 * for tests to assert against exact numbers.
 */
export type Metric = { "LastLapAt": SourceTime | null } | { "ReachedAt": SourceTime | null } | { "BestLapMicros": bigint | null } | { "BestConsecutiveMicros": bigint | null };
