// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerNode } from "./LayerNode";

/**
 * The body of `POST /events/{id}/layers` — define a new channel layer (#117 S2).
 *
 * The id is generated server-side (never user-entered). `nodes` is **optional and that is the
 * global→event seam**: omit it and the layer is *seeded* from the event timer's allowed set —
 * enabled node *i* takes the *i*-th allowed channel, in the RD's own preference order. That is the
 * whole of "global is the default subset an event starts from"; from the moment the layer exists
 * it is event state, and editing it never touches [`Timer::available_channels`].
 */
export type NewChannelLayerRequest = { 
/**
 * The layer's display name. Trimmed; must be non-empty and unique within the event.
 */
name: string, 
/**
 * The explicit node → channel mapping, or omitted to **seed** it from the timer's allowed set.
 */
nodes?: Array<LayerNode>, };
