// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { SeedingRule } from "./SeedingRule";
import type { WinCondition } from "./WinCondition";

/**
 * The body of `POST /events/{id}/rounds` — everything a caller supplies to add a round (race
 * redesign Slice 2a).
 *
 * The **id is always auto-generated** (a slug of `label` plus a short random suffix), never
 * user-entered — mirroring the event/pilot create rule. The [`seeding`](Self::seeding) defaults to
 * [`SeedingRule::FromRoster`] when omitted. The route returns the created [`RoundDef`] (with its
 * generated [`id`](RoundDef::id)).
 */
export type NewRoundReq = { 
/**
 * The display label for the new round (e.g. `"Qualifying R1"`).
 */
label: string, 
/**
 * The eligible classes this round runs for. Each must be one of the event's selected classes.
 */
classes: Array<ClassId>, 
/**
 * The format this round runs — a known [`FormatRegistry`] name.
 */
format: string, 
/**
 * The format's config knobs, stored verbatim.
 */
params: { [key in string]: string }, 
/**
 * How a heat in this round is won.
 */
win_condition: WinCondition, 
/**
 * How the round's field is seeded; defaults to [`SeedingRule::FromRoster`] when omitted.
 */
seeding: SeedingRule, };
