// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { ClassId } from "./ClassId";
import type { GraceWindow } from "./GraceWindow";
import type { SeedingRule } from "./SeedingRule";
import type { StartProcedure } from "./StartProcedure";
import type { WinCondition } from "./WinCondition";

/**
 * The body of `POST /events/{id}/rounds` — everything a caller supplies to add a round (race
 * redesign Slice 2a).
 *
 * The **id is always auto-generated** (a slug of `label` plus a short random suffix), never
 * user-entered — mirroring the event/pilot create rule. The [`seeding`](Self::seeding) defaults to
 * [`SeedingRule::FromRoster`] when omitted. The route returns the created [`RoundDef`] (with its
 * generated [`id`](RoundDef::id)).
 */
export type NewRoundReq = { 
/**
 * The display label for the new round (e.g. `"Qualifying R1"`).
 */
label: string, 
/**
 * The eligible classes this round runs for. Each must be one of the event's selected classes.
 */
classes: Array<ClassId>, 
/**
 * The format this round runs — a known [`FormatRegistry`] name.
 */
format: string, 
/**
 * The format's config knobs, stored verbatim.
 */
params: { [key in string]: string }, 
/**
 * How a heat in this round is won.
 */
win_condition: WinCondition, 
/**
 * How the round's field is seeded; defaults to [`SeedingRule::FromRoster`] when omitted.
 */
seeding: SeedingRule, 
/**
 * How this round assigns channels (race redesign Slice 7a). Optional — **omit it** to take the
 * format's default ([`ChannelMode::default_for_format`]); supply it to override (e.g. force a
 * qual round per-heat). Additive on the wire.
 */
channel_mode?: ChannelMode, 
/**
 * The round's staging timer in seconds (heat-lifecycle Slice 2). Optional — omit for the
 * [`default_staging_timer_secs`] (300). Informational only (no auto-advance).
 */
staging_timer_secs?: number, 
/**
 * The round's start procedure (heat-lifecycle Slice 2). Optional — omit for the
 * [`StartProcedure::default`] randomized 2000–5000ms delay.
 */
start_procedure?: StartProcedure, 
/**
 * The round's grace window (heat-lifecycle Slice 2). Optional — omit for the
 * [`default_grace_window`] (a bounded 3s).
 */
grace_window?: GraceWindow, };
