// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node's **GridFPV-owned** channel (#413, D27) — the twin of [`NodeCalibration`].
 *
 * D27 again: *"GridFPV is the sole system of record for configuration"*, and *"writing to a timer
 * is applying, not storing"*. A channel the RD picks on the Tune page is GridFPV's value; the
 * node's receiver is merely where it takes effect. So an accepted channel write is recorded here,
 * on the [`Timer`], and persisted with it — while the `frequency_mhz` RotorHazard reports back on
 * `GET /timers/{id}/signal` is **evidence about the timer**, never the store.
 *
 * The `band`/`channel` pair is the **friendly name** ([`crate::channels::ChannelCatalogEntry`]),
 * resolved server-side from the shared catalog at accept time and carried onto the emit so
 * RotorHazard's own UI shows `Raceband R7` rather than a bare number. `None` for a **custom** raw
 * MHz the catalog does not know — that is an honest absence, not a name worth inventing.
 */
export type NodeChannel = { 
/**
 * The node's index on the timer, `0`-based (RotorHazard's `seat_index`).
 */
node: number, 
/**
 * The channel's centre frequency in raw MHz — the value the receiver actually tunes.
 */
mhz: number, 
/**
 * The catalog band this channel was picked from (`"Raceband"`), or `None` for a custom MHz.
 */
band?: string, 
/**
 * The catalog channel label within that band (`"R7"`), or `None` for a custom MHz.
 */
channel?: string, };
