// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node's **GridFPV-owned** enter/exit calibration (#355, D27).
 *
 * D27: *"GridFPV is the sole system of record for configuration"* — a threshold the RD sets is
 * GridFPV's value, and the timer is merely where it takes effect. So an accepted calibration write
 * is recorded here, on the [`Timer`], and persisted with it; the level that comes back from the
 * timer on `GET /timers/{id}/signal` is **evidence about the timer**, never the store.
 *
 * Each threshold is independently optional because the console writes only the one the RD actually
 * moved: a node whose exit has been tuned and whose enter has not holds `exit_at: Some, enter_at:
 * None`, which is the truth rather than a fabricated pair.
 */
export type NodeCalibration = { 
/**
 * The node's index on the timer, `0`-based (RotorHazard's `seat_index`).
 */
node: number, 
/**
 * The enter threshold GridFPV has set on this node, or `None` if it never has.
 */
enter_at?: number, 
/**
 * The exit threshold GridFPV has set on this node, or `None` if it never has.
 */
exit_at?: number, };
