// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node's latest readings — the thirteen per-node values the timer reports, and **the** wire
 * definition of them.
 *
 * This is both the crate-boundary twin of the adapter's `NodeTick` (the live socket lives in
 * `gridfpv-app`, *above* this crate, so the registry cannot name the adapter's type — restating
 * the fields here keeps the dependency arrow pointing the right way, and the app crate does the
 * trivial mapping) **and** the flattened body of [`NodeSignal`] on the wire. It is one struct for
 * both jobs on purpose (#461): the two used to be hand-mirrored field lists joined by a
 * field-by-field copy, which is a shape that can silently drift. Now the ingest type and the
 * published type are the same type, so a field added here reaches the console or fails to compile.
 *
 * Everything is `Option` because everything is genuinely optional: a node RotorHazard has not
 * reported yet, a timer whose thresholds have not arrived, a build that omits a readout. A
 * missing value renders as "—", which is information; a zero would be a lie.
 */
export type NodeReading = { 
/**
 * Whether RotorHazard has reported anything at all for this node.
 *
 * **Unseated nodes are included, and this is why.** "Is this node even alive?" is half the
 * diagnostic a mistuned timer needs, and filtering the snapshot to a heat's lineup would
 * answer it with silence for exactly the nodes an RD is most likely to be checking.
 */
seen: boolean, 
/**
 * Live RSSI (filtered ADC counts) at the newest sample.
 */
rssi?: number, 
/**
 * The node's tuned frequency in MHz; `None` when the node is not tuned to anything.
 */
frequency_mhz?: number, 
/**
 * The detector's loop time in microseconds — a timer falling behind shows up here first.
 */
loop_time_micros?: number, 
/**
 * Whether the node is inside a crossing right now.
 */
crossing: boolean, 
/**
 * Whether a crossing was seen at any point in the interval this sample covers — the sticky
 * flag that survives the Director's decimation, so a fast pass still lights the lamp.
 */
crossed_recently: boolean, 
/**
 * The node's running peak RSSI (`node_data.node_peak_rssi`).
 */
node_peak_rssi?: number, 
/**
 * The node's running nadir RSSI (`node_data.node_nadir_rssi`) — the noise floor.
 */
node_nadir_rssi?: number, 
/**
 * Peak RSSI of the most recent pass (`node_data.pass_peak_rssi`).
 */
pass_peak_rssi?: number, 
/**
 * Nadir RSSI of the most recent pass (`node_data.pass_nadir_rssi`).
 */
pass_nadir_rssi?: number, 
/**
 * How many passes this node has detected (`node_data.debug_pass_count`).
 */
pass_count?: number, 
/**
 * The enter threshold the timer is detecting against.
 */
enter_at?: number, 
/**
 * The exit threshold the timer is detecting against.
 */
exit_at?: number, };
