// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A disagreement between what a timer **reported** and what GridFPV is **configured** for (#412).
 *
 * **A notice, never an edit.** D27 and #355's calibration drift settle the rule: a value read back
 * from a timer is evidence about the timer, not an input to a decision. GridFPV shows this and
 * keeps racing on its own config; resolving it is the RD's call.
 *
 * The two directions mean different things. `reported < configured` is the bench bug #412 was
 * filed for — a real 4-node timer configured as 8, which builds an 8-pilot heat that can only time
 * four. `reported > configured` is a timer with capacity GridFPV is not using, which costs
 * nothing but is worth showing.
 */
export type NodeDrift = { 
/**
 * How many nodes the timer said it has.
 */
reported: number, 
/**
 * The width GridFPV is using ([`Timer::node_width`]).
 */
configured: number, 
/**
 * The **enabled** node indices (0-based) at or beyond `reported` — seats GridFPV would fill
 * that the hardware does not have. These are the ones that lose laps: a pilot seated here
 * flies a heat that records nothing.
 */
enabled_beyond_reported: Array<number>, };
