// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";

/**
 * One node's live signal, as a Tune page reads it (#355).
 *
 * Everything is `Option` because everything is genuinely optional: a node RotorHazard has not
 * reported yet, a timer whose thresholds have not arrived, a build that omits a readout. A
 * missing value renders as "—", which is information; a zero would be a lie.
 */
export type NodeSignal = { 
/**
 * The node's index on the timer, `0`-based. The **display** name is built from this plus the
 * channel (`Node 1 · Raceband R7`) — see the repo display rule.
 */
node: number, 
/**
 * The stable per-node competitor handle (`node-0`, `node-1`, …) the rest of GridFPV uses for
 * a seat. A wire handle, not a label.
 */
seat: CompetitorRef, 
/**
 * Whether RotorHazard has reported anything at all for this node.
 *
 * **Unseated nodes are included, and this is why.** "Is this node even alive?" is half the
 * diagnostic a mistuned timer needs, and filtering the snapshot to a heat's lineup would
 * answer it with silence for exactly the nodes an RD is most likely to be checking.
 */
seen: boolean, 
/**
 * Live RSSI (filtered ADC counts) at the newest sample.
 */
rssi?: number, 
/**
 * The node's tuned frequency in MHz; `None` when the node is not tuned to anything.
 */
frequency_mhz?: number, 
/**
 * The detector's loop time in microseconds — a timer falling behind shows up here first.
 */
loop_time_micros?: number, 
/**
 * Whether the node is inside a crossing right now.
 */
crossing: boolean, 
/**
 * Whether a crossing was seen at any point in the interval this sample covers — the sticky
 * flag that survives the Director's decimation, so a fast pass still lights the lamp.
 */
crossed_recently: boolean, 
/**
 * The node's running peak RSSI (`node_data.node_peak_rssi`).
 */
node_peak_rssi?: number, 
/**
 * The node's running nadir RSSI (`node_data.node_nadir_rssi`) — the noise floor.
 */
node_nadir_rssi?: number, 
/**
 * Peak RSSI of the most recent pass (`node_data.pass_peak_rssi`).
 */
pass_peak_rssi?: number, 
/**
 * Nadir RSSI of the most recent pass (`node_data.pass_nadir_rssi`).
 */
pass_nadir_rssi?: number, 
/**
 * How many passes this node has detected (`node_data.debug_pass_count`).
 */
pass_count?: number, 
/**
 * The enter threshold the timer is detecting against.
 */
enter_at?: number, 
/**
 * The exit threshold the timer is detecting against.
 */
exit_at?: number, 
/**
 * The rolling RSSI window, **oldest first**, one value per entry in
 * [`TimerSignal::sample_micros`]. At most [`SIGNAL_RING`] long, always.
 */
samples: Array<number>, };
