// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An edit to an **optional** field that distinguishes *clear it* from *leave it unchanged*
 * (issue #74).
 *
 * In `PUT /pilots/{id}` an absent field means "leave unchanged"; a present field means "apply
 * this", where the value can itself be `null` to **clear** the stored value. Wrapping each
 * optional edit in this type makes that two-level optionality explicit (`Option<OptionalEdit<T>>`:
 * the outer `Option` is absent/present, the inner is the new value or `null`). On the TS side it
 * is just `T | null`.
 */
export type OptionalEdit<T> = T | null;
