// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The **kind** of a format parameter (race redesign Slice 7a) — how a UI renders / validates it.
 *
 * A `number` is a free integer/decimal input; an `enum` is a fixed choice from
 * [`options`](FormatParam::options); a `bool` is a toggle. Externally tagged so it maps to a TS
 * discriminated-union-friendly string literal. Derives serde + `ts_rs::TS`.
 */
export type ParamKind = "number" | "enum" | "bool";
