// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";
import type { GateIndex } from "./GateIndex";
import type { SignalContext } from "./SignalContext";
import type { SourceTime } from "./SourceTime";

/**
 * A gate crossing — the one observation everything else derives from.
 */
export type Pass = { 
/**
 * Which timing source produced this pass.
 */
adapter: AdapterId, 
/**
 * The source's own competitor handle.
 */
competitor: CompetitorRef, 
/**
 * When the crossing happened, in the source's clock.
 */
at: SourceTime, 
/**
 * A source-provided monotonic sequence number, where one exists. Disambiguates
 * passes that share a timestamp and survives clock adjustments; also the basis
 * for reconnect deduplication.
 */
sequence?: number, 
/**
 * The gate crossed; defaults to the lap gate.
 */
gate?: GateIndex, 
/**
 * Optional signal context (hardware only).
 */
signal?: SignalContext, };
