// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A marshaling penalty applied to a competitor in a heat (marshaling.html §3.3 — the
 * adjudication framework: DQ, penalty time *and* points, richer than RotorHazard's
 * `+time`/note model).
 *
 * The variants split by **where they land**:
 * - [`Disqualify`](Penalty::Disqualify) and [`TimeAdded`](Penalty::TimeAdded) reshape the
 *   **per-heat** lap/time result (the heat scorer, `gridfpv_engine::scoring`): a DQ sinks a
 *   competitor below the field, a time penalty worsens their deciding time.
 * - [`PointsDeducted`](Penalty::PointsDeducted) / [`PointsAdded`](Penalty::PointsAdded) do
 *   **not** touch the per-heat lap result — they adjust the competitor's **season / event
 *   standings** points, folded by the standings projection
 *   (`gridfpv_server::round_engine::class_standings`), leaving the heat's lap/time/DQ intact.
 *
 * All variants are reversible via [`RulingReversed`](Event::RulingReversed) and read back on a
 * legacy log (the enum is externally tagged, so the new variants are purely additive).
 *
 * # Legacy `Disqualify` compatibility
 *
 * Adding the optional `reason` made [`Disqualify`](Penalty::Disqualify) a *struct* variant,
 * which serde would otherwise serialise as `{"Disqualify":{}}` and refuse to read from the
 * legacy bare string `"Disqualify"`. A hand-written [`Deserialize`] (see the impl below) accepts
 * **both** the legacy bare `"Disqualify"` and the struct form, and [`Serialize`] keeps emitting
 * the compact bare `"Disqualify"` when there is no reason — so old logs round-trip byte-for-byte
 * and a reason-less DQ stays on the wire exactly as before.
 */
export type Penalty = { "Disqualify": { 
/**
 * Why the competitor was disqualified (e.g. "cut the course", "unsafe flying"). `None`
 * when no reason was recorded — the common quick-DQ, and the legacy shape. (`Penalty`
 * hand-rolls serde — see the impls below — so the optional/skip behaviour lives there;
 * `#[ts(optional)]` keeps the generated TS field `reason?:`.)
 */
reason?: string, } } | { "TimeAdded": { micros: number, } } | { "PointsDeducted": { 
/**
 * How many standings points to subtract (saturating at zero).
 */
points: number, } } | { "PointsAdded": { 
/**
 * How many standings points to add.
 */
points: number, } };
