// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A marshaling penalty applied to a competitor in a heat.
 */
export type Penalty = "Disqualify" | { "TimeAdded": { micros: bigint, } };
