// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotId } from "./PilotId";
import type { VtxType } from "./VtxType";

/**
 * One pilot in the application-level directory (issue #74).
 *
 * The wire shape `GET /pilots` returns and the on-disk shape `pilots.json` persists: a stable
 * [`PilotId`] (auto-generated, never user-entered), a required `callsign`, and a little optional
 * metadata. The optional fields are all omitted from the wire when unset (`skip_serializing_if`)
 * so an entry with just a callsign serialises to a two-field object. Derives serde (its JSON *is*
 * both the wire and the persisted form) and `ts_rs::TS` so the frontend reads a generated `Pilot`
 * type.
 *
 * # Directory fields (a survey of RotorHazard / MultiGP / FPVScores, #74/#120)
 *
 * Beyond the core callsign + cloud-pull ids, the directory carries a small set of
 * **display/organizer** fields those systems converge on: a [`phonetic`](Pilot::phonetic)
 * pronunciation hint for voice callouts (RotorHazard), a [`team`](Pilot::team) / club name, a
 * [`color`](Pilot::color) for overlays/leaderboards, and a [`country`](Pilot::country) code. The
 * open [`attributes`](Pilot::attributes) bag then captures whatever event/region-specific data
 * (insurance #, FAA/FCC license, bib, sponsor, …) an organizer needs without us hardcoding a
 * column per use.
 */
export type Pilot = { 
/**
 * The stable handle a roster references and the API addresses (`PUT /pilots/{id}`). The same
 * [`PilotId`] the log's registration binding uses — directory and log never disagree on what a
 * pilot id is.
 */
id: PilotId, 
/**
 * The pilot's **callsign** — the required display handle (their racing name). The directory's
 * one mandatory field; everything else is optional metadata.
 */
callsign: string, 
/**
 * The pilot's real / full name, if recorded. Omitted from the wire when unset.
 */
name?: string, 
/**
 * A **pronunciation hint** for the callsign, for voice callouts (RotorHazard carries this).
 * Free-form (e.g. `"AK-ro AYS"`). Omitted from the wire when unset.
 */
phonetic?: string, 
/**
 * The pilot's **team / club** name, if recorded. Free-form. Omitted from the wire when unset.
 */
team?: string, 
/**
 * A **hex color** `#RRGGBB` for overlays / leaderboards, if recorded. Stored as a plain
 * (normalized) string and lightly validated on create/update. Omitted from the wire when unset.
 */
color?: string, 
/**
 * The pilot's **country** as an ISO 3166-1 alpha-2 code (e.g. `US`, `GB`), if recorded. The
 * **code only** — flags/names derive from it in the UI. Stored uppercase, lightly validated.
 * Omitted from the wire when unset.
 */
country?: string, 
/**
 * The pilot's video-transmitter type, if recorded (see [`VtxType`]). Omitted when unset.
 */
vtx_type?: VtxType, 
/**
 * The pilot's **MultiGP** pilot id, if known — a forward hook for a later cloud-pull import
 * (#74). A free-form string. Omitted from the wire when unset.
 */
multigp_id?: string, 
/**
 * The pilot's **Velocidrone** id, if known — a forward hook for matching a Velocidrone racer
 * (#74). A free-form string. Omitted from the wire when unset.
 */
velocidrone_id?: string, 
/**
 * An **open custom-attributes** bag (insurance #, FAA/FCC license, bib, sponsor, …) so an
 * organizer can capture event/region-specific data without us hardcoding a field per use.
 * Keys are trimmed and non-empty; serializes to TS `Record<string, string>`. Defaults empty
 * (and, being a `BTreeMap`, an empty bag still serializes to `{}` — there is no `skip`).
 */
attributes: { [key in string]: string }, };
