// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GridFPV pilot's stable, event-scoped identity — the racer a source-local
 * [`CompetitorRef`] is *bound* to by a registration action (Architecture §9), never by
 * the adapter. For a basic race this is the pilot's callsign / stable id; richer pilot
 * metadata (display name, team, avatar) can layer on later.
 *
 * This is the canonical pilot handle the whole stack shares: the event model records
 * the binding ([`Event::CompetitorRegistered`]) and the wire/scope layer addresses a
 * pilot by the same type, so the log and the protocol never disagree on what a pilot id
 * is.
 */
export type PilotId = string;
