// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";

/**
 * One active pilot's live progress in the current heat (protocol.html §1).
 *
 * Derived from the heat's lap projection: the number of laps completed so far and the
 * duration of the most recent completed lap (the live "last lap" an overlay shows).
 * Splits are a later refinement; the lap-count + last-lap pair is the live core.
 */
export type PilotProgress = { 
/**
 * The source-local competitor this progress is for (a member of the lineup).
 */
competitor: CompetitorRef, 
/**
 * Completed laps so far in the heat.
 */
laps_completed: number, 
/**
 * Duration (µs, source clock) of the most recently completed lap, or `None` before
 * the pilot has completed a lap.
 */
last_lap_micros?: bigint, };
