// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a **pilot** across an event (protocol.html §4 "Pilot scope") — a racer
 * following their own laps, results, and next heat.
 *
 * This is the event-scoped pilot handle a scope addresses, distinct from the
 * per-source [`CompetitorRef`](gridfpv_events::CompetitorRef) the timer reports: a
 * pilot is bound to source competitors by a registration action (Architecture §9),
 * which is out of scope here.
 */
export type PilotId = string;
