// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotId } from "./PilotId";
import type { VtxType } from "./VtxType";

/**
 * One pilot in the application-level directory (issue #74).
 *
 * The wire shape `GET /pilots` returns and the on-disk shape `pilots.json` persists: a stable
 * [`PilotId`] (auto-generated, never user-entered), a required `callsign`, and a little optional
 * metadata. The optional fields are all omitted from the wire when unset (`skip_serializing_if`)
 * so an entry with just a callsign serialises to a two-field object. Derives serde (its JSON *is*
 * both the wire and the persisted form) and `ts_rs::TS` so the frontend reads a generated `Pilot`
 * type.
 */
export type Pilot = { 
/**
 * The stable handle a roster references and the API addresses (`PUT /pilots/{id}`). The same
 * [`PilotId`] the log's registration binding uses — directory and log never disagree on what a
 * pilot id is.
 */
id: PilotId, 
/**
 * The pilot's **callsign** — the required display handle (their racing name). The directory's
 * one mandatory field; everything else is optional metadata.
 */
callsign: string, 
/**
 * The pilot's real / full name, if recorded. Omitted from the wire when unset.
 */
name?: string, 
/**
 * The pilot's video-transmitter type, if recorded (see [`VtxType`]). Omitted when unset.
 */
vtx_type?: VtxType, 
/**
 * The pilot's **MultiGP** pilot id, if known — a forward hook for a later cloud-pull import
 * (#74). A free-form string. Omitted from the wire when unset.
 */
multigp_id?: string, 
/**
 * The pilot's **Velocidrone** id, if known — a forward hook for matching a Velocidrone racer
 * (#74). A free-form string. Omitted from the wire when unset.
 */
velocidrone_id?: string, };
