// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorKey } from "./CompetitorKey";
import type { Metric } from "./Metric";

/**
 * One competitor's place in a scored heat.
 *
 * `position` is **1-based and dense at the top but tie-aware**: tied competitors
 * share the same `position`, and the next distinct competitor's `position` skips
 * past them (standard "1, 2, 2, 4" competition ranking). `laps` is the number of
 * laps that counted under the win condition (for [`WinCondition::Timed`] that is
 * the number inside the window, not the raw laps flown). `metric` carries the
 * condition-specific deciding value for display / debugging.
 */
export type Placement = { 
/**
 * Which source-local competitor this placement is for.
 */
competitor: CompetitorKey, 
/**
 * 1-based finishing position; tied competitors share a position.
 */
position: number, 
/**
 * Laps that counted under the win condition.
 */
laps: number, 
/**
 * The condition-specific deciding metric for this competitor.
 */
metric: Metric, 
/**
 * The competitor's **fastest single completed lap** in this heat, in microseconds, or
 * `None` if they completed no timed lap. Computed from the run's lap durations
 * **independently of the win condition** (so e.g. a [`WinCondition::FirstToLaps`]
 * placement still carries a real best-lap, not the win metric), with thrown-out laps
 * excluded. Cross-heat rankings use it to break ties — round-robin breaks pilots equal
 * on points by their faster best lap. Defaults to `None` so older snapshots that
 * predate the field still deserialise.
 */
best_lap_micros: number | null, 
/**
 * Whether this competitor was **disqualified** by an adjudication
 * ([`gridfpv_events::Penalty::Disqualify`] via
 * [`gridfpv_events::Event::PenaltyApplied`]). A disqualified competitor is ranked
 * **after every non-disqualified competitor**, regardless of their on-track result
 * (see [`score_with_adjudications`]). Defaults to `false` and is omitted from the
 * wire when false, so clean results carry no extra bytes.
 */
disqualified?: boolean, };
