// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a connected RotorHazard timer carries the **GridFPV plugin** (RH plugin design D16,
 * Slice 1) — the in-process integration the Director probes for over the existing socket.io
 * connection (`gridfpv_hello` → `gridfpv_hello_ack`). Carried as an `Option` on [`Timer`]:
 * `None` is "not probed" (a Mock timer, or an RH not yet connected). Like [`TimerStatus`] it is a
 * **live, in-memory** value, not persisted (reset to `None` on load and on reconfigure) and
 * **additive on the wire** (`#[ts(optional)]` — an older console still parses a `Timer`). The
 * Director uses it to drive the required-with-guided-install UX (§5): `Missing` and `Incompatible`
 * surface the one-step install; `Present` surfaces a healthy timer.
 */
export type PluginPresence = "Missing" | { "Present": { 
/**
 * The plugin build version (e.g. `"0.1.0"`).
 */
plugin_version: string, 
/**
 * The RHAPI version the plugin reported (e.g. `"1.4"`).
 */
rhapi_version: string, 
/**
 * The capabilities the plugin declared (e.g. `["hello"]`).
 */
capabilities: Array<string>, } } | { "Incompatible": { 
/**
 * The plugin build version, so the UI can name the mismatch.
 */
plugin_version: string, 
/**
 * The plugin's `gridfpv_*` protocol version (the field that didn't match).
 */
protocol_version: number, 
/**
 * A short plain-language reason for the mismatch.
 */
reason: string, } };
