// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditEntry } from "./AuditEntry";
import type { EventOutcome } from "./EventOutcome";
import type { HeatResult } from "./HeatResult";
import type { LapList } from "./LapList";
import type { LiveRaceState } from "./LiveRaceState";
import type { RankEntry } from "./RankEntry";
import type { SignalTraceView } from "./SignalTraceView";

/**
 * A served projection **with its value** (protocol.html §1) — the closed set of
 * projection shapes the contract carries, each reusing the existing projection/engine
 * output type. Externally tagged, so it maps to a TS discriminated union keyed by
 * projection kind.
 *
 * This is the body of a [`Snapshot`] and of a fresh-value
 * [`ChangeEnvelope`](crate::stream::ChangeEnvelope). Adding a new served projection is
 * an additive variant (§7); an older client ignores a kind it does not understand.
 */
export type ProjectionBody = { "LiveRaceState": LiveRaceState } | { "LapList": LapList } | { "HeatResult": HeatResult } | { "Ranking": Array<RankEntry> } | { "EventOutcome": EventOutcome } | { "MarshalingAudit": Array<AuditEntry> } | { "SignalTrace": SignalTraceView };
