// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which projection a snapshot body or change envelope is *about* — the bare
 * discriminant with no payload (protocol.html §3).
 *
 * A fresh-value envelope carries the whole [`ProjectionBody`] (kind *and* value); a
 * delta envelope carries this `ProjectionKind` plus an opaque delta, naming the
 * projection it advances without re-sending it. Keeping the kind separate from the
 * body lets a delta name its target cheaply.
 */
export type ProjectionKind = "LiveRaceState" | "LapList" | "HeatResult" | "Ranking" | "EventOutcome";
