// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The **protest window** for the provisional → official lifecycle (marshaling Slice 5,
 * marshaling.html §3.3): an optional, OFF-by-default **auto-official timer**.
 *
 * A heat sits in [`Unofficial`](HeatState::Unofficial) (provisional, correctable) after the race
 * closes. When a protest window is configured, the runtime **auto-finalizes** it
 * (`Unofficial → Final`) once the window elapses from the race-end instant; the RD can always
 * finalize early (manually) or correct during the window, and [`Revert`](HeatCommand::Revert)
 * re-opens a finalized result. This is **not** a gate that blocks `Finalize` — it is an additive
 * auto-finalize. The default ([`Off`](Self::Off)) is today's behaviour: manual `Finalize` only.
 *
 * Derives serde + `ts_rs::TS` so it can be carried as a per-round config
 * ([`RoundDef::protest_window`](../../server/events/struct.RoundDef.html)) and read by the
 * frontend; it mirrors [`GraceWindow`]'s shape (an off variant + a bounded duration).
 */
export type ProtestWindow = "Off" | { "After": { 
/**
 * Length of the protest window, in microseconds (server wall clock), counted from the
 * `Running → Unofficial` race-end instant.
 */
micros: number, } };
