// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * The one error shape every protocol surface returns (protocol.html §9.8).
 *
 * Carried in an HTTP error body, a WS error frame, and a failed
 * [`CommandAck`](crate::control::CommandAck) alike. `code` is the branchable
 * category; `message` is the human-readable detail for logs and the RD console.
 */
export type ProtocolError = { 
/**
 * The machine-readable error category.
 */
code: ErrorCode, 
/**
 * A human-readable description of what went wrong.
 */
message: string, };
