// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a [`ProtestFiled`](Event::ProtestFiled) was resolved (marshaling.html §3.3). A small,
 * closed enum recorded by [`ProtestResolved`](Event::ProtestResolved); externally tagged on the
 * wire like the rest of the event vocabulary, so it maps to a TS string union.
 */
export type ProtestOutcome = "Upheld" | "Denied" | "Withdrawn";
