// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";

/**
 * One competitor's place in a generator's overall ranking.
 *
 * `position` is **1-based and tie-aware** with the same "competition ranking"
 * convention as [`crate::scoring::Placement`]: tied competitors share a `position`
 * and the next distinct entry skips past them (1, 2, 2, 4). Entries are returned in
 * ranking order (best first), with a total, deterministic tie-break so the order is
 * stable across runs.
 */
export type RankEntry = { 
/**
 * The competitor this entry ranks.
 */
competitor: CompetitorRef, 
/**
 * 1-based overall position; tied competitors share a position.
 */
position: number, };
