// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The **win-condition metric** a round's standings are ranked by — the tagged mirror of the
 * round's [`win_condition`](RoundDef::win_condition), carrying the value the ranking is *by*.
 *
 * This is the headline number the Rounds stage shows next to each pilot: the fastest single lap
 * ([`BestLap`](RoundMetric::BestLap)), the fastest N-consecutive-lap window
 * ([`BestConsecutive`](RoundMetric::BestConsecutive)), or the most laps banked
 * ([`MostLaps`](RoundMetric::MostLaps)) — mapped from the win condition exactly as
 * [`qual_metric_for`] derives the qualifying metric. The lap-time variants carry `None` for a
 * pilot who set no qualifying value (no lap / fewer than `n` laps), so a no-show still renders.
 */
export type RoundMetric = { "BestLap": { 
/**
 * Fastest single lap (µs), or `None` for no completed lap.
 */
micros: number | null, } } | { "BestConsecutive": { 
/**
 * How many consecutive laps the window spans.
 */
n: number, 
/**
 * Smallest consecutive-window sum (µs), or `None` if fewer than `n` laps.
 */
micros: number | null, } } | { "MostLaps": { 
/**
 * Most laps in a heat (0 if the pilot completed no lap).
 */
laps: number, } };
