// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies a **round** within a class's schedule — one pass through the phase
 * (qualifying round 1, round 2, …). A transparent string newtype like [`ClassId`];
 * the richer phase/round model lands with the scheduler, this is the stable handle a
 * scheduled heat is tagged with.
 */
export type RoundId = string;
