// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { ClassId } from "./ClassId";
import type { GraceWindow } from "./GraceWindow";
import type { ProtestWindow } from "./ProtestWindow";
import type { RoundId } from "./RoundId";
import type { SeedingRule } from "./SeedingRule";
import type { StartProcedure } from "./StartProcedure";
import type { WinCondition } from "./WinCondition";

/**
 * One **round** within an event (race redesign Slice 2a): an event-level, class-tagged, *dynamic*
 * format-instance.
 *
 * A round is a *format-instance* — a named, configured run of one
 * [`FormatRegistry`](gridfpv_engine::format::FormatRegistry) format, scoped to the eligible
 * [`classes`](Self::classes) it runs for, with a [`SeedingRule`] deciding how its field is drawn.
 * One eligible class is a **class round** (e.g. "Open Qualifying"); many/all classes is an
 * **open / practice** round. Rounds are added **as-you-go** (practice/quali) rather than
 * precomputed; later slices seed brackets from a prior round's ranking
 * ([`SeedingRule::FromRanking`]).
 *
 * Carried in [`EventMeta::rounds`]. Derives serde (its JSON *is* the wire form) and `ts_rs::TS` so
 * the frontend reads a generated `RoundDef` type (the Rounds UI lands in Slice 2b).
 */
export type RoundDef = { 
/**
 * The stable, **auto-generated** handle for this round (a slug of the [`label`](Self::label)
 * plus a short random suffix — mirroring the event/pilot id-gen). Never user-entered; the
 * label is display-only. Referenced by a later round's [`SeedingRule::FromRanking`].
 */
id: RoundId, 
/**
 * The human-readable label (e.g. `"Qualifying R1"`, `"Open Practice"`). Display-only; the
 * [`id`](Self::id) is authoritative.
 */
label: string, 
/**
 * The eligible [`classes`](EventMeta::classes) this round runs for. One class is a *class
 * round*; many/all is an *open / practice* round. Each must be one of the event's selected
 * classes.
 */
classes: Array<ClassId>, 
/**
 * The format this round runs — a known
 * [`FormatRegistry`](gridfpv_engine::format::FormatRegistry) name (e.g. `"timed_qual"`,
 * `"single_elim"`). Validated against [`FormatRegistry::standard`] on add/update.
 */
format: string, 
/**
 * The format's config knobs (e.g. `rounds`, `advance`, `heat_size`), stored as-is as a
 * string→string map — the same shape a `FormatConfig`'s params take. Stored verbatim with only
 * light validation; format-specific interpretation is the engine's concern when the round runs
 * (a later slice).
 */
params: { [key in string]: string }, 
/**
 * How a heat in this round is won — the per-round scoring rule (the existing wire
 * [`WinCondition`](gridfpv_engine::scoring::WinCondition)).
 *
 * **Open practice does no scoring**, so a win condition is not *required* for an open-practice
 * round: the create/update requests make this field optional ([`NewRoundReq::win_condition`])
 * and an omitted condition stores an inert [`default_win_condition`] here. The field stays a
 * plain [`WinCondition`] (not an `Option`) so every scoring path is unchanged — for a
 * non-open-practice round the stored condition is the one the RD chose; for an open-practice
 * round it is never consulted (the heat ends on the [`time_limit_secs`](Self::time_limit_secs)
 * or the RD's `ForceEnd`).
 */
win_condition: WinCondition, 
/**
 * How this round's field is **seeded** (drawn). Defaults to [`SeedingRule::FromRoster`] (the
 * eligible classes' membership, in roster order); a bracket round seeds from a prior round's
 * ranking ([`SeedingRule::FromRanking`], consumed in a later slice).
 */
seeding: SeedingRule, 
/**
 * How this round assigns **video channels** to its heats (race redesign Slice 7a). A
 * [`ChannelMode::Static`] round (time-trial / qual, GQ-style) uses each member's *fixed*
 * per-membership channel ([`MemberSlot::channel`]) and forms channel-balanced heats; a
 * [`ChannelMode::PerHeat`] round (brackets) assigns channels per heat from the timer's pool
 * (first-fit). Defaulted **by format** on create (`#[serde(default)]` so pre-Slice-7a meta
 * reads back as [`ChannelMode::PerHeat`], the prior behaviour); RD-overridable.
 */
channel_mode: ChannelMode, 
/**
 * The **staging timer** for this round, in seconds (heat-lifecycle Slice 2). *Informational
 * only* — there is **no** auto-advance out of `Staged`; the console displays it as a staging
 * countdown (Slice 3). Defaults to [`default_staging_timer_secs`] (300s = 5 min). Additive
 * (`#[serde(default)]`) so pre-Slice-2 meta reads back with the default.
 */
staging_timer_secs: number, 
/**
 * The **start procedure** for this round (heat-lifecycle Slice 2) — how the heat auto-advances
 * `Armed → Running`. The runtime picks a randomized delay in the procedure's window once, logs
 * it ([`Event::HeatStarting`](gridfpv_events::Event::HeatStarting)), and fires the transition
 * then. Defaults to a sane randomized delay ([`StartProcedure::default`]). Additive.
 */
start_procedure: StartProcedure, 
/**
 * The **grace window** for late crossings after the win condition is met (heat-lifecycle
 * Slice 2). The runtime holds the heat in `Running` for this long after the race-end criterion
 * before appending the auto `Running → Unofficial`, so trailing pilots' final laps still count.
 * Defaults to [`default_grace_window`] (a bounded few seconds — *not* `UntilScored`, so the
 * auto-completion actually fires). Additive.
 */
grace_window: GraceWindow, 
/**
 * The **protest window** for the provisional → official lifecycle (marshaling Slice 5,
 * marshaling.html §3.3) — an optional, **OFF-by-default auto-official timer**. When set to
 * [`ProtestWindow::After`], the runtime auto-finalizes the heat (`Unofficial → Final`) once the
 * window elapses from the race-end instant; the RD can always finalize early or correct during
 * the window, and `Revert` re-opens a finalized result. The default [`ProtestWindow::Off`] is
 * today's behaviour — **manual `Finalize` only**, nothing auto-finalizes.
 *
 * Per-round so it can vary by phase (e.g. a protest window on the mains, none on practice).
 * Additive (`#[serde(default)]`) so a round persisted before this field reads back as `Off`.
 */
protest_window: ProtestWindow, 
/**
 * The **practice duration** for an open-practice round, in seconds (open-practice refinement).
 * When set, the runtime clock **auto-ends the practice** (`Running → Unofficial`) once the
 * heat's elapsed running time reaches this limit — independent of any win condition (the time is
 * the *only* end condition for an open-practice heat). When unset (`None`), the practice runs
 * until the RD ends it (`ForceEnd`). E.g. `3600` ends a one-hour practice on its own.
 *
 * Additive (`#[serde(default)]`, omitted from the wire when unset) so a round persisted before
 * this field reads back with `None`. Only consulted for an open-practice heat; a normal round
 * keeps ending on its win condition.
 */
time_limit_secs?: number, };
