// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeatId } from "./HeatId";
import type { LayoutId } from "./LayoutId";
import type { RoundId } from "./RoundId";
import type { SeatProblem } from "./SeatProblem";
import type { TimerId } from "./TimerId";

/**
 * One problem found in a **stored** round's configuration, on read (#416).
 *
 * # Why read and not only write
 *
 * #412 refuses an impossible seat at add *and* update, so every round authored since is safe. But
 * nothing re-checked the rounds already on disk — and the rounds already on disk are exactly where
 * the bug lives, because they predate the fix. A stored round is also not static: the RD can
 * disable a node, narrow a timer's width, or swap the event's primary timer, and any of those can
 * make a round that validated cleanly at write time impossible at race time. So the check runs
 * where the RD looks (`GET /events/{id}/round-issues`), against the same
 * [`Timer::node_view`](crate::timers::Timer::node_view) answer `GET /timers/{id}/nodes` serves.
 *
 * Every field a person reads is a **friendly name** — the round's label, the timer's name, the
 * heat's name, the layout's name, the 1-based node label — never a raw id or a bare index (repo
 * display rule). `round` / `node` / `layout` / `heat` are the wire handles the console repairs
 * *through* (they address the round-edit form, the layouts page, the heat), not labels.
 *
 * # Only `round` and `problem` are always there
 *
 * The set has grown past "an impossible seat". A stale-layout problem is about a node *and* a
 * layout; an orphaned heat bind ([`SeatProblem::HeatLayoutNotInRound`]) is about a **heat** and
 * has no node at all, and is not checked against a timer. Rather than fabricate a node index or a
 * timer to fill the struct — the display rule's exact failure mode — the fields that do not apply
 * are simply absent.
 */
export type RoundIssue = { 
/**
 * The round the problem is in — the handle the console's repair action edits.
 */
round: RoundId, 
/**
 * The round's **label**, for display.
 */
round_label: string, 
/**
 * The timer the seat was checked against (the event's effective primary). Absent for a
 * problem that is not about the timer at all (an orphaned heat bind).
 */
timer?: TimerId, 
/**
 * That timer's **name**, for display.
 */
timer_name?: string, 
/**
 * The offending node index, **0-based** — a wire handle (it is what the round's seeding
 * stores), never shown as-is. Absent for a problem that names no single node.
 */
node?: number, 
/**
 * The node's **display name**, 1-based: index `6` is `"Node 7"`.
 */
node_label?: string, 
/**
 * Which case this is — an impossible **seat** (#412/#416), a stale **channel layout**
 * (#117 S3), or a heat still bound to a layout its round dropped.
 */
problem: SeatProblem, 
/**
 * The **channel layout** the problem is in, for the `Layout*` cases — the handle the console's
 * repair action edits. Absent for a seat problem, which is about the round's own seeding, and
 * for [`SeatProblem::HeatLayoutGone`], where the layout no longer exists to name.
 */
layout?: LayoutId, 
/**
 * That layout's **name**, for display — never its [`LayoutId`].
 */
layout_name?: string, 
/**
 * The **heat** the problem is in, for the `HeatLayout*` cases — the handle the console's
 * repair actions (`SetHeatLayout` / `OverrideHeatSeating`) address. Absent otherwise.
 */
heat?: HeatId, 
/**
 * That heat's **name**, for display — resolved through
 * [`round_engine::heat_display_name`](crate::round_engine::heat_display_name), the server-side
 * twin of the console's `heatNameById`, so both surfaces call the heat the same thing. Never
 * its [`HeatId`].
 */
heat_name?: string, 
/**
 * The RD-facing sentence: what is wrong, and what to do about it. Written server-side so the
 * console does not re-derive (and drift from) the explanation.
 */
detail: string, };
