// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { RoundMetric } from "./RoundMetric";

/**
 * One pilot's **per-round standing** for the Rounds stage's time-trial (timed_qual) display.
 *
 * Built by [`round_standings`] for a single round: each pilot's [`position`](RoundStanding::position)
 * (exactly the [`round_ranking`] order, so the standings and the ranking never disagree), their
 * **best single lap** ([`best_lap_micros`](RoundStanding::best_lap_micros), *always* computed so the
 * UI can show a Best-lap column regardless of win condition), their **most laps in a heat**
 * ([`laps`](RoundStanding::laps)), and the win-condition [`metric`](RoundStanding::metric) the
 * ranking is by. Pure + deterministic — the same log + meta always yields the same standings.
 */
export type RoundStanding = { 
/**
 * The competitor this standing is for (the pilot's source-local handle).
 */
competitor: CompetitorRef, 
/**
 * 1-based position; tied competitors share a position with the same dense, tie-aware
 * "1, 2, 2, 4" convention as [`RankEntry`] — and exactly matches [`round_ranking`].
 */
position: number, 
/**
 * The pilot's **best single lap** across the round's heats, in microseconds, or `None` when
 * they completed no lap. *Always* computed (independent of the win condition) so a Best-lap
 * column can sit alongside the ranking metric.
 */
best_lap_micros: number | null, 
/**
 * The most laps the pilot banked in any single heat (under the round's win condition) — the
 * most-laps metric value and lap-count context. `0` for a pilot who completed no lap.
 */
laps: number, 
/**
 * The win-condition metric the ranking is *by* (the tagged mirror of the round's win
 * condition). `best_lap_micros` is always present alongside this.
 */
metric: RoundMetric, };
