// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { RoundId } from "./RoundId";
import type { SeedingRule } from "./SeedingRule";
import type { WinCondition } from "./WinCondition";

/**
 * One **round** within an event (race redesign Slice 2a): an event-level, class-tagged, *dynamic*
 * format-instance.
 *
 * A round is a *format-instance* — a named, configured run of one
 * [`FormatRegistry`](gridfpv_engine::format::FormatRegistry) format, scoped to the eligible
 * [`classes`](Self::classes) it runs for, with a [`SeedingRule`] deciding how its field is drawn.
 * One eligible class is a **class round** (e.g. "Open Qualifying"); many/all classes is an
 * **open / practice** round. Rounds are added **as-you-go** (practice/quali) rather than
 * precomputed; later slices seed brackets from a prior round's ranking
 * ([`SeedingRule::FromRanking`]).
 *
 * Carried in [`EventMeta::rounds`]. Derives serde (its JSON *is* the wire form) and `ts_rs::TS` so
 * the frontend reads a generated `RoundDef` type (the Rounds UI lands in Slice 2b).
 */
export type RoundDef = { 
/**
 * The stable, **auto-generated** handle for this round (a slug of the [`label`](Self::label)
 * plus a short random suffix — mirroring the event/pilot id-gen). Never user-entered; the
 * label is display-only. Referenced by a later round's [`SeedingRule::FromRanking`].
 */
id: RoundId, 
/**
 * The human-readable label (e.g. `"Qualifying R1"`, `"Open Practice"`). Display-only; the
 * [`id`](Self::id) is authoritative.
 */
label: string, 
/**
 * The eligible [`classes`](EventMeta::classes) this round runs for. One class is a *class
 * round*; many/all is an *open / practice* round. Each must be one of the event's selected
 * classes.
 */
classes: Array<ClassId>, 
/**
 * The format this round runs — a known
 * [`FormatRegistry`](gridfpv_engine::format::FormatRegistry) name (e.g. `"timed_qual"`,
 * `"single_elim"`). Validated against [`FormatRegistry::standard`] on add/update.
 */
format: string, 
/**
 * The format's config knobs (e.g. `rounds`, `advance`, `heat_size`), stored as-is as a
 * string→string map — the same shape a `FormatConfig`'s params take. Stored verbatim with only
 * light validation; format-specific interpretation is the engine's concern when the round runs
 * (a later slice).
 */
params: { [key in string]: string }, 
/**
 * How a heat in this round is won — the per-round scoring rule (the existing wire
 * [`WinCondition`](gridfpv_engine::scoring::WinCondition)).
 */
win_condition: WinCondition, 
/**
 * How this round's field is **seeded** (drawn). Defaults to [`SeedingRule::FromRoster`] (the
 * eligible classes' membership, in roster order); a bracket round seeds from a prior round's
 * ranking ([`SeedingRule::FromRanking`], consumed in a later slice).
 */
seeding: SeedingRule, };
