// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";
import type { HeatId } from "./HeatId";

/**
 * A heat a command **created**, identified for the caller (#395).
 */
export type ScheduledHeat = { 
/**
 * The heat's id — a **wire handle**, for addressing it in follow-up commands. Never shown
 * to a user; [`name`](Self::name) is what a message prints (repo display rule).
 */
heat: HeatId, 
/**
 * The heat's **friendly display name** ("Test Round Heat 1", "A-Main", "Practice Heat"),
 * resolved server-side by the same convention the console uses.
 */
name: string, 
/**
 * Who is racing in it, in the generator's seeding order.
 */
lineup: Array<CompetitorRef>, 
/**
 * The per-pilot channel assignment in raw MHz, as logged on the heat. Empty when the round
 * assigns none (open practice, or no timer channels to hand out).
 */
frequencies?: Array<[CompetitorRef, number]>, };
