// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";
import type { EventId } from "./EventId";
import type { HeatId } from "./HeatId";
import type { PilotId } from "./PilotId";

/**
 * What a subscription addresses (protocol.html §4): one of the four resources a
 * client can scope to. Externally tagged like the event model, so it maps to a TS
 * discriminated union.
 *
 * Scopes compose and a client may hold several at once over one connection (§4); a
 * multi-scope subscribe is a list of these. The richer filter grammar (§9.6) is
 * deferred — this fixes the addressable *resources*, which is what later issues build
 * the grammar over.
 */
export type Scope = { "Event": { 
/**
 * The event addressed.
 */
event: EventId, } } | { "Class": { 
/**
 * The event the class belongs to.
 */
event: EventId, 
/**
 * The class addressed.
 */
class: ClassId, } } | { "Heat": { 
/**
 * The heat addressed (the id it carries in the log).
 */
heat: HeatId, } } | { "Pilot": { 
/**
 * The event the pilot is racing in.
 */
event: EventId, 
/**
 * The pilot addressed.
 */
pilot: PilotId, } };
