// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is wrong with a **stored** round's channel configuration, found on read (#412 / #416 /
 * #117 S3).
 *
 * The original three cases are about a `node-{i}` **seat that cannot record a lap**: an
 * open-practice round's field *is* its active nodes, laid out as `node-{i}` seats
 * ([`SeedingRule::ActiveNodes`], whose entries are **node indices**). A seat naming a node the
 * timer does not have, or one the RD switched off, is a pilot on a dead gate: the heat runs, the
 * clock counts, and nothing is ever detected. Silently rendering that seat is the worst available
 * behaviour, so it is surfaced on **read** as well as refused on write.
 *
 * The `Layout*` cases extend the same idea to a stored [`ChannelLayout`] that has gone stale, and
 * the `HeatLayout*` cases to a **heat still bound to a layout its round no longer names**. One
 * enum and one read (`GET /events/{id}/round-issues`) on purpose: #412, #416 and #117 S3 all
 * landed on *validate stored config on read*, and a second mechanism is how two answers to one
 * question start disagreeing.
 */
export type SeatProblem = "NoSuchNode" | "Disabled" | "NotOnTimer" | "LayoutNodeUntuned" | "LayoutNodeGone" | "LayoutChannelNotAllowed" | "HeatLayoutNotInRound" | "HeatLayoutGone";
