// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a stored round's `node-{i}` seat **cannot record a lap** (#412 / #416).
 *
 * An open-practice round's field *is* its active channels, laid out as `node-{i}` seats
 * ([`SeedingRule::AllChannels`], whose entries are **node indices**). A seat naming a node the
 * timer does not have, or one the RD switched off, is a pilot on a dead gate: the heat runs, the
 * clock counts, and nothing is ever detected. Silently rendering that seat is the worst available
 * behaviour, so it is surfaced on **read** as well as refused on write.
 */
export type SeatProblem = "NoSuchNode" | "Disabled" | "NotOnTimer";
