// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundId } from "./RoundId";

/**
 * How a [`RoundDef`]'s field is **seeded** (race redesign Slice 2a).
 *
 * A round either draws its field straight from the eligible classes' roster membership
 * ([`FromRoster`](Self::FromRoster) — practice / first qualifying), or from a **prior round's
 * ranking** ([`FromRanking`](Self::FromRanking) — the bracket / cut case, the issue-#84 carry that
 * a later slice consumes), or — for the casual **open-practice** format — from a set of active
 * **timer nodes** ([`ActiveNodes`](Self::ActiveNodes)) rather than pilots. Derives serde +
 * `ts_rs::TS`.
 */
export type SeedingRule = "FromRoster" | { "FromRanking": { 
/**
 * The prior rounds this round seeds from — each must exist in [`EventMeta::rounds`].
 * Aggregated best-per-pilot when more than one is named. Always at least one entry.
 */
source_rounds: Array<RoundId>, 
/**
 * How many of the aggregated ranking's top places advance into this round.
 */
top_n: number, } } | { "FromHeatWinners": { 
/**
 * The prior bracket-level round whose heat winners seed this round — must exist in
 * [`EventMeta::rounds`].
 */
source_round: RoundId, } } | { "FromRankingRange": { 
/**
 * The prior rounds this round seeds from — each must exist in [`EventMeta::rounds`].
 * Aggregated best-per-pilot when more than one is named. Always at least one entry.
 */
source_rounds: Array<RoundId>, 
/**
 * How many of the aggregated ranking's leading places to **skip** before taking — the
 * 0-based start of the window (seed 13 is `skip: 12`).
 */
skip: number, 
/**
 * How many places to take after the skip — the window width. Must be `> 0`.
 */
take: number, } } | { "Combine": { 
/**
 * The sub-rules whose fields are concatenated (in order) then de-duplicated first-wins.
 * Each is resolved exactly as a standalone seeding rule. Always at least one entry.
 */
sources: Array<SeedingRule>, } } | { "ActiveNodes": { 
/**
 * The active **node indices** (the timer-seat indices the RD made live), laid out as
 * `node-{i}` competitor refs by the field builder, in this order. These are seats on the
 * timer, never frequencies — what a seat is *tuned to* comes from the round's
 * [`ChannelLayout`].
 */
nodes: Array<number>, } };
