// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundId } from "./RoundId";

/**
 * How a [`RoundDef`]'s field is **seeded** (race redesign Slice 2a).
 *
 * A round either draws its field straight from the eligible classes' roster membership
 * ([`FromRoster`](Self::FromRoster) — practice / first qualifying), or from a **prior round's
 * ranking** ([`FromRanking`](Self::FromRanking) — the bracket / cut case, the issue-#84 carry that
 * a later slice consumes). Derives serde + `ts_rs::TS`.
 */
export type SeedingRule = "FromRoster" | { "FromRanking": { 
/**
 * The prior round this round seeds from — must exist in [`EventMeta::rounds`].
 */
source_round: RoundId, 
/**
 * How many of the source ranking's top places advance into this round.
 */
top_n: number, } };
