// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractVersion } from "./ContractVersion";

/**
 * The server's reply to a [`Hello`] (protocol.html §7).
 *
 * The server "states the version(s) it serves" as an inclusive band
 * `[min_contract_version, max_contract_version]`. A client whose
 * [`Hello::contract_version`] falls inside the band is served; one that falls
 * outside gets `compatible = false` — the explicit "too old / too new, please
 * refresh" signal — rather than malformed data.
 */
export type ServerHello = { 
/**
 * The oldest contract version this server still serves (inclusive).
 */
min_contract_version: ContractVersion, 
/**
 * The newest contract version this server serves (inclusive).
 */
max_contract_version: ContractVersion, 
/**
 * Whether the client's announced version falls within the served band. `false`
 * is the "please refresh" signal (the client is too old or too new to be served).
 */
compatible: boolean, };
