// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source's own race/heat identifier, where it exposes one.
 */
export type SessionId = string;
