// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";

/**
 * The body of `PUT /active-event` — the id of the event to make the Director's active one
 * (issue #90). The id must name a known event, else a typed 404 (`UnknownScope`).
 */
export type SetActiveEventRequest = { 
/**
 * The event to make active.
 */
id: EventId, };
