// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerNode } from "./LayerNode";

/**
 * The body of `PUT /events/{id}/layers/{layer_id}` — replace a layer's editable fields (#117 S2).
 *
 * The [`LayerId`] is fixed (it is the path segment); the name and the whole mapping are replaced
 * wholesale, and re-validated exactly as on create.
 */
export type SetChannelLayerRequest = { 
/**
 * The layer's display name. Trimmed; must be non-empty and unique within the event.
 */
name: string, 
/**
 * The complete node → channel mapping (one entry per enabled node, no duplicate channels).
 */
nodes: Array<LayerNode>, };
