// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberSlot } from "./MemberSlot";

/**
 * The body of `PUT /events/{id}/classes/{class}/membership` — the roster pilot ids that race a
 * single class (race redesign Slice 1a). The `class` is the path segment; each id here must name
 * a pilot in the [`PilotDirectory`](crate::pilots::PilotDirectory), else a typed 404. An empty
 * list clears the class's membership.
 */
export type SetClassMembershipRequest = { 
/**
 * The roster pilots that race this class, in selection order, **each with an optional assigned
 * channel** (race redesign Slice 7a). Each must name a known pilot; each set
 * [`channel`](MemberSlot::channel) must be one of the event's **primary timer**'s
 * `available_channels` (which may exceed the timer's `node_count`).
 *
 * **Legacy-compatible:** an element may be a bare pilot-id string (the pre-Slice-7a wire shape),
 * read as a channel-less slot — so an old client / persisted body still sets membership.
 */
pilots: Array<MemberSlot>, };
