// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `PUT /classes/{id}/hidden` — the new visibility for a class (hide/archive classes).
 *
 * A one-field body: `hidden: true` tucks the class away from the per-event picker, `false` brings
 * it back. Applies to **built-in** and custom classes alike (hiding is a visibility preference, not
 * an edit), so it is valid even on a read-only built-in.
 */
export type SetClassHiddenRequest = { 
/**
 * The desired visibility: `true` → hidden (archived from the picker), `false` → visible.
 */
hidden: boolean, };
