// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotId } from "./PilotId";

/**
 * The body of `PUT /events/{id}/classes/{class}/membership` — the roster pilot ids that race a
 * single class (race redesign Slice 1a). The `class` is the path segment; each id here must name
 * a pilot in the [`PilotDirectory`](crate::pilots::PilotDirectory), else a typed 404. An empty
 * list clears the class's membership.
 */
export type SetClassMembershipRequest = { 
/**
 * The roster pilots that race this class, in selection order. Each must name a known pilot.
 */
pilot_ids: Array<PilotId>, };
