// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PilotId } from "./PilotId";

/**
 * The body of `PUT /events/{id}/roster` — the directory pilot ids that make up an event's
 * roster (issue #74). Each must name a pilot in the application-level
 * [`PilotDirectory`](crate::pilots::PilotDirectory), else a typed 404.
 */
export type SetEventRosterRequest = { 
/**
 * The directory pilots this event rosters, in selection order. Each must name a known pilot.
 */
pilot_ids: Array<PilotId>, };
