// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from "./TimerId";

/**
 * The body of `PUT /events/{id}/timers` — the timer ids an event selects (issue #73).
 */
export type SetEventTimersRequest = { 
/**
 * The timers this event uses, in selection order. Each must name a known timer.
 */
ids: Array<TimerId>, };
