// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassId } from "./ClassId";

/**
 * The body of `PUT /events/{id}/classes` — the directory class ids that make up an event's
 * selection (issue #84). Each must name a class in the application-level
 * [`ClassDirectory`](crate::classes::ClassDirectory), else a typed 404.
 */
export type SetEventClassesRequest = { 
/**
 * The directory classes this event runs, in selection order. Each must name a known class.
 */
ids: Array<ClassId>, };
