// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerId } from "./TimerId";

/**
 * The body of `PUT /events/{id}/primary-timer` — designate which selected timer is the
 * **primary** (issue #112), the rest being alternates. The `id` must be one of the event's
 * currently-selected timers; `null` clears the override (the first selected timer becomes primary).
 */
export type SetPrimaryTimerRequest = { 
/**
 * The timer to make primary, or `null` to clear the override (default to the first selected).
 */
id?: TimerId, };
