// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of `PUT /timers/{id}/nodes` — set a timer's node configuration (#412).
 *
 * Both fields are independently optional, so the console can send exactly the thing the RD
 * changed: flipping one node's checkbox carries `enabled`, and pinning the width carries
 * `node_count`.
 */
export type SetTimerNodesRequest = { 
/**
 * The RD's explicit width override.
 *
 * **Three-valued on purpose**: absent leaves it unchanged, `null` **clears** it (follow
 * whatever the timer reports), and a number pins it. "Go back to trusting the hardware" is a
 * real thing an RD does after a drift notice, and a two-valued field cannot say it.
 */
node_count?: number | null, 
/**
 * The node indices (**0-based**) to leave **enabled**; every other index below the effective
 * width becomes disabled. Absent leaves the enabled set unchanged.
 *
 * Sent as the set the RD wants rather than as a delta so a stale console cannot half-apply an
 * edit. Indices at or beyond the width, and duplicates, are ignored.
 */
enabled?: Array<number>, };
