// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";

/**
 * The **dense, full-fidelity** per-node RSSI history for a heat — the detector's own internal
 * sampling, pulled from RotorHazard's request-driven `current_marshal_data` at heat end
 * (marshaling.html §3.2, the "RSSI fidelity" risk in §4).
 *
 * Unlike the live-streamed [`SignalChunk`] (one aggregate sample per `node_data` heartbeat emit,
 * the *coarse* trace), this is the trace RotorHazard's own marshal page reviews against: every
 * per-tick sample the node recorded, with its **own** sample time. A signal-capable adapter pulls
 * it once when a heat reaches `DONE` and appends one `SignalHistory` per node. The `signal_trace`
 * projection **prefers** this dense history over the coarse [`SignalChunk`] samples for a
 * competitor when both are present (the dense trace supersedes the streaming approximation).
 *
 * # Why explicit per-sample times (not a uniform cadence)
 *
 * [`SignalChunk`] assumes a fixed `period_micros` because the live stream emits on a regular
 * heartbeat. The detector's internal history is **not** guaranteed uniform — RotorHazard reports a
 * parallel `history_times`/`history_values` pair — so this carries the per-sample times directly
 * (`times[i]` is the source-clock instant of `rssi[i]`), preserving native fidelity with **no
 * resampling** (the load-bearing fidelity caution, marshaling.html §4). Times are race-relative
 * microseconds on the same clock as [`Pass::at`] and the chunk time base, so lap markers and the
 * dense trace align.
 */
export type SignalHistory = { 
/**
 * The timing source that produced this history.
 */
adapter: AdapterId, 
/**
 * The source-local competitor (node seat) the history belongs to.
 */
competitor: CompetitorRef, 
/**
 * The source-clock timestamp (race-relative µs) of each sample, parallel to `rssi`. Same
 * length as `rssi`; `times[i]` is when `rssi[i]` was recorded. Renders as TS `number[]`
 * (bounded far below 2^53).
 */
times: number[], 
/**
 * The dense per-tick RSSI samples (filtered ADC counts), parallel to `times`.
 */
rssi: Array<number>, };
