// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";

/**
 * The enter/exit detection thresholds a signal-capable timer is configured with for a node —
 * the levels the RSSI crosses to open/close a pass (RotorHazard `enter_at_level` /
 * `exit_at_level`). Captured **once** alongside the [`SignalChunk`] trace so a marshal can
 * see *why* the timer called (or missed) a lap against the visible signal (marshaling.html
 * §3.2). One-shot per `(adapter, competitor)`; a later one supersedes (the projection keeps
 * the last).
 */
export type SignalThresholds = { 
/**
 * The timing source these thresholds belong to.
 */
adapter: AdapterId, 
/**
 * The source-local competitor (node seat) the thresholds apply to.
 */
competitor: CompetitorRef, 
/**
 * The **enter** threshold: RSSI rising above this opens a pass.
 */
enter: number, 
/**
 * The **exit** threshold: RSSI falling below this closes the pass.
 */
exit: number, };
