// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional signal detail beneath a crossing, present only where the source has it
 * (RotorHazard/LapRF). A simulator reports an exact crossing with nothing
 * underneath, so this is `None` there — and signal-based lap recovery is simply
 * unavailable for such adapters. Kept minimal for now; hardware adapters (v0.2)
 * extend it.
 */
export type SignalContext = { 
/**
 * Peak RSSI at the crossing, if reported.
 */
rssi_peak: number | null, };
