// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { CompetitorRef } from "./CompetitorRef";
import type { SourceTime } from "./SourceTime";

/**
 * A contiguous run of per-tick RSSI samples captured from a signal-capable timer
 * (RotorHazard first — marshaling.html §3.2, the signal-as-evidence layer).
 *
 * The trace is the **evidence** a marshal later reviews a call against. It is captured
 * **chunked and append-incrementally** rather than one fat per-heat blob: a hardware timer
 * streams its node RSSI continuously, so chunks append as the run proceeds and interleave
 * deterministically with the [`Pass`]es in the same log — a single buffered-until-heat-end
 * event would be lost on an abort. Each chunk is a window of `rssi` samples beginning at
 * `from` on the source clock, one every `period_micros`; concatenating a competitor's chunks
 * in append order reconstructs the whole trace (the projection's job, see
 * `gridfpv_projection::signal_trace`).
 *
 * `rssi` is kept as `u16` — RotorHazard's filtered ADC counts are integers, so this is
 * compact, exact, and free of the float-equality hazards a `f32` trace would carry into the
 * deterministic fold/tests (matching the events crate's integer-time convention).
 *
 * # Fidelity bound
 *
 * RotorHazard's streaming `node_data` socket emit carries only the **latest** per-node
 * sample (`pass_peak_rssi`/`node_peak_rssi`), not a backfilled per-tick history array (that
 * lives in the request-driven `current_marshal_data`, which a live translator does not
 * subscribe to). So a chunk captured from the live stream samples at the emit cadence — one
 * `rssi` value per `node_data` tick — which is faithful to *what RH exposes live*, but is
 * coarser than the detector's internal sampling. This is the load-bearing fidelity bound
 * (marshaling.html §4) to confirm on real hardware.
 */
export type SignalChunk = { 
/**
 * The timing source that produced this trace.
 */
adapter: AdapterId, 
/**
 * The source-local competitor (node seat) the trace belongs to.
 */
competitor: CompetitorRef, 
/**
 * The source-clock timestamp of the **first** sample in `rssi`.
 */
from: SourceTime, 
/**
 * Microseconds between consecutive samples (the capture cadence).
 */
period_micros: number, 
/**
 * The RSSI samples (filtered ADC counts), oldest first, one every `period_micros`.
 */
rssi: Array<number>, };
