// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorTrace } from "./CompetitorTrace";

/**
 * The signal-trace read model for a heat: one [`CompetitorTrace`] per competitor that produced
 * any signal facts, ordered deterministically by [`CompetitorKey`] (marshaling Slice 1).
 */
export type SignalTraceView = { 
/**
 * Per-competitor traces, ordered by competitor key.
 */
competitors: Array<CompetitorTrace>, };
