// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cursor } from "./Cursor";
import type { ProjectionBody } from "./ProjectionBody";

/**
 * A snapshot of a scoped projection (protocol.html §2): the current materialized
 * [`ProjectionBody`] plus the [`Cursor`] the change stream resumes from.
 *
 * "Snapshot first, then subscribe" (§2): the client renders the `body` immediately and
 * opens the stream `from` this `cursor`, so the first envelope it applies is exactly
 * the one after the snapshot — nothing missed, nothing double-applied. Re-snapshotting
 * is always correct because projections are recomputable; the stream is an
 * optimization, never the source of truth (§3).
 */
export type Snapshot = { 
/**
 * The stream cursor this snapshot was taken at — where the subscription resumes.
 */
cursor: Cursor, 
/**
 * The materialized projection at that cursor.
 */
body: ProjectionBody, };
