// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A timestamp in the **source's own clock**, stored as microseconds.
 *
 * Lap and split durations are computed from these values, which are internally
 * consistent and immune to network jitter. Game-engine time (Velocidrone), server
 * time (RotorHazard), device RTC (LapRF) and wall clock (manual) all reduce to a
 * microsecond count on their own timeline; the adapter maps that timeline onto the
 * Director's session axis separately. Integer microseconds keep interval math exact
 * and comparisons stable (no float-equality hazards in tests).
 */
export type SourceTime = number;
