// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The start-tone cue for a [`StartProcedure`] (heat-lifecycle Slice 2) — stored config the console
 * uses to play the go-tone (the audio UX lands in Slice 3). Kept minimal and additive.
 */
export type StartTone = { 
/**
 * The tone frequency in hertz (e.g. `880`). Absent fields default in the console.
 */
hz?: number, 
/**
 * The tone duration in milliseconds (e.g. `400`).
 */
ms?: number, };
