// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartTone } from "./StartTone";

/**
 * The **start procedure** that drives a heat's `Armed → Running` auto-transition (heat-lifecycle
 * Slice 2).
 *
 * An **extensible** enum (today the one [`RandomizedDelay`](Self::randomized-delay) mode): the
 * runtime reads it when a heat enters `Armed`, picks a delay in the procedure's window **once**,
 * writes it to the log as a fact ([`Event::HeatStarting`](gridfpv_events::Event::HeatStarting)),
 * and schedules the `Running` transition for then. Randomization happens only in the runtime at
 * emission time, never in the fold, so a replay reads the logged delay and reproduces the start
 * exactly (race-engine.html §6). Derives serde + `ts_rs::TS`.
 *
 * Serialized **internally tagged** on `mode` (e.g. `{ "mode": "randomized-delay", ... }`) so a
 * future mode (a fixed countdown, an external arm-tone trigger) is an additive variant.
 */
export type StartProcedure = { "mode": "randomized-delay", 
/**
 * The shortest the runtime will hold before `Running`, in milliseconds.
 */
min_delay_ms: number, 
/**
 * The longest the runtime will hold before `Running`, in milliseconds. Must be ≥
 * `min_delay_ms` (the runtime clamps a mis-ordered pair to a point delay defensively).
 */
max_delay_ms: number, 
/**
 * Optional start-tone cue config for the console (heat-lifecycle Slice 3 renders/plays it;
 * stored here now). Absent ⇒ the console uses its default tone.
 */
tone?: StartTone, };
