// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeEnvelope } from "./ChangeEnvelope";
import type { ProtocolError } from "./ProtocolError";

/**
 * A frame the server sends down the change-stream WebSocket (protocol.html §3).
 *
 * Almost every frame is a [`ChangeEnvelope`]; the one exception is the distinguished
 * **re-snapshot-required** signal the server sends when a client resumes from a cursor
 * older than the bounded retained window (§3 "fall back to re-snapshot"). Modelling
 * both as one externally-tagged enum means a client reads a single message type off the
 * socket and branches on the tag, rather than guessing whether a frame is data or a
 * control signal.
 *
 * Externally tagged, mapping to a TS discriminated union.
 */
export type StreamMessage = { "Change": ChangeEnvelope } | { "ReSnapshotRequired": ProtocolError };
