// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractVersion } from "./ContractVersion";
import type { Cursor } from "./Cursor";
import type { Scope } from "./Scope";

/**
 * A subscription request (protocol.html §3, §4): a [`Scope`] plus where to resume
 * the stream from.
 *
 * `from` is the last-applied [`Cursor`](crate::stream::Cursor) the client presents on
 * (re)connect — `Some(cursor)` to resume after a drop, `None` for a fresh
 * subscription that begins from the snapshot's cursor (protocol.html §3 "resume by
 * cursor, fall back to re-snapshot"). If the gap is too old to replay the server
 * answers with a [`StaleCursor`](crate::error::ErrorCode::StaleCursor) error and the
 * client re-snapshots.
 * The subscribe frame doubles as the **connect message** for the WS read path
 * (protocol.html §7): it carries the client's [`ContractVersion`](crate::ContractVersion)
 * (`contract_version`) so the server can negotiate the contract band before streaming,
 * and an optional read **token** (`token`) — a bearer or read-only join-token — so a
 * gated deployment can authenticate the read on the same frame. Both are optional and
 * default-absent so an existing fresh subscribe (just a `scope`) is unchanged on the
 * wire; a missing `contract_version` is treated as this build's [`CONTRACT_VERSION`]
 * (the legacy/unspecified client), and a missing `token` is an anonymous LAN read.
 */
export type SubscribeRequest = { 
/**
 * The resource this subscription is scoped to.
 */
scope: Scope, 
/**
 * The cursor to resume after, or `None` to start fresh from the snapshot.
 */
from?: Cursor, 
/**
 * The contract version the client was built against (protocol.html §7). Checked
 * against the server's supported band before the stream starts; out of band gets the
 * "please refresh" [`VersionMismatch`](crate::error::ErrorCode::VersionMismatch)
 * signal. Absent means "unspecified" — treated as the server's own
 * [`CONTRACT_VERSION`](crate::CONTRACT_VERSION).
 */
contract_version?: ContractVersion, 
/**
 * An optional read credential (protocol.html §5): a bearer or read-only join-token.
 * Reads are open on the LAN, so this is omitted by an anonymous viewer; when present
 * it must be valid (an unknown/revoked token is rejected).
 */
token?: string, };
