// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cursor } from "./Cursor";
import type { Scope } from "./Scope";

/**
 * A subscription request (protocol.html §3, §4): a [`Scope`] plus where to resume
 * the stream from.
 *
 * `from` is the last-applied [`Cursor`](crate::stream::Cursor) the client presents on
 * (re)connect — `Some(cursor)` to resume after a drop, `None` for a fresh
 * subscription that begins from the snapshot's cursor (protocol.html §3 "resume by
 * cursor, fall back to re-snapshot"). If the gap is too old to replay the server
 * answers with a [`StaleCursor`](crate::error::ErrorCode::StaleCursor) error and the
 * client re-snapshots.
 */
export type SubscribeRequest = { 
/**
 * The resource this subscription is scoped to.
 */
scope: Scope, 
/**
 * The cursor to resume after, or `None` to start fresh from the snapshot.
 */
from?: Cursor, };
