// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCapability } from "./ChannelCapability";
import type { NodeCalibration } from "./NodeCalibration";
import type { NodeChannel } from "./NodeChannel";
import type { PluginPresence } from "./PluginPresence";
import type { TimerId } from "./TimerId";
import type { TimerKind } from "./TimerKind";
import type { TimerStatus } from "./TimerStatus";

/**
 * One configured timer in the application-level registry (issue #73).
 *
 * The wire shape `GET /timers` returns and the on-disk shape `timers.json` persists: a stable
 * [`TimerId`], a human display `name`, the [`TimerKind`] (its config), and a derived
 * [`TimerStatus`]. Derives serde (its JSON *is* both the wire and the persisted form) and
 * `ts_rs::TS` so the frontend reads a generated `Timer` type.
 */
export type Timer = { 
/**
 * The stable handle an event selects by and the API addresses (`PUT /timers/{id}`).
 */
id: TimerId, 
/**
 * The human-readable display name (display-only; the id is authoritative).
 */
name: string, 
/**
 * The kind + config: a [`TimerKind::Mock`] or a [`TimerKind::Rotorhazard`].
 */
kind: TimerKind, 
/**
 * The derived usability of the timer (see [`TimerStatus`]).
 */
status: TimerStatus, 
/**
 * The timer's **channel capability** (race redesign Slice 4a): the set of frequencies it can
 * tune to ([`Fixed`](ChannelCapability::Fixed)) or that it tunes freely
 * ([`Flexible`](ChannelCapability::Flexible)). Additive — defaults to
 * [`Flexible`](ChannelCapability::Flexible) for a pre-channel-model timer.
 */
channel_capability: ChannelCapability, 
/**
 * The Race Director's **explicit width override** — how many nodes GridFPV should treat this
 * timer as having, regardless of what the hardware says (#412).
 *
 * `None` — the default for a newly created timer — means **follow the timer**: the width comes
 * from [`reported_nodes`](Timer::reported_nodes), discovered on connect. `Some(n)` pins it,
 * which is what a Mock (nothing to ask) and a timer whose RD deliberately set a width use.
 * [`node_width`](Timer::node_width) resolves the two.
 *
 * **Migration (#412).** This was a plain `u32` defaulting to [`DEFAULT_NODE_COUNT`], and the
 * registry always wrote it — so every pre-#412 `timers.json` carries an explicit number and
 * reads back as `Some(n)`, keeping exactly the width it had. Only timers created *after* this
 * change start out following the hardware. A disagreement between this and what the timer
 * reports is surfaced as [`NodeDrift`], never silently resolved.
 */
node_count?: number, 
/**
 * How many nodes the timer **said it has**, learned on connect (#412) — an *observation*, not
 * config.
 *
 * RotorHazard publishes no `num_nodes` scalar on the socket, but the count is knowable three
 * ways, and the Director takes the most direct one available on each (re)connect: the GridFPV
 * plugin's `gridfpv_hello_ack` (`len(rhapi.interface.seats)`), else the length of
 * `frequency_data.fdata`, else the `[:num_nodes]`-sliced `enter_and_exit_at_levels`. `None`
 * means the timer has never been asked — a Mock, an adapter that cannot report, or an RH not
 * yet dialed.
 *
 * **Live, in-memory, never persisted as config** (D27: *"a value read from a timer is evidence
 * about the timer, not an input to a decision"*). Like [`plugin`](Timer::plugin) it round-trips
 * on the wire but is reset to `None` on load, so a restart re-observes rather than remembering.
 */
reported_nodes?: number, 
/**
 * The node indices (**0-based**) the Race Director has **disabled** on this timer (#412) — a
 * dead receiver, a gate that will not tune, a seat that must not be flown.
 *
 * **This is a decision, so it is persisted and it survives a reconnect.** A timer that keeps
 * reporting four nodes does not re-enable node 3; the RD turned it off on purpose. Stored as
 * the *complement* of the enabled set precisely so it stays meaningful when the reported width
 * changes: "node 2 is busted" is true whether the timer reports 4 nodes or 8.
 *
 * Sorted ascending and de-duplicated on write. Entries at or beyond
 * [`node_width`](Timer::node_width) are inert (there is no such node to disable) but are kept
 * rather than pruned — a timer that comes back wider must not silently un-disable a node.
 * Additive on the wire and on disk: an older `timers.json` restores with none disabled, which
 * is every node enabled — exactly the pre-#412 behaviour.
 *
 * **0-based on the wire, 1-based on screen.** Index `2` is the node the RD calls "Node 3"; see
 * [`Timer::node_label`].
 */
disabled_nodes: Array<number>, 
/**
 * The timer's **allowed channel set** (race redesign Slice 4a; #117 S1): the raw-MHz channels
 * the Race Director has said this timer **may ever use** — what per-heat assignment draws
 * from, in preference order. Edited by the checkbox picker on the Timers page.
 *
 * **"Allowed", not "assigned", and not "capable".** Three different questions live nearby and
 * conflating them has been a recurring bug class (#402, #413, #416):
 *
 * - *What can the hardware tune?* → [`channel_capability`](Timer::channel_capability).
 *   [`Fixed`](ChannelCapability::Fixed) restricts; [`Flexible`](ChannelCapability::Flexible)
 *   does not. Assignment filters this set by it.
 * - *What may this timer be used on?* → **here**.
 * - *What is node N tuned to right now?* → [`node_channels`](Timer::node_channels) for what
 *   GridFPV last wrote from the bench, the heat's own `frequencies` for what a race allocated,
 *   `NodeSignal::frequency_mhz` for what the hardware reports. **Never this field indexed by
 *   node** — an allowed set carries no per-node mapping (that is S2's event *layers*).
 *
 * ⚠️ **Empty means "the RD has not configured this timer", and what follows differs by
 * context.** Every RotorHazard on the bench reports `Flexible` with an empty set.
 *
 * - **Offering a human a choice** (the #413 Tune-page dropdown): empty ⇒ offer the whole
 *   catalog. The RD is actively picking; show them everything the timer can do.
 * - **Assigning automatically** ([`assign_frequencies`](crate::round_engine::assign_frequencies)):
 *   empty ⇒ **refuse**, naming the timer. Inventing channels from the catalog would scatter a
 *   heat across the band with no RD intent behind it — "no channels" becoming "arbitrary
 *   channels", which is worse for looking deliberate.
 *
 * Additive — defaults empty for a pre-channel-model timer.
 */
available_channels: Array<number>, 
/**
 * Whether this (RotorHazard) timer carries the **GridFPV plugin** (D16, S1). `None` until
 * probed (Mock timers, or an RH not yet connected). Live, in-memory, not persisted — reset to
 * `None` on load/reconfigure and driven by the connect-time handshake probe. Additive on the
 * wire (`#[ts(optional)]`): an older console (or a test fixture) omits it.
 */
plugin?: PluginPresence, 
/**
 * Whether the Race Director is **manually holding a connection** to this (RotorHazard) timer,
 * independent of any event (issue #383).
 *
 * A timer only ever connected when the *active event* selected it, so "is this timer even
 * reachable?" — the question the Timers menu exists to answer — could not be asked without
 * first creating and activating an event. `POST /timers/{id}/connect` sets this hold and
 * `POST /timers/{id}/disconnect` clears it; the connection reconciler unions the held timers
 * with the active event's selection, so a held timer dials and publishes the same
 * [`TimerStatus`] and [`PluginPresence`] the event-driven path does.
 *
 * **Lifetime: explicit.** The hold persists until the RD disconnects — this is a diagnostic
 * control, and a "test connection" that silently expired would be worse than useless at a
 * venue. It is deliberately *not* dropped when an active event takes the timer over: the event
 * connection simply supersedes it, and when the event lets go the manual hold takes the timer
 * back. Live and **in-memory only**, like [`status`](Timer::status) — it round-trips on the
 * wire but a restart comes back with no holds. Additive: defaults to `false`.
 */
manual_connect: boolean, 
/**
 * The per-node enter/exit thresholds **GridFPV has set** on this timer (#355, D27), in node
 * order, one entry per node that has ever been calibrated from the Tune page.
 *
 * **This is the config; the timer is where it is applied.** D27's test — *"delete everything
 * GridFPV put on the timer, and it must rebuild identically from GridFPV's own state"* — is
 * why this is a persisted field on `Timer` rather than something read back off RotorHazard.
 * A threshold read from the timer is evidence about the timer, never an input to a decision.
 *
 * Written by [`TimerRegistry::request_calibration`] at the moment a write is **accepted**,
 * which is deliberately before the emit has landed: the record is of what GridFPV decided,
 * not of what the hardware was observed to do (that is what `GET /timers/{id}/signal` is
 * for). Additive on the wire and on disk — an older `timers.json` restores with none.
 *
 * ⚠️ **Not yet re-applied on reconnect.** D27 also asks that a timer coming back with
 * different values be pushed back to GridFPV's, with a drift notice rather than a silent
 * overwrite; that half is not built (see [`TimerRegistry::request_calibration`]).
 */
calibration: Array<NodeCalibration>, 
/**
 * The per-node channels **GridFPV has set** on this timer (#413, D27), in node order — one
 * entry per node whose channel has ever been set from the Tune page.
 *
 * The twin of [`calibration`](Timer::calibration), and for the same D27 reason: a channel is
 * Grid-owned config *applied* to the timer, exactly like a threshold. Written by
 * [`TimerRegistry::request_channel`] at the moment a write is accepted.
 *
 * ⚠️ **Distinct from [`available_channels`](Timer::available_channels).** That is the
 * *allowed set* per-heat assignment draws from — a set, carrying no per-node mapping; this is
 * what an individual node was last told to tune to from the bench. A heat legitimately
 * overwrites the latter (it re-tunes every node to its assigned channel) and this record is
 * not re-applied afterwards — the Tune page says so rather than pretending the bench value
 * wins.
 *
 * ⚠️ **Not re-applied on reconnect** either — same gap, and same reason, as `calibration`'s.
 *
 * **Additive on the wire and on disk**, and `#[ts(optional)]` like [`plugin`](Timer::plugin):
 * an empty record is omitted entirely, so a pre-#413 `timers.json` restores with none and a
 * console (or a test fixture) written before this existed still parses a `Timer`.
 */
node_channels?: Array<NodeChannel>, };
