// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a timer — *how* it produces passes (issue #73).
 *
 * Externally tagged so it maps to a TS discriminated union. [`Sim`](TimerKind::Sim) is the
 * synthetic source wired end-to-end in this slice; [`Rotorhazard`](TimerKind::Rotorhazard) is
 * **reserved / config-only** — its `url` is stored and round-trips on the wire and on disk, but
 * nothing connects to it here (that is 2b / #65). A selected RotorHazard timer is a no-op stub.
 */
export type TimerKind = { "Sim": { 
/**
 * Laps each sim pilot flies beyond the holeshot.
 */
laps: number, 
/**
 * The nominal real-time pace of one sim lap, in milliseconds.
 */
lap_ms: number, } } | { "Rotorhazard": { 
/**
 * The RotorHazard server base URL (e.g. `http://rotorhazard.local:5000`).
 */
url: string, } };
