// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a timer is currently usable, and — for a live source — the state of its connection
 * (issues #73, #65).
 *
 * Two **static** states describe a timer's resting config: the Mock is always
 * [`Ready`](TimerStatus::Ready) (it needs nothing external), and a configured-but-not-yet-dialed
 * RotorHazard timer reports [`Configured`](TimerStatus::Configured). The remaining four are
 * **dynamic** connection states the Director drives on a live (`live`-feature) RotorHazard timer
 * as its connection comes and goes: [`Connecting`](TimerStatus::Connecting) while the socket is
 * being established, [`Connected`](TimerStatus::Connected) once it is up,
 * [`Disconnected`](TimerStatus::Disconnected) when it drops, and [`Error`](TimerStatus::Error)
 * when the connection attempt fails. They are **additive on the wire** — a console that only knows
 * `Ready`/`Configured` still parses the type; new variants surface richer status.
 *
 * These dynamic states are **not persisted** (`timers.json` always restores a timer's resting
 * status from its kind — see [`Timer::status_for`]); they are live, in-memory, and reset to
 * `Configured` whenever the RH timer's kind/config **actually changes** (a no-op edit leaves the
 * live state alone — see [`TimerRegistry::update`] and #382).
 */
export type TimerStatus = "Ready" | "Configured" | "Connecting" | "Connected" | "Disconnected" | "Error";
