// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeDrift } from "./NodeDrift";
import type { TimerId } from "./TimerId";
import type { TimerNode } from "./TimerNode";

/**
 * A timer's node configuration and the observation behind it — the body of
 * `GET /timers/{id}/nodes` and `PUT /timers/{id}/nodes` (#412).
 *
 * The shape the console lays the per-node enable/disable picker out from, and the one answer to
 * "how many pilots fit in a heat on this timer?" (`enabled.len()`).
 */
export type TimerNodes = { 
/**
 * The timer this view describes.
 */
timer: TimerId, 
/**
 * How many nodes the timer **reported** on its last connect, or `None` if it has never been
 * asked (a Mock, an adapter that cannot report, an RH not yet dialed). An observation.
 */
reported?: number, 
/**
 * The RD's explicit width **override**, or `None` to follow the timer. A decision.
 */
configured?: number, 
/**
 * The **effective width** — how many node indices exist ([`Timer::node_width`]). `nodes` is
 * exactly this long.
 */
width: number, 
/**
 * Every node index `0..width`, in order, each with its display label and enabled state.
 */
nodes: Array<TimerNode>, 
/**
 * The **enabled node indices** (0-based, ascending) — the seats a heat is laid onto, in order:
 * the *n*-th pilot of a heat sits on `enabled[n]`.
 *
 * **Not necessarily `0..n`.** With node index `2` disabled on a 4-node timer this is
 * `[0, 1, 3]`, and a 3-pilot heat occupies nodes 0, 1 and 3 — a set with a hole, not a prefix.
 */
enabled: Array<number>, 
/**
 * The reported-vs-configured disagreement, when there is one (see [`NodeDrift`]).
 */
drift?: NodeDrift, };
