// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCapability } from "./ChannelCapability";
import type { PluginPresence } from "./PluginPresence";
import type { TimerId } from "./TimerId";
import type { TimerKind } from "./TimerKind";
import type { TimerStatus } from "./TimerStatus";

/**
 * One configured timer in the application-level registry (issue #73).
 *
 * The wire shape `GET /timers` returns and the on-disk shape `timers.json` persists: a stable
 * [`TimerId`], a human display `name`, the [`TimerKind`] (its config), and a derived
 * [`TimerStatus`]. Derives serde (its JSON *is* both the wire and the persisted form) and
 * `ts_rs::TS` so the frontend reads a generated `Timer` type.
 */
export type Timer = { 
/**
 * The stable handle an event selects by and the API addresses (`PUT /timers/{id}`).
 */
id: TimerId, 
/**
 * The human-readable display name (display-only; the id is authoritative).
 */
name: string, 
/**
 * The kind + config: a [`TimerKind::Mock`] or a reserved [`TimerKind::Rotorhazard`].
 */
kind: TimerKind, 
/**
 * The derived usability of the timer (see [`TimerStatus`]).
 */
status: TimerStatus, 
/**
 * The timer's **channel capability** (race redesign Slice 4a): the set of frequencies it can
 * tune to ([`Fixed`](ChannelCapability::Fixed)) or that it tunes freely
 * ([`Flexible`](ChannelCapability::Flexible)). Additive — defaults to
 * [`Flexible`](ChannelCapability::Flexible) for a pre-channel-model timer.
 */
channel_capability: ChannelCapability, 
/**
 * How many nodes/slots the timer has (race redesign Slice 4a) — the **heat-size cap**: a
 * heat's lineup must be ≤ this. Additive; defaults to [`DEFAULT_NODE_COUNT`].
 */
node_count: number, 
/**
 * The timer's **defined available channels** (race redesign Slice 4a): the raw-MHz channels,
 * within its [`channel_capability`](Timer::channel_capability), that the Race Director has
 * made available on this timer — the pool per-heat assignment allocates from, in preference
 * order. Empty means none configured (assignment then allocates nothing). Additive — defaults
 * empty for a pre-channel-model timer.
 */
available_channels: Array<number>, 
/**
 * Whether this (RotorHazard) timer carries the **GridFPV plugin** (D16, S1). `None` until
 * probed (Mock timers, or an RH not yet connected). Live, in-memory, not persisted — reset to
 * `None` on load/reconfigure and driven by the connect-time handshake probe. Additive on the
 * wire (`#[ts(optional)]`): an older console (or a test fixture) omits it.
 */
plugin?: PluginPresence, 
/**
 * Whether the Race Director is **manually holding a connection** to this (RotorHazard) timer,
 * independent of any event (issue #383).
 *
 * A timer only ever connected when the *active event* selected it, so "is this timer even
 * reachable?" — the question the Timers menu exists to answer — could not be asked without
 * first creating and activating an event. `POST /timers/{id}/connect` sets this hold and
 * `POST /timers/{id}/disconnect` clears it; the connection reconciler unions the held timers
 * with the active event's selection, so a held timer dials and publishes the same
 * [`TimerStatus`] and [`PluginPresence`] the event-driven path does.
 *
 * **Lifetime: explicit.** The hold persists until the RD disconnects — this is a diagnostic
 * control, and a "test connection" that silently expired would be worse than useless at a
 * venue. It is deliberately *not* dropped when an active event takes the timer over: the event
 * connection simply supersedes it, and when the event lets go the manual hold takes the timer
 * back. Live and **in-memory only**, like [`status`](Timer::status) — it round-trips on the
 * wire but a restart comes back with no holds. Additive: defaults to `false`.
 */
manual_connect: boolean, };
