// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeSignal } from "./NodeSignal";
import type { TimerId } from "./TimerId";

/**
 * A timer's live tuning signal — the whole of `GET /timers/{id}/signal` (#355).
 *
 * **Never an [`Event`](gridfpv_events::Event), never a log.** This is a read of a bounded
 * in-memory buffer that exists only while an RD is looking at it; it is not derived from a log,
 * it is not written to one, and it has no `SignalChunk` / `SignalHistory` in its lineage. That is
 * why it is timer-scoped and polled rather than a scoped subscription on the event change-stream:
 * it must work before an event exists at all, which is the state an untuned timer is in.
 */
export type TimerSignal = { 
/**
 * The timer this snapshot came from.
 */
timer: TimerId, 
/**
 * Whether a live connection is actually feeding this snapshot right now. `false` with a valid
 * lease means the timer is not connected (or has just dropped) — the difference between "no
 * signal" and "no link", which an RD chasing a dead gate needs to be able to tell.
 */
streaming: boolean, 
/**
 * Milliseconds left on the subscription lease before the stream stops by itself. Each `GET`
 * resets it to [`SIGNAL_LEASE`].
 */
lease_ms_remaining: number, 
/**
 * Microseconds between consecutive samples — the Director's own decimation cadence, not the
 * timer's heartbeat rate.
 */
period_micros: number, 
/**
 * The **shared** sample time base (microseconds since this subscription started), oldest
 * first: `sample_micros[i]` is when `nodes[*].samples[i]` was taken. One axis for every node
 * because every node is sampled in the same pass, so this stays O(1) per tick rather than
 * O(nodes) copies of the same numbers.
 *
 * Rendered as plain TS `number`s (`#[ts(as = …)]`), the same choice
 * [`SourceTime`](gridfpv_events::SourceTime) makes and for the same reason: a rolling window's
 * microsecond offsets sit far below 2^53, so `number` is exact — and a `bigint` here would be
 * a needless conversion between this axis and the one every other trace on screen uses.
 */
sample_micros: Array<number>, 
/**
 * Every node the timer reports, **including unseated ones** (see [`NodeSignal::seen`]), in
 * node order.
 */
nodes: Array<NodeSignal>, };
