// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorRef } from "./CompetitorRef";

/**
 * One node of a timer, as the console lays the node picker out (#412).
 *
 * Carries both halves of the 0-based/1-based boundary explicitly — the raw wire index and the
 * resolved display label — so no surface has to do the `+ 1` itself. Every off-by-one here is a
 * pilot on a dead gate, so the boundary is data rather than convention.
 */
export type TimerNode = { 
/**
 * The node's index on the timer, **0-based** — RotorHazard's `seat_index`, and the same index
 * [`NodeSignal::node`] and [`CalibrationRequest::node`] carry.
 */
node: number, 
/**
 * The node's **display name**, 1-based: node `0` is `"Node 1"` (the repo display rule). Use
 * this wherever a person reads it; never print the raw index.
 */
label: string, 
/**
 * The stable per-node competitor handle (`node-0`, `node-1`, …) — a wire handle, not a label,
 * and always the **real** node index even when the enabled set has holes in it.
 */
seat: CompetitorRef, 
/**
 * Whether the Race Director has this node **enabled**. A disabled node seats no pilot, is
 * offered no channel, and refuses calibration.
 */
enabled: boolean, 
/**
 * Whether the timer itself reported this node on its last connect. `false` on a node that
 * exists only because GridFPV is configured wider than the hardware — the drift that seats a
 * pilot on nothing.
 */
reported: boolean, };
