// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a timer is currently usable (issue #73).
 *
 * The Mock is always [`Ready`](TimerStatus::Ready) (it needs nothing external). A reserved
 * RotorHazard timer reports [`Configured`](TimerStatus::Configured) — it has a URL on file but is
 * not yet connected (2b wires the live connection and the `Connected`/`Unreachable` states).
 */
export type TimerStatus = "Ready" | "Configured";
