// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a timer — *how* it produces passes (issue #73).
 *
 * Externally tagged so it maps to a TS discriminated union. [`Mock`](TimerKind::Mock) is the
 * built-in synthetic source; [`Rotorhazard`](TimerKind::Rotorhazard) is a **real, connected**
 * timer (#65) — its `url` is stored here and round-trips on the wire and on disk, and the
 * Director dials it, probes for the GridFPV plugin, and streams its passes.
 */
export type TimerKind = { "Mock": { 
/**
 * Laps each sim pilot flies beyond the holeshot.
 */
laps: number, 
/**
 * The nominal real-time pace of one sim lap, in milliseconds.
 */
lap_ms: number, } } | { "Velocidrone": { 
/**
 * The machine running VelociDrone — its **LAN IP or hostname**, and nothing else.
 *
 * **A host, not a URL, and deliberately so.** Everything else about the address is fixed
 * by the game with no setting behind it: the scheme (`ws`, no TLS), the port (60003) and
 * the service path (`/velocidrone`). A URL field therefore asked the RD to type three
 * constants next to one variable — and the first field test did exactly what that invites,
 * entering `ws://<ip>:60003` with no path. The game's handshake parser compares the path
 * ordinally after stripping slashes, so it answered `400`, the Director reported "could
 * not reach this timer", and the sentence sent the RD to check the one thing that was
 * already working. Storing the host removes the failure class rather than documenting it.
 *
 * **It must be the LAN IP of the machine running the game, not the Director's.** The sim's
 * TCP layer binds the primary LAN IPv4 address it discovers (by probing a UDP socket at
 * `8.8.8.8:65530` and reading the local endpoint), not `IPAddress.Any` and not loopback —
 * so `127.0.0.1` cannot connect even when the sim is on this very machine.
 *
 * Normalised on the way to the dialer by
 * [`url_for_host`](gridfpv_adapters::velocidrone::transport::url_for_host), which tolerates
 * a pasted full URL and honours an explicit `:port` (for a tunnel or port-forward).
 */
host: string, } } | { "Rotorhazard": { 
/**
 * The RotorHazard server base URL — `http://<host>:5000`, e.g.
 * `http://rotorhazard.local:5000`.
 *
 * Passed **verbatim** to the socket.io client: no trimming, no trailing-slash removal, no
 * scheme defaulting. [`validate_timer_config`] only rejects empty/whitespace, so a
 * trailing slash, a missing `http://`, or `https://` against a plain-HTTP RH all reach the
 * dialer as-is and fail as a connection [`Error`](TimerStatus::Error). The console's URL
 * field states that shape (#381).
 */
url: string, } };
