// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionalEdit } from "./OptionalEdit";
import type { VtxType } from "./VtxType";

/**
 * The body of `PUT /pilots/{id}` — the editable fields of a pilot (issue #74).
 *
 * Every field is optional so a partial edit is a one-field body; the id is fixed (it is in the
 * path). A present `callsign` replaces it (a blank one is ignored — the callsign is required and
 * never cleared). Each optional-metadata field is a three-state [`OptionalEdit`]: **absent** leaves
 * it unchanged ([`Keep`](OptionalEdit::Keep)), present **`null`** clears it
 * ([`Clear`](OptionalEdit::Clear)), and present **with a value** sets it ([`Set`](OptionalEdit::Set)).
 * The wire-level distinction between "field absent" and "field present and `null`" is what lets a
 * caller both leave-alone and clear — `#[serde(default)]` on each field maps an absent field to
 * `Keep` while a present `null`/value runs [`OptionalEdit`]'s deserializer.
 */
export type UpdatePilotRequest = { 
/**
 * A new callsign, or `None`/blank to leave it unchanged.
 */
callsign?: string, 
/**
 * A new real name: present value → set, present `null` → clear, absent → leave unchanged.
 */
name?: OptionalEdit<string>, 
/**
 * A new pronunciation hint (set / clear / leave-unchanged, like [`name`](Self::name)).
 */
phonetic?: OptionalEdit<string>, 
/**
 * A new team / club (set / clear / leave-unchanged).
 */
team?: OptionalEdit<string>, 
/**
 * A new hex color `#RRGGBB` (set / clear / leave-unchanged; a set value is validated).
 */
color?: OptionalEdit<string>, 
/**
 * A new ISO 3166-1 alpha-2 country code (set / clear / leave-unchanged; a set value is
 * validated and normalized uppercase).
 */
country?: OptionalEdit<string>, 
/**
 * A **full replacement** of the VTX set when present (absent leaves it unchanged; present `[]`
 * clears it). Mirrors how [`attributes`](Self::attributes) updates — a present array replaces
 * the stored set wholesale (deduped, stable order), rather than a per-value set/clear edit.
 */
vtx_types?: Array<VtxType>, 
/**
 * A new MultiGP id (set / clear / leave-unchanged).
 */
multigp_id?: OptionalEdit<string>, 
/**
 * A new Velocidrone id (set / clear / leave-unchanged).
 */
velocidrone_id?: OptionalEdit<string>, 
/**
 * A **full replacement** of the custom-attributes bag when present (absent leaves it
 * unchanged; present `{}` clears it). Empty keys are rejected; keys/values trimmed.
 */
attributes?: { [key in string]: string }, };
