// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassSource } from "./ClassSource";
import type { OptionalEdit } from "./OptionalEdit";

/**
 * The body of `PUT /classes/{id}` — the editable fields of a class (issue #84).
 *
 * Every field is optional so a partial edit is a one-field body; the id is fixed (it is in the
 * path). A present `name` replaces it (a blank one is ignored — the name is required and never
 * cleared). A present `source` replaces the provenance. Each optional-metadata field is a
 * three-state [`OptionalEdit`]: **absent** leaves it unchanged ([`Keep`](OptionalEdit::Keep)),
 * present **`null`** clears it ([`Clear`](OptionalEdit::Clear)), and present **with a value** sets
 * it ([`Set`](OptionalEdit::Set)) — exactly the `UpdatePilotRequest` semantics.
 */
export type UpdateClassRequest = { 
/**
 * A new name, or `None`/blank to leave it unchanged.
 */
name?: string, 
/**
 * A new provenance, or `None` to leave it unchanged.
 */
source?: ClassSource, 
/**
 * A new reference id: present value → set, present `null` → clear, absent → leave unchanged.
 */
reference?: OptionalEdit<string>, 
/**
 * A new description (set / clear / leave-unchanged, like [`reference`](Self::reference)).
 */
description?: OptionalEdit<string>, };
