// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { ClassId } from "./ClassId";
import type { SeedingRule } from "./SeedingRule";
import type { WinCondition } from "./WinCondition";

/**
 * The body of `PUT /events/{id}/rounds/{round}` — the editable fields of an existing round (race
 * redesign Slice 2a). The round's [`id`](RoundDef::id) is the path segment and is **not** editable;
 * every other field is replaced wholesale. Same validation as the add path.
 */
export type UpdateRoundReq = { 
/**
 * The new display label.
 */
label: string, 
/**
 * The new eligible classes. Each must be one of the event's selected classes.
 */
classes: Array<ClassId>, 
/**
 * The new format — a known [`FormatRegistry`] name.
 */
format: string, 
/**
 * The new format config knobs, stored verbatim.
 */
params: { [key in string]: string }, 
/**
 * The new win condition.
 */
win_condition: WinCondition, 
/**
 * The new seeding rule; defaults to [`SeedingRule::FromRoster`] when omitted.
 */
seeding: SeedingRule, 
/**
 * The new channel mode (race redesign Slice 7a). Optional — **omit it** to take the format's
 * default ([`ChannelMode::default_for_format`]); supply it to override.
 */
channel_mode?: ChannelMode, };
