// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMode } from "./ChannelMode";
import type { ClassId } from "./ClassId";
import type { GraceWindow } from "./GraceWindow";
import type { LayoutId } from "./LayoutId";
import type { ProtestWindow } from "./ProtestWindow";
import type { SeedingRule } from "./SeedingRule";
import type { StartProcedure } from "./StartProcedure";
import type { WinCondition } from "./WinCondition";

/**
 * The body of `PUT /events/{id}/rounds/{round}` — the editable fields of an existing round (race
 * redesign Slice 2a). The round's [`id`](RoundDef::id) is the path segment and is **not** editable;
 * every other field is replaced wholesale. Same validation as the add path.
 */
export type UpdateRoundReq = { 
/**
 * The new display label.
 */
label: string, 
/**
 * The new eligible classes. Each must be one of the event's selected classes.
 */
classes: Array<ClassId>, 
/**
 * The new format — a known [`FormatRegistry`] name.
 */
format: string, 
/**
 * The new format config knobs, stored verbatim.
 */
params: { [key in string]: string }, 
/**
 * The new win condition. **Optional** (open-practice refinement): omit it to store the inert
 * [`default_win_condition`] (an open-practice round does no scoring).
 */
win_condition?: WinCondition, 
/**
 * The new seeding rule; defaults to [`SeedingRule::FromRoster`] when omitted.
 */
seeding: SeedingRule, 
/**
 * The new practice duration in seconds (open-practice refinement). Optional — omit for **no
 * time limit**. Stored on [`RoundDef::time_limit_secs`].
 */
time_limit_secs?: number, 
/**
 * The new channel mode (race redesign Slice 7a). Optional — **omit it** to take the format's
 * default ([`ChannelMode::default_for_format`]); supply it to override.
 */
channel_mode?: ChannelMode, 
/**
 * The new **channel layouts** this round's heats may fly (#117 S3), replaced wholesale.
 * Optional — omit for none (the auto-pick). Each must name a layout this event has.
 */
layouts?: Array<LayoutId>, 
/**
 * The new staging timer in seconds (heat-lifecycle Slice 2). Optional — omit for the
 * [`default_staging_timer_secs`] (300).
 */
staging_timer_secs?: number, 
/**
 * The new start procedure (heat-lifecycle Slice 2). Optional — omit for the
 * [`StartProcedure::default`].
 */
start_procedure?: StartProcedure, 
/**
 * The new grace window (heat-lifecycle Slice 2). Optional — omit for the
 * [`default_grace_window`].
 */
grace_window?: GraceWindow, 
/**
 * The new protest window (marshaling Slice 5). Optional — omit for the default
 * [`ProtestWindow::Off`] (manual finalize only).
 */
protest_window?: ProtestWindow, 
/**
 * Minimum lap time floor in seconds (D26); omitted/0 ⇒ off.
 */
min_lap_secs?: number, };
