// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerKind } from "./TimerKind";

/**
 * The body of `PUT /timers/{id}` — the editable fields of a timer (issue #73).
 *
 * Edits the display `name` and/or the [`TimerKind`] config (e.g. retune the sim's `lap_ms`, or
 * point a RotorHazard timer at a new URL). Both optional so a partial edit is a one-field body;
 * the id is fixed (it is in the path) and the built-in Mock may be retuned but not removed.
 */
export type UpdateTimerRequest = { 
/**
 * A new display name, or `None` to leave it unchanged.
 */
name?: string, 
/**
 * A new kind + config, or `None` to leave it unchanged.
 */
kind?: TimerKind, };
