// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionalEdit } from "./OptionalEdit";
import type { VtxType } from "./VtxType";

/**
 * The body of `PUT /pilots/{id}` — the editable fields of a pilot (issue #74).
 *
 * Every field is optional so a partial edit is a one-field body; the id is fixed (it is in the
 * path). A present `callsign` replaces it (a blank one is ignored — the callsign is required and
 * never cleared). For the optional metadata, a present field **replaces** the stored value
 * (including with `null` to clear it); an absent field leaves it unchanged. The wire-level
 * distinction between "field absent" and "field present and null" is what lets a caller both
 * leave-alone and clear.
 */
export type UpdatePilotRequest = { 
/**
 * A new callsign, or `None`/blank to leave it unchanged.
 */
callsign?: string, 
/**
 * A new real name (`Some(value)` to set, `Some(null)` to clear, absent to leave unchanged).
 */
name?: OptionalEdit<string>, 
/**
 * A new VTX type (set / clear / leave-unchanged, like [`name`](Self::name)).
 */
vtx_type?: OptionalEdit<VtxType>, 
/**
 * A new MultiGP id (set / clear / leave-unchanged).
 */
multigp_id?: OptionalEdit<string>, 
/**
 * A new Velocidrone id (set / clear / leave-unchanged).
 */
velocidrone_id?: OptionalEdit<string>, };
