// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCapability } from "./ChannelCapability";
import type { TimerKind } from "./TimerKind";

/**
 * The body of `PUT /timers/{id}` — the editable fields of a timer (issue #73).
 *
 * Edits the display `name` and/or the [`TimerKind`] config (e.g. retune the sim's `lap_ms`, or
 * point a RotorHazard timer at a new URL). Both optional so a partial edit is a one-field body;
 * the id is fixed (it is in the path) and the built-in Mock may be retuned but not removed.
 */
export type UpdateTimerRequest = { 
/**
 * A new display name, or `None` to leave it unchanged.
 */
name?: string, 
/**
 * A new kind + config, or `None` to leave it unchanged.
 */
kind?: TimerKind, 
/**
 * A new **channel capability** (race redesign Slice 4a), or `None` to leave it unchanged.
 */
channel_capability?: ChannelCapability, 
/**
 * A new **node-count override** (race redesign Slice 4a; #412), or `None` to leave it
 * unchanged. Use `PUT /timers/{id}/nodes` ([`SetTimerNodesRequest`]) to *clear* the override
 * (follow the timer) or to enable/disable individual nodes — this field can only set one.
 */
node_count?: number, 
/**
 * A new **available-channels** set in raw MHz (race redesign Slice 4a), or `None` to leave it
 * unchanged.
 */
available_channels?: Array<number>, };
