// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRef } from "./LogRef";
import type { SourceTime } from "./SourceTime";
import type { VoidReason } from "./VoidReason";

/**
 * One RD-voided gate pass, as the lap list records it (see [`CompetitorLaps::voided`]).
 */
export type VoidedPass = { 
/**
 * Source-clock time (µs) of the voided pass — its RAW instant (no re-time applied): the
 * removal record exists so re-detection can recognise the crossing on the trace, and the
 * trace knows nothing of a re-time.
 */
at: SourceTime, 
/**
 * The voided pass's own global log offset (a stable row identity for the UI).
 */
pass_ref: LogRef, 
/**
 * The **standing void event's** offset — the target a RESTORE (void-the-void) addresses.
 * For an AUTO-suppressed pass (see [`VoidReason::UnderMinLap`]) this is the pass's own
 * offset: there is no void event, and the restore path is a marshal ruling on the pass
 * itself (an [`Event::LapAdjusted`] re-asserting its raw instant — an explicit ruling
 * always outranks the floor).
 */
void_ref: LogRef, 
/**
 * WHY the pass is off the lap chain — the console labels the row (and picks the restore
 * command) by this.
 */
reason: VoidReason, };
