// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRef } from "./LogRef";
import type { SourceTime } from "./SourceTime";

/**
 * One RD-voided gate pass, as the lap list records it (see [`CompetitorLaps::voided`]).
 */
export type VoidedPass = { 
/**
 * Source-clock time (µs) the voided pass was recorded at (re-time applied, like a
 * surviving pass — the instant re-detection would re-find it at).
 */
at: SourceTime, 
/**
 * The voided pass's own global log offset (a stable row identity for the UI).
 */
pass_ref: LogRef, };
