// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogRef } from "./LogRef";
import type { SourceTime } from "./SourceTime";

/**
 * One RD-voided gate pass, as the lap list records it (see [`CompetitorLaps::voided`]).
 */
export type VoidedPass = { 
/**
 * Source-clock time (µs) of the voided pass — its RAW instant (no re-time applied): the
 * removal record exists so re-detection can recognise the crossing on the trace, and the
 * trace knows nothing of a re-time.
 */
at: SourceTime, 
/**
 * The voided pass's own global log offset (a stable row identity for the UI).
 */
pass_ref: LogRef, 
/**
 * The **standing void event's** offset — the target a RESTORE (void-the-void) addresses.
 */
void_ref: LogRef, };
