// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a pass sits on the removal record instead of the lap chain.
 */
export type VoidReason = "Marshal" | "UnderMinLap";
