// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of **video transmitter** a pilot flies (issue #74).
 *
 * A small closed enum the directory records so the RD can group / display pilots by their video
 * system. Externally tagged (the default serde enum representation) so it maps to a TS string
 * union (`"Analog" | "HDZero" | "DJI" | "Walksnail"`). Optional on a [`Pilot`] — a directory
 * entry need not state a VTX type.
 */
export type VtxType = "Analog" | "HDZero" | "DJI" | "Walksnail";
