// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of **video transmitter** a pilot flies (issue #74).
 *
 * A small closed enum the directory records so the RD can group / display pilots by their video
 * system. Externally tagged (the default serde enum representation) so it maps to a TS string
 * union (`"Analog" | "HDZero" | "DJI" | "Walksnail" | "Other"`). A pilot carries a **set** of
 * these (see [`Pilot::vtx_types`]) since many pilots run more than one video system; the
 * [`Other`](VtxType::Other) variant is the catch-all for anything not enumerated.
 */
export type VtxType = "Analog" | "HDZero" | "DJI" | "Walksnail" | "Other";
