// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a heat is won — the configured per-heat / per-format scoring rule
 * (race-engine.html §4, §7.1).
 */
export type WinCondition = { "Timed": { 
/**
 * Window length in microseconds, measured from the race start.
 * Renders as a plain TS `number` (bounded far below 2^53).
 */
window_micros: number, } } | { "FirstToLaps": { 
/**
 * The target lap count.
 */
n: number, } } | "BestLap" | { "BestConsecutive": { 
/**
 * How many consecutive laps the window spans.
 */
n: number, } };
